"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {useSearchParams} from "next/navigation";
import {ArrowRight,Clock3,FilePlus2,RefreshCw,ShieldCheck,Swords,X} from "lucide-react";
import {useT} from "@/i18n/I18nProvider";
import {useAuth} from "@/store/auth";
import {AccountPanel} from "@/components/account/account-panel";
import {POKE_GAMES} from "@/poke/registry";
import {pl,type PokeDifficulty,type PokeGameId} from "@/poke/types";
import {actOnPokeChallenge,createPokeChallenge,getPokeChallenges,type PokeChallenge} from "@/poke/online";

export function PokeChallenges(){
 const{locale}=useT(),user=useAuth((state)=>state.user),loaded=useAuth((state)=>state.loaded);
 const suggestedOpponent=useSearchParams().get("opponent")??"";
 const [challenges,setChallenges]=useState<PokeChallenge[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[opponent,setOpponent]=useState(suggestedOpponent),[gameId,setGameId]=useState<PokeGameId>(POKE_GAMES[0].id),[difficulty,setDifficulty]=useState<PokeDifficulty>("medium"),[generationCap,setGenerationCap]=useState(1),[rounds,setRounds]=useState<5|10|20>(5);
 const refresh=()=>{setLoading(true);getPokeChallenges().then((result)=>{setChallenges(result.challenges??[]);setError(result.error??"");setLoading(false)})};
 useEffect(()=>{if(user)refresh();else setLoading(false)},[user]);
 const create=async(event:React.FormEvent)=>{event.preventDefault();setError("");const result=await createPokeChallenge({opponentName:opponent,gameId,difficulty,generationCap,rounds});if(!result.ok){setError(result.error??"error");return}setOpponent("");refresh()};
 const act=async(id:string,action:"accept"|"decline"|"cancel")=>{const result=await actOnPokeChallenge(id,action);if(!result.ok)setError(result.error??"error");refresh()};
 if(!loaded)return null;
 if(!user)return <div className="poke-stats-page"><header><span><Swords/></span><p className="poke-kicker">DIRECT ASYNC MISSIONS</p><h1>{locale==="de"?"Trainer Challenges":"Trainer challenges"}</h1></header><div className="poke-profile-auth"><ShieldCheck/><h2>{locale==="de"?"Direkte Challenges brauchen eine Identität":"Direct challenges need an identity"}</h2><p>{locale==="de"?"Nutze deinen bestehenden GeoNerds-Account. Es gibt kein Fake-Matchmaking: Du forderst gezielt einen bekannten Trainernamen heraus.":"Use your existing GeoNerds account. There is no fake matchmaking: challenge a known trainer name directly."}</p><AccountPanel/></div></div>;
 const active=challenges.filter((item)=>["pending","active"].includes(item.status)),history=challenges.filter((item)=>!["pending","active"].includes(item.status));
 return <div className="poke-stats-page poke-challenges-page"><header><span><Swords/></span><p className="poke-kicker">DIRECT ASYNC MISSIONS</p><h1>{locale==="de"?"Trainer Challenges":"Trainer challenges"}</h1></header>
  <form className="poke-challenge-creator" onSubmit={create}><header><FilePlus2/><div><p className="poke-kicker">SEALED TWO-TRAINER DOSSIER</p><h2>{locale==="de"?"Neue Challenge ausstellen":"Issue a new challenge"}</h2></div></header><label>{locale==="de"?"Gegnerischer Trainername":"Opponent trainer name"}<input required minLength={2} maxLength={40} value={opponent} onChange={(event)=>setOpponent(event.target.value)} placeholder="Trainer name"/></label><div><label>{locale==="de"?"Mission":"Mission"}<select value={gameId} onChange={(event)=>setGameId(event.target.value as PokeGameId)}>{POKE_GAMES.map((game)=><option value={game.id} key={game.id}>{pl(game.title,locale)}</option>)}</select></label><label>{locale==="de"?"Schwierigkeit":"Difficulty"}<select value={difficulty} onChange={(event)=>setDifficulty(event.target.value as PokeDifficulty)}><option>easy</option><option>medium</option><option>hard</option></select></label><label>GEN CAP<input type="number" min="1" max="9" value={generationCap} onChange={(event)=>setGenerationCap(Number(event.target.value))}/></label><label>{locale==="de"?"Runden":"Rounds"}<select value={rounds} onChange={(event)=>setRounds(Number(event.target.value) as 5|10|20)}><option>5</option><option>10</option><option>20</option></select></label></div><button className="poke-primary"><Swords/>{locale==="de"?"Dossier versiegeln":"Seal dossier"}</button><small>{locale==="de"?"Der Server stellt einen gemeinsamen Seed aus. Er wird erst nach Annahme sichtbar.":"The server issues one shared seed. It is revealed only after acceptance."}</small></form>
  {error&&<div className="poke-error-state" role="alert"><X/>{localizedError(error,locale)}</div>}
  <section className="poke-challenge-section"><header><div><p className="poke-kicker">INBOX / ACTIVE</p><h2>{locale==="de"?"Offene Akten":"Open dossiers"}</h2></div><button onClick={refresh} aria-label="Refresh"><RefreshCw/></button></header>{loading?<div className="poke-loading-inline">OPENING SEALED FILES…</div>:active.length?<div className="poke-dossier-stack">{active.map((item)=><ChallengeDossier key={item.id} item={item} locale={locale} act={act}/>)}</div>:<div className="poke-empty"><Clock3/><b>{locale==="de"?"Keine offenen Challenges":"No open challenges"}</b><span>{locale==="de"?"Stelle oben eine direkte Akte aus.":"Issue a direct dossier above."}</span></div>}</section>
  <section className="poke-challenge-section"><header><div><p className="poke-kicker">ARCHIVE</p><h2>{locale==="de"?"Verlauf":"History"}</h2></div></header><div className="poke-dossier-stack">{history.map((item)=><ChallengeDossier key={item.id} item={item} locale={locale} act={act}/>)}</div></section>
 </div>;
}
function ChallengeDossier({item,locale,act}:{item:PokeChallenge;locale:"en"|"de";act:(id:string,action:"accept"|"decline"|"cancel")=>void}){
 const game=POKE_GAMES.find((entry)=>entry.id===item.gameId)!;
 const outcome=item.viewerOutcome==="win"?(locale==="de"?"SIEG":"VICTORY"):item.viewerOutcome==="loss"?(locale==="de"?"NIEDERLAGE":"DEFEAT"):locale==="de"?"UNENTSCHIEDEN":"DRAW";
 return <article className={`poke-challenge-dossier status-${item.status}`}><header><span>FILE {item.id.slice(0,8).toUpperCase()}</span><b>{item.status}</b><small>{new Date(item.expiresAt).toLocaleDateString(locale)}</small></header><div className="poke-versus-panels"><section><small>{item.direction==="sent"?"CHALLENGER":"YOU"}</small><b>{item.direction==="sent"?"YOU":item.challengerName}</b><i/></section><div><Swords/><span>VS</span></div><section><small>{item.direction==="sent"?"RIVAL":"CHALLENGER"}</small><b>{item.opponentName}</b><i/></section></div><dl><div><dt>MISSION</dt><dd>{pl(game.title,locale)}</dd></div><div><dt>CONFIG</dt><dd>{item.difficulty.toUpperCase()} · GEN 1–{item.generationCap} · {item.rounds}R</dd></div><div><dt>SEED</dt><dd>{item.seed?`${item.seed.slice(0,18)}…`:"SEALED UNTIL ACCEPTED"}</dd></div><div><dt>RESULT SLOTS</dt><dd>{item.attemptCount??0}/2 LOCKED</dd></div></dl><footer>{item.status==="pending"&&item.direction==="received"&&<><button className="poke-primary" onClick={()=>act(item.id,"accept")}>{locale==="de"?"Annehmen":"Accept"}</button><button className="poke-secondary" onClick={()=>act(item.id,"decline")}>{locale==="de"?"Ablehnen":"Decline"}</button></>}{item.status==="pending"&&item.direction==="sent"&&<button className="poke-secondary" onClick={()=>act(item.id,"cancel")}>{locale==="de"?"Zurückziehen":"Cancel"}</button>}{item.status==="active"&&!item.viewerAttempted&&<Link className="poke-primary" href={`/poke-nerds/play/${item.gameId}?challenge=${item.id}`}>{locale==="de"?"Versuch starten":"Play attempt"}<ArrowRight/></Link>}{item.status==="active"&&item.viewerAttempted&&<span className="poke-waiting-stamp">{locale==="de"?"VERSUCH VERSIEGELT · WARTE AUF RIVALEN":"ATTEMPT SEALED · WAITING FOR RIVAL"}</span>}{item.status==="resolved"&&<><span className="poke-winner-stamp">{outcome}</span><Link className="poke-secondary" href={`/poke-nerds/challenges?opponent=${encodeURIComponent(item.opponentName)}`}>{locale==="de"?"Rückkampf konfigurieren":"Configure rematch"}</Link></>}</footer></article>;
}
function localizedError(code:string,locale:"en"|"de"){const map:Record<string,[string,string]>={unknown_trainer:["Trainer not found.","Trainer nicht gefunden."],self_challenge:["You cannot challenge yourself.","Du kannst dich nicht selbst herausfordern."],offline:["League service is offline. Local play still works.","Ligadienst offline. Lokales Spielen funktioniert weiter."],rate_limited:["Too many requests. Try again shortly.","Zu viele Anfragen. Versuche es gleich erneut."],transition_conflict:["This dossier changed moments ago. It has been refreshed.","Diese Akte wurde gerade geändert und neu geladen."],invalid_transition:["This action is no longer available.","Diese Aktion ist nicht mehr verfügbar."],expired:["This challenge has expired.","Diese Challenge ist abgelaufen."]};return map[code]?.[locale==="de"?1:0]??code}
