"use client";
import Link from "next/link";
import {useState} from "react";
import {ArrowLeft,Check,RotateCcw,Sparkles} from "lucide-react";
import {useT} from "@/i18n/I18nProvider";
import {getPokeGame} from "@/poke/registry";
import {pl,type PokeDifficulty,type PokeGameId,type PokeRun} from "@/poke/types";
import {usePokeDex,usePokeProgression,usePokeScores} from "@/poke/store";
import {PokePathExpedition,RegionRanger,HabitatHunt,TypeClashArena,GymDraftGauntlet} from "./games/exploration-games";
import {CryRadar,EvolutionLab,FieldScanner,PokeGrid,ProfessorCaseFiles} from "./games/lab-games";
const components={ "poke-path-expedition":PokePathExpedition,"region-ranger":RegionRanger,"habitat-hunt":HabitatHunt,"type-clash-arena":TypeClashArena,"gym-draft-gauntlet":GymDraftGauntlet,"evolution-lab":EvolutionLab,"field-scanner":FieldScanner,"cry-radar":CryRadar,"poke-grid":PokeGrid,"professor-case-files":ProfessorCaseFiles};
const mapGames:PokeGameId[]=["poke-path-expedition","region-ranger","habitat-hunt"];
export function PokeGameRunner({gameId}:{gameId:PokeGameId}){
 const {locale}=useT();const game=getPokeGame(gameId);const [started,setStarted]=useState(false);const [difficulty,setDifficulty]=useState<PokeDifficulty>("medium");const [practice,setPractice]=useState(false);const [generationCap,setGenerationCap]=useState(1);const [result,setResult]=useState<{score:number;correct:number;total:number}|null>(null);const record=usePokeProgression((state)=>state.record);const add=usePokeScores((state)=>state.add);const encounter=usePokeDex((state)=>state.encounter);const Component=components[gameId];const isMap=mapGames.includes(gameId);
 const finish=(score:number,correct:number,total:number,speciesIds:number[])=>{const run:PokeRun={id:crypto.randomUUID(),gameId,score,correct,total,difficulty,practice,speciesIds,createdAt:Date.now()};record(run);add(run);speciesIds.forEach((id)=>encounter(id,gameId,correct>0));setResult({score,correct,total})};
 if(result)return <div className="poke-result"><div className="poke-result-mark"><Check/></div><p className="poke-kicker">MISSION ARCHIVED</p><h1>{pl(game.title,locale)}</h1><div><span><b>{result.score}</b> SCORE</span><span><b>{result.correct}/{result.total}</b> VALID</span><span><b>{practice?"OFF":"ON"}</b> PROGRESS</span></div><p>{locale==="de"?"Der Feldbericht wurde verarbeitet. Neue Begegnungen stehen im PokéDex bereit.":"The field report has been processed. New encounters are waiting in your PokéDex."}</p><button className="poke-primary" onClick={()=>{setResult(null);setStarted(false)}}><RotateCcw/>{locale==="de"?"Neuen Run konfigurieren":"Configure another run"}</button><Link className="poke-secondary" href="/poke-nerds">{locale==="de"?"Zur Forschungsbasis":"Research base"}</Link></div>;
 if(!started)return <div className="poke-game-setup"><Link className="poke-back" href="/poke-nerds"><ArrowLeft/>{locale==="de"?"Missionsverzeichnis":"Mission index"}</Link><div className={`poke-setup-signal signal-${game.signal}`}><span>{game.eyebrow[locale]}</span><i/><b>MODULE {String(Object.keys(components).indexOf(gameId)+1).padStart(2,"0")}</b></div><h1>{pl(game.title,locale)}</h1><p>{pl(game.description,locale)}</p><section className="poke-config-desk"><div><label>{locale==="de"?"Schwierigkeit":"Difficulty"}</label><div className="poke-segmented">{(["easy","medium","hard"] as const).map((option)=><button key={option} aria-pressed={difficulty===option} onClick={()=>setDifficulty(option)}>{option}</button>)}</div><small>{difficulty==="easy"?(locale==="de"?"Mehr Ressourcen und größere Toleranzen":"More resources and wider tolerances"):difficulty==="hard"?(locale==="de"?"Knappere Ressourcen und präzisere Entscheidungen":"Tighter resources and more exact decisions"):(locale==="de"?"Ausgewogene Feldbedingungen":"Balanced field conditions")}</small></div><div><label>{locale==="de"?"Pokédex-Umfang":"Pokédex scope"}</label>{isMap?<div className="poke-scope-lock"><b>KANTO · FIRERED LEARNING FIXTURES</b><span>{locale==="de"?"Kartenspiele nutzen eigens erstellte, schematische Kanto-Feldsektoren mit kuratierten Feuerrot-Lernfixtures. Die Punkte sind keine exakten Encounter- oder Stadtkoordinaten; spätere Spezies werden nicht künstlich eingesetzt.":"Map games use original schematic Kanto field sectors with curated FireRed learning fixtures. Points are not exact encounter or city coordinates; later species are not inserted inaccurately."}</span></div>:<div className="poke-generation-select">{Array.from({length:9},(_,index)=>index+1).map((cap)=><button key={cap} onClick={()=>setGenerationCap(cap)} aria-pressed={generationCap===cap}><b>{cap===1?"Gen 1":cap===9?"Gen 1–9":`→ Gen ${cap}`}</b><small>{[151,251,386,493,649,721,809,905,1025][cap-1]}</small></button>)}</div>}</div><label className="poke-practice"><input type="checkbox" checked={practice} onChange={(event)=>setPractice(event.target.checked)}/><span><b>{locale==="de"?"Übungsmodus":"Practice mode"}</b><small>{locale==="de"?"Keine XP, Scores oder Dex-Fortschritte speichern":"Do not save XP, scores or Dex progress"}</small></span></label></section><button className="poke-launch" onClick={()=>setStarted(true)}><Sparkles/>{locale==="de"?"Mission initialisieren":"Initialize mission"}<span>ENTER ↵</span></button></div>;
 return <div className="poke-game-live"><div className="poke-game-live-top"><Link href="/poke-nerds"><ArrowLeft/>{locale==="de"?"Abbrechen":"Abort"}</Link><span>{pl(game.title,locale)}</span><small>{difficulty.toUpperCase()} · {isMap?"KANTO / FIRERED":`GEN 1–${generationCap}`}</small></div><Component locale={locale} difficulty={difficulty} generationCap={generationCap} onFinish={finish}/></div>;
}
