"use client";

import {useEffect,useMemo,useState} from "react";
import {Archive,Check,Coins,Filter,Layers3,LockKeyhole,Rotate3D,Sparkles,Undo2,X} from "lucide-react";
import {useT} from "@/i18n/I18nProvider";
import {BOOSTER_COST,CARD_ODDS,FINISH_ODDS,GEN_UNLOCK_COST,standardArtworkUrl,type CardFinish,type CardRarity,type PokeCard} from "@/poke/cards";
import {SPECIES,species} from "@/poke/data";
import {STANDARD_TYPES,TYPE_COLORS,localizedType} from "@/poke/type-chart";
import {usePokeCards,usePokeProgression} from "@/poke/store";

export function PokeCards(){
 const{locale}=useT();const credits=usePokeProgression((state)=>state.researchCredits);const cards=usePokeCards();
 const[packGeneration,setPackGeneration]=useState(1);const[filterGeneration,setFilterGeneration]=useState(0);const[type,setType]=useState("all");const[rarity,setRarity]=useState("all");const[finish,setFinish]=useState("all");const[inspect,setInspect]=useState<PokeCard|null>(null);
 const collection=useMemo(()=>Object.values(cards.collection).filter(({card})=>(filterGeneration===0||card.generation===filterGeneration)&&(type==="all"||species(card.speciesId).types.includes(type))&&(rarity==="all"||card.rarity===rarity)&&(finish==="all"||card.finish===finish)),[cards.collection,filterGeneration,finish,rarity,type]);
 return <div className="poke-cards">
  <header className="poke-cards-hero"><div><p className="poke-kicker">{locale==="de"?"DIGITALE FELD-SAMMELOBJEKTE":"DIGITAL FIELD COLLECTIBLES"}</p><h1>{locale==="de"?"Kartenarchiv":"Card archive"}</h1><p>{locale==="de"?"Öffne Forschungssets, wähle exakt zwei Fundstücke und baue einen zweisprachigen Spezies-Binder.":"Open research sets, keep exactly two findings and build a bilingual specimen binder."}</p></div><div className="poke-currency"><Coins/><b>{credits}</b><span>{locale==="de"?"Forschungspunkte":"Research Credits"}</span><small>{cards.dust} {locale==="de"?"Forschungsstaub":"Research Dust"}</small></div></header>
  <aside className="poke-card-disclaimer">{locale==="de"?"Digitale Fanprojekt-Sammelobjekte ohne Geldwert, Handel oder Echtgeldkäufe. Legendär/Mythisch folgt den Speziesdaten; die übrige Seltenheit ist eine stabile eigene Taxonomie aus Entwicklung und Basiswertsumme. Finishes sind davon getrennte kosmetische Varianten.":"Digital fan-project collectibles with no monetary value, trading or real-money purchases. Legendary/Mythical follows species data; other rarity is a stable original taxonomy based on evolution and base stat total. Finishes are separate cosmetic variants."}</aside>
  <section className="poke-booster-terminal"><header><div><p className="poke-kicker">{locale==="de"?"FORSCHUNGSSET-TERMINAL":"RESEARCH SET TERMINAL"}</p><h2>{locale==="de"?"Fünf aufdecken. Zwei archivieren.":"Reveal five. Archive two."}</h2></div><span>{locale==="de"?"Seltenheitspool":"Rarity pool"}: {Object.entries(CARD_ODDS).map(([key,value])=>`${rarityLabel(key as CardRarity,locale)} ${value}%`).join(" · ")}<br/>{locale==="de"?"Finish":"Finish"}: {Object.entries(FINISH_ODDS).map(([key,value])=>`${finishLabel(key as CardFinish,locale)} ${value}%`).join(" · ")}</span></header>
   <div className="poke-pack-generations">{Array.from({length:9},(_,index)=>index+1).map((gen)=>{const unlocked=cards.unlockedGenerations.includes(gen);return <div key={gen} className={packGeneration===gen?"is-active":""}>{unlocked?<button type="button" aria-pressed={packGeneration===gen} onClick={()=>setPackGeneration(gen)}><b>GEN {gen}</b><small>{SPECIES.filter((entry)=>entry.generation===gen).length} {locale==="de"?"Karten":"cards"}</small></button>:<><span aria-hidden><LockKeyhole/></span><small>{GEN_UNLOCK_COST} {locale==="de"?"Punkte":"credits"}</small><button type="button" disabled={credits<GEN_UNLOCK_COST} onClick={()=>{if(cards.unlock(gen))setPackGeneration(gen)}}>{locale==="de"?"Freischalten":"Unlock"}</button></>}</div>})}</div>
   {!cards.pending?<div className="poke-pack-vault"><div><Layers3/><i/><span>GEN {packGeneration} {locale==="de"?"FORSCHUNGSSET":"RESEARCH SET"}</span></div><button className="poke-primary" disabled={credits<BOOSTER_COST||!cards.unlockedGenerations.includes(packGeneration)} onClick={()=>cards.open(packGeneration)}><Sparkles/>{locale==="de"?`Set öffnen · ${BOOSTER_COST} Punkte`:`Open set · ${BOOSTER_COST} credits`}</button><p>{locale==="de"?"Forschungspunkte werden ausschließlich erspielt; Trainer-XP wird nie ausgegeben.":"Research Credits are earned only through play; Trainer XP is never spent."}</p></div>:<PackSelection cards={cards.pending} selected={cards.selected} locale={locale} toggle={cards.toggle} confirm={cards.confirm} inspect={setInspect}/>}
  </section>
  <section className="poke-binder"><header><div><p className="poke-kicker">{locale==="de"?"SPEZIES-BINDER":"SPECIMEN BINDER"}</p><h2>{locale==="de"?"Deine Sammlung":"Your collection"}</h2></div><div><b>{Object.keys(cards.collection).length}</b><span>{locale==="de"?"VARIANTEN":"VARIANTS"} · {new Set(Object.values(cards.collection).map((item)=>item.card.speciesId)).size} {locale==="de"?"SPEZIES":"SPECIES"}</span></div></header>
   <div className="poke-card-filters"><Filter/><select aria-label={locale==="de"?"Generation filtern":"Filter generation"} value={filterGeneration} onChange={(event)=>setFilterGeneration(Number(event.target.value))}><option value={0}>{locale==="de"?"Alle Generationen":"All generations"}</option>{Array.from({length:9},(_,index)=><option value={index+1} key={index}>Gen {index+1}</option>)}</select><select aria-label={locale==="de"?"Typ filtern":"Filter type"} value={type} onChange={(event)=>setType(event.target.value)}><option value="all">{locale==="de"?"Alle Typen":"All types"}</option>{STANDARD_TYPES.map((item)=><option key={item} value={item}>{localizedType(item,locale)}</option>)}</select><select aria-label={locale==="de"?"Seltenheit filtern":"Filter rarity"} value={rarity} onChange={(event)=>setRarity(event.target.value)}><option value="all">{locale==="de"?"Alle Seltenheiten":"All rarities"}</option>{Object.keys(CARD_ODDS).map((item)=><option value={item} key={item}>{rarityLabel(item as CardRarity,locale)}</option>)}</select><select aria-label={locale==="de"?"Finish filtern":"Filter finish"} value={finish} onChange={(event)=>setFinish(event.target.value)}><option value="all">{locale==="de"?"Alle Finishes":"All finishes"}</option>{Object.keys(FINISH_ODDS).map((item)=><option value={item} key={item}>{finishLabel(item as CardFinish,locale)}</option>)}</select></div>
   <div className="poke-card-grid">{collection.length?collection.map(({card})=><button type="button" className="poke-card-inspect-button" onClick={()=>setInspect(card)} aria-label={`${species(card.speciesId).name[locale]} · ${locale==="de"?"Karte inspizieren":"inspect card"}`} key={`${card.speciesId}-${card.finish}`}><Card card={card} locale={locale}/></button>):<div className="poke-card-empty"><Archive/><b>{locale==="de"?"Der Binder wartet auf deine ersten zwei Karten.":"The binder is waiting for your first two cards."}</b></div>}</div>
  </section>
  {inspect&&<CardDetailViewer card={inspect} locale={locale} close={()=>setInspect(null)}/>}
 </div>;
}

function PackSelection({cards,selected,locale,toggle,confirm,inspect}:{cards:PokeCard[];selected:string[];locale:"en"|"de";toggle:(id:string)=>void;confirm:()=>boolean;inspect:(card:PokeCard)=>void}){
 return <div className="poke-pack-open"><header><span>{selected.length} / 2 {locale==="de"?"gewählt":"selected"}</span><p>{locale==="de"?"Alle fünf sind sichtbar. Wähle exakt zwei für den Binder; drei werden nach Bestätigung freigegeben.":"All five are visible. Choose exactly two for the binder; three are released after confirmation."}</p></header><div>{cards.map((card,index)=><div className="poke-pack-card-slot" key={card.id}><button aria-pressed={selected.includes(card.id)} aria-label={`${species(card.speciesId).name[locale]} · ${selected.includes(card.id)?(locale==="de"?"gewählt":"selected"):(locale==="de"?"auswählen":"select")}`} className={selected.includes(card.id)?"is-kept":""} onClick={()=>toggle(card.id)} style={{"--reveal-delay":`${index*90}ms`} as React.CSSProperties}><Card card={card} locale={locale}/>{selected.includes(card.id)&&<span><Check/> {locale==="de"?"BEHALTEN":"KEEP"} {selected.indexOf(card.id)+1}</span>}</button><button type="button" className="poke-inspect-link" onClick={()=>inspect(card)}><Rotate3D/> {locale==="de"?"Inspizieren":"Inspect"}</button></div>)}</div><button className="poke-primary" disabled={selected.length!==2} onClick={confirm}>{locale==="de"?"Zwei Karten archivieren":"Archive two cards"} <Archive/></button></div>;
}

function Card({card,locale}:{card:PokeCard;locale:"en"|"de"}){
 const entry=species(card.speciesId);const total=Object.values(entry.stats).reduce((sum,value)=>sum+value,0);const signature=locale==="de"?`BASIS ${total} · INIT ${entry.stats.speed}`:`BST ${total} · SPD ${entry.stats.speed}`;const[artFailed,setArtFailed]=useState(false);useEffect(()=>setArtFailed(false),[card.artworkUrl,card.speciesId]);
 const alternate=card.finish==="special-art"||card.finish==="gold",effectiveFinish=artFailed&&alternate?"holo":card.finish,src=artFailed?(alternate?standardArtworkUrl(entry):entry.fallbackSprite):card.artworkUrl;
 return <article className={`poke-card rarity-${card.rarity} finish-${effectiveFinish}`}><header><span>#{String(entry.id).padStart(4,"0")}</span><b>{rarityLabel(card.rarity,locale).toUpperCase()}</b></header><div className="poke-card-art"><img className="poke-sprite" src={src} onError={()=>{if(!artFailed)setArtFailed(true)}} width={145} height={145} draggable={false} alt={entry.name[locale]}/><i/></div><h3>{entry.name[locale]}</h3><div className="poke-card-types">{entry.types.map((item)=><span key={item} style={{background:TYPE_COLORS[item]}}>{localizedType(item,locale)}</span>)}</div><footer><span>GEN {entry.generation}</span><small>{signature}</small><b>{finishLabel(effectiveFinish,locale).toUpperCase()}</b></footer></article>;
}

function CardDetailViewer({card,locale,close}:{card:PokeCard;locale:"en"|"de";close:()=>void}){
 const[rotation,setRotation]=useState({x:0,y:0});const[flipped,setFlipped]=useState(false);const entry=species(card.speciesId);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==="Escape")close();if(event.key==="ArrowLeft")setRotation((value)=>({...value,y:value.y-12}));if(event.key==="ArrowRight")setRotation((value)=>({...value,y:value.y+12}));if(event.key==="ArrowUp")setRotation((value)=>({...value,x:value.x+8}));if(event.key==="ArrowDown")setRotation((value)=>({...value,x:value.x-8}))};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[close]);
 const reset=()=>{setRotation({x:0,y:0});setFlipped(false)};
 return <div className="poke-card-viewer" role="dialog" aria-modal="true" aria-label={`${entry.name[locale]} card`}>
  <button className="poke-viewer-close" onClick={close} aria-label={locale==="de"?"Schließen":"Close"}><X/></button>
  <div className="poke-viewer-object" tabIndex={0} onPointerMove={(event)=>{if(event.buttons===1)setRotation((value)=>({x:Math.max(-35,Math.min(35,value.x-event.movementY*.5)),y:value.y+event.movementX*.7}))}} style={{transform:`rotateX(${rotation.x}deg) rotateY(${rotation.y+(flipped?180:0)}deg)`}}>
   <div className="poke-viewer-face is-front"><Card card={card} locale={locale}/></div>
   <div className="poke-viewer-face is-back"><div className="poke-card-back-mark"><i/><b>POKÉ<br/>NERDS</b></div><span>FIELD RESEARCH ARCHIVE</span><small>#{String(entry.id).padStart(4,"0")} · {card.finish.toUpperCase()}</small></div>
  </div>
  <div className="poke-viewer-controls"><button onClick={()=>setFlipped((value)=>!value)}><Rotate3D/>{locale==="de"?"Umdrehen":"Flip"}</button><button onClick={reset}><Undo2/>{locale==="de"?"Zurücksetzen":"Reset"}</button><span>{locale==="de"?"Ziehen oder Pfeiltasten zum Drehen":"Drag or use arrow keys to rotate"}</span></div>
 </div>;
}

function rarityLabel(rarity:CardRarity,locale:"en"|"de"){if(locale==="en")return rarity;return({common:"häufig",uncommon:"ungewöhnlich",rare:"selten",epic:"episch",legendary:"legendär",mythical:"mythisch"} as const)[rarity]}
function finishLabel(finish:CardFinish,locale:"en"|"de"){if(locale==="en")return finish;return({standard:"standard",foil:"folie","reverse-holo":"reverse-holo",holo:"holo","special-art":"spezial-art",gold:"gold"} as const)[finish]}
