"use client";
import Link from "next/link";
import {useState} from "react";
import {ArrowLeft,Check,RotateCcw,Sparkles} from "lucide-react";
import {useT} from "@/i18n/I18nProvider";
import {getPokeGame} from "@/poke/registry";
import {pl,type PokeDifficulty,type PokeGameId,type PokeRun} from "@/poke/types";
import {usePokeDex,usePokeProgression,usePokeScores,usePokeSession} from "@/poke/store";
import {normalizeRunScore,shouldRecordDex} from "@/poke/progression";
import {PokePathExpedition,RegionRanger,HabitatHunt,TypeClashArena,GymDraftGauntlet} from "./games/exploration-games";
import {CryRadar,EvolutionLab,FieldScanner,PokeGrid,ProfessorCaseFiles} from "./games/lab-games";
const components={ "poke-path-expedition":PokePathExpedition,"region-ranger":RegionRanger,"habitat-hunt":HabitatHunt,"type-clash-arena":TypeClashArena,"gym-draft-gauntlet":GymDraftGauntlet,"evolution-lab":EvolutionLab,"field-scanner":FieldScanner,"cry-radar":CryRadar,"poke-grid":PokeGrid,"professor-case-files":ProfessorCaseFiles};
const mapGames:PokeGameId[]=["poke-path-expedition","region-ranger","habitat-hunt"];
export function PokeGameRunner({gameId}:{gameId:PokeGameId}){
 const {locale}=useT();const game=getPokeGame(gameId);const [started,setStarted]=useState(false);const [runSeed,setRunSeed]=useState<string|null>(null);const [difficulty,setDifficulty]=useState<PokeDifficulty>("medium");const [practice,setPractice]=useState(false);const [generationCap,setGenerationCap]=useState(1);const roundCount=usePokeSession((state)=>state.roundCount);const setRoundCount=usePokeSession((state)=>state.setRoundCount);const [result,setResult]=useState<{score:number;correct:number;total:number;rating:number}|null>(null);const record=usePokeProgression((state)=>state.record);const add=usePokeScores((state)=>state.add);const encounter=usePokeDex((state)=>state.encounter);const Component=components[gameId];const isMap=mapGames.includes(gameId);
 const finish=(score:number,correct:number,total:number,speciesIds:number[])=>{const rating=normalizeRunScore(score,total);const run:PokeRun={id:crypto.randomUUID(),gameId,score,correct,total,selectedRounds:roundCount,completedRounds:total,normalizedRating:rating,difficulty,practice,speciesIds,createdAt:Date.now()};record(run);add(run);if(shouldRecordDex(practice))speciesIds.forEach((id)=>encounter(id,gameId,correct>0));setResult({score,correct,total,rating})};
 if(result){const accuracy=Math.round(result.correct/Math.max(1,result.total)*100);return <div className="poke-result"><div className="poke-result-mark"><Check/></div><p className="poke-kicker">MISSION ARCHIVED</p><h1>{pl(game.title,locale)}</h1><div><span><b>{result.score}</b>{locale==="de"?"ROHPUNKTE":"RAW SCORE"}</span><span><b>{result.correct}/{result.total}</b>{accuracy}% {locale==="de"?"GENAUIGKEIT":"ACCURACY"}</span><span><b>{result.rating}</b>{locale==="de"?"RATING / 10 RUNDEN":"RATING / 10 ROUNDS"}</span></div><p>{locale==="de"?`Gewählt: ${roundCount} · tatsächlich abgeschlossen: ${result.total}. Das Rating normalisiert die Rohpunkte auf zehn abgeschlossene Runden, damit längere Runs allein keinen Rangvorteil erzeugen.`:`Selected: ${roundCount} · actually completed: ${result.total}. Rating normalizes raw score to ten completed rounds, so length alone cannot inflate rank.`}</p><button className="poke-primary" onClick={()=>{setResult(null);setStarted(false)}}><RotateCcw/>{locale==="de"?"Neuen Run konfigurieren":"Configure another run"}</button><Link className="poke-secondary" href="/poke-nerds">{locale==="de"?"Zur Forschungsbasis":"Research base"}</Link></div>}
 if(!started)return <div className="poke-game-setup"><Link className="poke-back" href="/poke-nerds"><ArrowLeft/>{locale==="de"?"Missionsverzeichnis":"Mission index"}</Link><div className={`poke-setup-signal signal-${game.signal}`}><span>{game.eyebrow[locale]}</span><i/><b>MODULE {String(Object.keys(components).indexOf(gameId)+1).padStart(2,"0")}</b></div><h1>{pl(game.title,locale)}</h1><p>{pl(game.description,locale)}</p><section className="poke-config-desk"><div><label>{locale==="de"?"Schwierigkeit":"Difficulty"}</label><div className="poke-segmented">{(["easy","medium","hard"] as const).map((option)=><button key={option} aria-pressed={difficulty===option} onClick={()=>setDifficulty(option)}>{option}</button>)}</div><small>{difficulty==="easy"?(locale==="de"?"Mehr Ressourcen und größere Toleranzen":"More resources and wider tolerances"):difficulty==="hard"?(locale==="de"?"Knappere Ressourcen und präzisere Entscheidungen":"Tighter resources and more exact decisions"):(locale==="de"?"Ausgewogene Feldbedingungen":"Balanced field conditions")}</small></div><div><label>{locale==="de"?"Missionslänge":"Mission length"}</label><div className="poke-segmented">{([5,10,20] as const).map((count)=><button key={count} aria-pressed={roundCount===count} onClick={()=>setRoundCount(count)}>{count} {locale==="de"?"Runden":"rounds"}</button>)}</div><small>{locale==="de"?"Mehr Runden geben mehr Rohpunkte; das 10-Runden-Rating bleibt vergleichbar.":"More rounds award more raw score; the per-10-round rating remains comparable."}</small></div><div><label>{locale==="de"?"Pokédex-Umfang":"Pokédex scope"}</label><div className="poke-generation-select">{Array.from({length:9},(_,index)=>index+1).map((cap)=><button key={cap} onClick={()=>setGenerationCap(cap)} aria-pressed={generationCap===cap}><b>{cap===1?"Gen 1":cap===9?"Gen 1–9":`→ Gen ${cap}`}</b><small>{[151,251,386,493,649,721,809,905,1025][cap-1]}</small></button>)}</div>{isMap&&<div className="poke-scope-lock"><b>MULTI-REGION SCHEMATIC ATLAS</b><span>{locale==="de"?"Eine Region pro Einführungsgeneration. Alle Karten und Habitatsektoren sind eigens erstellte Lernfixtures und nicht maßstabsgetreu.":"One region per introduction generation. All maps and habitat sectors are original learning fixtures and not to scale."}</span></div>}</div><label className="poke-practice"><input type="checkbox" checked={practice} onChange={(event)=>setPractice(event.target.checked)}/><span><b>{locale==="de"?"Übungsmodus":"Practice mode"}</b><small>{locale==="de"?"Keine XP, Scores oder Dex-Fortschritte speichern":"Do not save XP, scores or Dex progress"}</small></span></label></section><button className="poke-launch" onClick={()=>{const nonce=globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;setRunSeed(`${gameId}:${nonce}`);setStarted(true)}}><Sparkles/>{locale==="de"?"Mission initialisieren":"Initialize mission"}<span>NEW SEED ↻</span></button></div>;
 if(!runSeed)return null;return <div className="poke-game-live"><div className="poke-game-live-top"><Link href="/poke-nerds"><ArrowLeft/>{locale==="de"?"Abbrechen":"Abort"}</Link><span>{pl(game.title,locale)}</span><small>{difficulty.toUpperCase()} · GEN 1–{generationCap} · {roundCount}R</small></div><Component locale={locale} difficulty={difficulty} generationCap={generationCap} roundCount={roundCount} runSeed={runSeed} onFinish={finish}/></div>;
}
