"use client";
import {useMemo,useState} from "react";
import {Archive,Check,Coins,Filter,Layers3,LockKeyhole,Sparkles} from "lucide-react";
import {useT} from "@/i18n/I18nProvider";
import {BOOSTER_COST,CARD_ODDS,GEN_UNLOCK_COST,type CardRarity,type PokeCard} from "@/poke/cards";
import {SPECIES,species} from "@/poke/data";
import {STANDARD_TYPES,TYPE_COLORS,localizedType} from "@/poke/type-chart";
import {usePokeCards,usePokeProgression} from "@/poke/store";
import {PokemonSprite} from "./pokemon-sprite";
export function PokeCards(){
 const{locale}=useT();const credits=usePokeProgression((state)=>state.researchCredits);const cards=usePokeCards();const[packGeneration,setPackGeneration]=useState(1);const[filterGeneration,setFilterGeneration]=useState(0);const[type,setType]=useState("all");const[rarity,setRarity]=useState("all");const[foil,setFoil]=useState("all");
 const collection=useMemo(()=>Object.values(cards.collection).filter(({card})=>(filterGeneration===0||card.generation===filterGeneration)&&(type==="all"||species(card.speciesId).types.includes(type))&&(rarity==="all"||card.rarity===rarity)&&(foil==="all"||(foil==="yes")===card.foil)),[cards.collection,filterGeneration,foil,rarity,type]);
 return <div className="poke-cards"><header className="poke-cards-hero"><div><p className="poke-kicker">{locale==="de"?"DIGITALE FELD-SAMMELOBJEKTE":"DIGITAL FIELD COLLECTIBLES"}</p><h1>{locale==="de"?"Kartenarchiv":"Card archive"}</h1><p>{locale==="de"?"Öffne Forschungssets, wähle exakt zwei Fundstücke und baue einen zweisprachigen Spezies-Binder.":"Open research sets, keep exactly two findings and build a bilingual specimen binder."}</p></div><div className="poke-currency"><Coins/><b>{credits}</b><span>{locale==="de"?"Forschungspunkte":"Research Credits"}</span><small>{cards.dust} {locale==="de"?"Forschungsstaub":"Research Dust"}</small></div></header><aside className="poke-card-disclaimer">{locale==="de"?"Nur digitale Sammelobjekte dieses Fanprojekts · kein Geldwert, kein Handel, keine Käufe mit Echtgeld. Die Seltenheitsstufen sind rein kosmetisch und keine kanonischen Pokémon-Seltenheiten.":"Digital fan-project collectibles only · no monetary value, trading or real-money purchases. Rarity tiers are cosmetic and do not represent canonical Pokémon rarity."}</aside>
 <section className="poke-booster-terminal"><header><div><p className="poke-kicker">{locale==="de"?"FORSCHUNGSSET-TERMINAL":"RESEARCH SET TERMINAL"}</p><h2>{locale==="de"?"Fünf aufdecken. Zwei archivieren.":"Reveal five. Archive two."}</h2></div><span>{locale==="de"?"Veröffentlichte Chancen":"Published odds"}: {Object.entries(CARD_ODDS).map(([key,value])=>`${rarityLabel(key as CardRarity,locale)} ${value}%`).join(" · ")} · {locale==="de"?"Foil":"foil"} 10%</span></header><div className="poke-pack-generations">{Array.from({length:9},(_,index)=>index+1).map((gen)=>{const unlocked=cards.unlockedGenerations.includes(gen);return <div key={gen} className={packGeneration===gen?"is-active":""}>{unlocked?<button type="button" aria-pressed={packGeneration===gen} onClick={()=>setPackGeneration(gen)}><b>GEN {gen}</b><small>{SPECIES.filter((entry)=>entry.generation===gen).length} {locale==="de"?"Karten":"cards"}</small></button>:<><span aria-hidden><LockKeyhole/></span><small>{GEN_UNLOCK_COST} {locale==="de"?"Punkte":"credits"}</small><button type="button" disabled={credits<GEN_UNLOCK_COST} onClick={()=>{if(cards.unlock(gen))setPackGeneration(gen)}}>{locale==="de"?"Freischalten":"Unlock"}</button></>}</div>})}</div>
 {!cards.pending?<div className="poke-pack-vault"><div><Layers3/><i/><span>GEN {packGeneration} {locale==="de"?"FORSCHUNGSSET":"RESEARCH SET"}</span></div><button className="poke-primary" disabled={credits<BOOSTER_COST||!cards.unlockedGenerations.includes(packGeneration)} onClick={()=>cards.open(packGeneration)}><Sparkles/>{locale==="de"?`Set öffnen · ${BOOSTER_COST} Punkte`:`Open set · ${BOOSTER_COST} credits`}</button><p>{locale==="de"?"Forschungspunkte werden ausschließlich erspielt; Trainer-XP wird nie ausgegeben.":"Research Credits are earned only through play; Trainer XP is never spent."}</p></div>:<PackSelection cards={cards.pending} selected={cards.selected} locale={locale} toggle={cards.toggle} confirm={cards.confirm}/>}
 </section>
 <section className="poke-binder"><header><div><p className="poke-kicker">{locale==="de"?"SPEZIES-BINDER":"SPECIMEN BINDER"}</p><h2>{locale==="de"?"Deine Sammlung":"Your collection"}</h2></div><div><b>{Object.keys(cards.collection).length}</b><span>{locale==="de"?"VARIANTEN":"VARIANTS"} · {new Set(Object.values(cards.collection).map((item)=>item.card.speciesId)).size} {locale==="de"?"SPEZIES":"SPECIES"}</span></div></header><div className="poke-card-filters"><Filter/><select aria-label={locale==="de"?"Generation filtern":"Filter generation"} value={filterGeneration} onChange={(event)=>setFilterGeneration(Number(event.target.value))}><option value={0}>{locale==="de"?"Alle Generationen":"All generations"}</option>{Array.from({length:9},(_,index)=><option value={index+1} key={index}>Gen {index+1}</option>)}</select><select aria-label={locale==="de"?"Typ filtern":"Filter type"} value={type} onChange={(event)=>setType(event.target.value)}><option value="all">{locale==="de"?"Alle Typen":"All types"}</option>{STANDARD_TYPES.map((item)=><option key={item} value={item}>{localizedType(item,locale)}</option>)}</select><select aria-label={locale==="de"?"Kosmetische Stufe filtern":"Filter cosmetic tier"} value={rarity} onChange={(event)=>setRarity(event.target.value)}><option value="all">{locale==="de"?"Alle Stufen":"All tiers"}</option>{Object.keys(CARD_ODDS).map((item)=><option value={item} key={item}>{rarityLabel(item as CardRarity,locale)}</option>)}</select><select aria-label={locale==="de"?"Foil filtern":"Filter foil"} value={foil} onChange={(event)=>setFoil(event.target.value)}><option value="all">{locale==="de"?"Standard + Foil":"Standard + foil"}</option><option value="yes">{locale==="de"?"Nur Foil":"Foil only"}</option><option value="no">{locale==="de"?"Nur Standard":"Standard only"}</option></select></div><div className="poke-card-grid">{collection.length?collection.map(({card})=><Card card={card} locale={locale} key={`${card.speciesId}-${card.foil}`}/>):<div className="poke-card-empty"><Archive/><b>{locale==="de"?"Der Binder wartet auf deine ersten zwei Karten.":"The binder is waiting for your first two cards."}</b></div>}</div></section></div>;
}
function PackSelection({cards,selected,locale,toggle,confirm}:{cards:PokeCard[];selected:string[];locale:"en"|"de";toggle:(id:string)=>void;confirm:()=>boolean}){
 return <div className="poke-pack-open"><header><span>{selected.length} / 2 {locale==="de"?"gewählt":"selected"}</span><p>{locale==="de"?"Alle fünf sind sichtbar. Wähle exakt zwei für den Binder; drei werden nach Bestätigung freigegeben.":"All five are visible. Choose exactly two for the binder; three are released after confirmation."}</p></header><div>{cards.map((card,index)=><button aria-pressed={selected.includes(card.id)} aria-label={`${card.speciesId} · ${selected.includes(card.id)?(locale==="de"?"gewählt":"selected"):(locale==="de"?"auswählen":"select")}`} key={card.id} className={selected.includes(card.id)?"is-kept":""} onClick={()=>toggle(card.id)} style={{"--reveal-delay":`${index*90}ms`} as React.CSSProperties}><Card card={card} locale={locale}/>{selected.includes(card.id)&&<span><Check/> {locale==="de"?"BEHALTEN":"KEEP"} {selected.indexOf(card.id)+1}</span>}</button>)}</div><button className="poke-primary" disabled={selected.length!==2} onClick={confirm}>{locale==="de"?"Zwei Karten archivieren":"Archive two cards"} <Archive/></button></div>;
}
function Card({card,locale}:{card:PokeCard;locale:"en"|"de"}){
 const entry=species(card.speciesId);const total=Object.values(entry.stats).reduce((sum,value)=>sum+value,0);const signature=locale==="de"?`BASIS ${total} · INIT ${entry.stats.speed}`:`BST ${total} · SPD ${entry.stats.speed}`;return <article className={`poke-card rarity-${card.rarity} ${card.foil?"is-foil":""}`}><header><span>#{String(entry.id).padStart(4,"0")}</span><b>{rarityLabel(card.rarity,locale).toUpperCase()}</b></header><div className="poke-card-art"><PokemonSprite entry={entry} size={145}/><i/></div><h3>{entry.name[locale]}</h3><div className="poke-card-types">{entry.types.map((item)=><span key={item} style={{background:TYPE_COLORS[item]}}>{localizedType(item,locale)}</span>)}</div><footer><span>GEN {entry.generation}</span><small>{signature}</small>{card.foil&&<b>FOIL</b>}</footer></article>;
}
function rarityLabel(rarity:CardRarity,locale:"en"|"de"){if(locale==="en")return rarity;return({common:"häufig",uncommon:"ungewöhnlich",rare:"selten",ultra:"ultra",mythic:"mythisch"} as const)[rarity]}
