"use client";
import {useMemo,useState} from "react";
import {Heart,LockKeyhole,Search,X} from "lucide-react";
import {useT} from "@/i18n/I18nProvider";
import {SPECIES,species} from "@/poke/data";
import {STANDARD_TYPES,TYPE_COLORS} from "@/poke/type-chart";
import {pokeDexStage} from "@/poke/progression";
import {usePokeDex} from "@/poke/store";
import {PokemonSprite} from "./pokemon-sprite";
import {PokeDisclaimer} from "./disclaimer";
export function PokeDex(){
 const {locale}=useT();const records=usePokeDex((state)=>state.records);const toggleFavorite=usePokeDex((state)=>state.toggleFavorite);const [query,setQuery]=useState("");const [generation,setGeneration]=useState(1);const [type,setType]=useState("all");const [selected,setSelected]=useState<number|null>(null);const [page,setPage]=useState(1);
 const filtered=useMemo(()=>SPECIES.filter((entry)=>entry.generation<=generation&&(type==="all"||entry.types.includes(type))&&entry.name[locale].toLowerCase().includes(query.toLowerCase())),[generation,locale,query,type]);const shown=filtered.slice(0,page*72);const detail=selected?species(selected):null;const detailRecord=selected?records[selected]:undefined;const stage=pokeDexStage(detailRecord?.correct,detailRecord?.games.length);
 return <div className="poke-dex"><header className="poke-dex-hero"><div><p className="poke-kicker">NATIONAL SPECIMEN ARCHIVE</p><h1>PokéDex</h1><p>{locale==="de"?"1025 Standard-Spezies · neun Generationen · eigener Forschungsfortschritt":"1,025 default species · nine generations · your own research progress"}</p></div><div className="poke-dex-count"><b>{Object.keys(records).length}</b><span>/ 1025 SIGNALS</span></div></header><PokeDisclaimer/><div className="poke-dex-controls"><label><Search/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={locale==="de"?"Name suchen":"Search canonical name"}/></label><select value={generation} onChange={(event)=>{setGeneration(Number(event.target.value));setPage(1)}} aria-label="Generation cap">{Array.from({length:9},(_,index)=>index+1).map((cap)=><option value={cap} key={cap}>{cap===1?"Gen 1 only":cap===9?"Through Gen 9 · all":`Through Gen ${cap}`}</option>)}</select><select value={type} onChange={(event)=>setType(event.target.value)}><option value="all">{locale==="de"?"Alle Typen":"All types"}</option>{STANDARD_TYPES.map((item)=><option key={item}>{item}</option>)}</select></div><div className="poke-dex-ledger">{shown.map((entry)=>{const record=records[entry.id];const entryStage=pokeDexStage(record?.correct,record?.games.length);const sealed=entryStage==="sealed";return <button key={entry.id} onClick={()=>!sealed&&setSelected(entry.id)} className={`stage-${entryStage}`}><span>#{String(entry.id).padStart(4,"0")}</span>{sealed?<LockKeyhole/>:<PokemonSprite entry={entry} size={86}/>}<b>{sealed?"••••••":entry.name[locale]}</b><small>{entryStage}</small>{record?.favorite&&<Heart className="is-favorite"/>}</button>})}</div>{shown.length<filtered.length&&<button className="poke-secondary mx-auto mt-8" onClick={()=>setPage((value)=>value+1)}>{locale==="de"?"Weitere Akten laden":"Load more files"}</button>}
 {detail&&<div className="poke-dossier-modal" role="dialog" aria-modal="true" aria-label={detail.name[locale]}><button className="poke-modal-close" onClick={()=>setSelected(null)}><X/></button><div className="poke-dossier-art"><span>#{String(detail.id).padStart(4,"0")}</span><PokemonSprite entry={detail} size={260}/><button onClick={()=>toggleFavorite(detail.id)}><Heart className={detailRecord?.favorite?"is-favorite":""}/>{locale==="de"?"Favorit":"Favorite"}</button></div><section><p className="poke-kicker">{stage.toUpperCase()} DOSSIER</p><h2>{detail.name[locale]}</h2><div className="poke-type-tags">{detail.types.map((item)=><span key={item} style={{background:TYPE_COLORS[item]}}>{item}</span>)}</div>{stage==="mastered"?<><div className="poke-measurements"><span>{detail.heightM} m<small>HEIGHT</small></span><span>{detail.weightKg} kg<small>WEIGHT</small></span><span>{detail.habitat}<small>HABITAT</small></span></div><div className="poke-stat-chart">{Object.entries(detail.stats).map(([key,value])=><div key={key}><span>{key}</span><i><b style={{width:`${Math.min(100,value/180*100)}%`}}/></i><strong>{value}</strong></div>)}</div></>:<div className="poke-dex-locked-note">{locale==="de"?"Meistere diese Spezies durch mehrere Spiele, um Messwerte, Habitat und Statusdiagramm freizuschalten.":"Master this species across several games to unlock measurements, habitat and the stat chart."}</div>}</section></div>}</div>;
}

