"use client";
import Link from "next/link";
import {Award,BarChart3,Flame,RotateCcw,Trophy} from "lucide-react";
import {useT} from "@/i18n/I18nProvider";
import {POKE_BADGES,POKE_COMPETENCIES,trainerLevel} from "@/poke/progression";
import {POKE_GAMES,getPokeGame} from "@/poke/registry";
import {usePokeProgression,usePokeScores} from "@/poke/store";
import {pl} from "@/poke/types";
export function PokeLeaderboard(){const{locale}=useT();const runs=usePokeScores((state)=>state.runs);const best=[...runs].sort((a,b)=>b.score-a.score).slice(0,20);return <StatsShell title={locale==="de"?"Lokales Rangsignal":"Local rank signal"} icon={<Trophy/>}><div className="poke-rank-list">{best.length?best.map((run,index)=><div key={run.id}><b>{String(index+1).padStart(2,"0")}</b><span>{pl(getPokeGame(run.gameId).title,locale)}<small>{new Date(run.createdAt).toLocaleDateString(locale)}</small></span><strong>{run.score}</strong></div>):<Empty locale={locale}/>}</div></StatsShell>}
export function PokeBadges(){const{locale}=useT();const progress=usePokeProgression();return <StatsShell title={locale==="de"?"Feldabzeichen":"Field badges"} icon={<Award/>}><div className="poke-badge-cabinet">{POKE_BADGES.map((badge)=>{const value=badge.metric==="runs"?progress.totalRuns:badge.metric==="correct"?progress.correct:progress.xp;const earned=value>=badge.goal;return <article className={earned?"is-earned":""} key={badge.id}><div><Award/></div><p>{badge.name[locale]}</p><span>{Math.min(value,badge.goal)} / {badge.goal}</span></article>})}</div></StatsShell>}
export function PokeProfile(){const{locale}=useT();const progress=usePokeProgression();const weakest=[...POKE_COMPETENCIES].sort((a,b)=>progress.competencyXp[a]-progress.competencyXp[b])[0];const game=POKE_GAMES.find((item)=>item.competency===weakest)!;return <StatsShell title={locale==="de"?"Trainer-Feldakte":"Trainer field file"} icon={<BarChart3/>}><div className="poke-profile-sheet"><div className="poke-level-stamp"><span>TRAINER LEVEL</span><b>{String(trainerLevel(progress.xp)).padStart(2,"0")}</b><small>{progress.xp} XP</small></div><div className="poke-competency-chart">{POKE_COMPETENCIES.map((item)=><div key={item}><span>{item}</span><i><b style={{width:`${Math.min(100,progress.competencyXp[item]/Math.max(1,...Object.values(progress.competencyXp))*100)}%`}}/></i><strong>{progress.competencyXp[item]}</strong></div>)}</div><aside><Flame/><div><b>{progress.activeDays.length}</b><span>{locale==="de"?"aktive Forschungstage":"active research days"}</span></div></aside><Link className="poke-primary" href={`/poke-nerds/play/${game.id}`}>{locale==="de"?"Schwächste Kompetenz trainieren":"Train weakest competency"}: {pl(game.title,locale)}</Link></div></StatsShell>}
function StatsShell({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <div className="poke-stats-page"><header><span>{icon}</span><p className="poke-kicker">PERSONAL RESEARCH RECORD</p><h1>{title}</h1></header>{children}</div>}
function Empty({locale}:{locale:string}){return <div className="poke-empty"><RotateCcw/><b>{locale==="de"?"Noch kein Feldbericht":"No field report yet"}</b><Link href="/poke-nerds">{locale==="de"?"Mission starten":"Start a mission"} →</Link></div>}

