"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Clock3, RotateCcw, Sparkles, X, LocateFixed } from "lucide-react";
import { useT } from "@/i18n/I18nProvider";
import { getWineGame } from "@/wine/registry";
import type { WineGameId, WineRun } from "@/wine/types";
import { localize } from "@/wine/types";
import { questionsFor, scoreMapClick, shuffle, type WineQuestion } from "@/wine/engine";
import { APPELLATIONS, CELLAR_BOTTLES, CELLAR_BRIEFS, DILEMMAS, GRAPES, PAIRINGS, REGIONS } from "@/wine/content";
import { useWineDaily, useWineDex, useWineProgression, useWineScores } from "@/wine/store";
import { PinMap } from "@/components/map/pin-map";
import { Compass } from "@/components/map/compass";

type Difficulty="easy"|"medium"|"hard";
const ROUND_COUNTS:Record<Difficulty,number>={easy:5,medium:8,hard:12};

export function WineGameRunner({gameId}:{gameId:WineGameId}) {
 const {locale}=useT(); const game=getWineGame(gameId);
 const [difficulty,setDifficulty]=useState<Difficulty>("medium");
 const [practice,setPractice]=useState(false); const [phase,setPhase]=useState<"setup"|"playing">("setup"); const [sessionSeed,setSessionSeed]=useState(0);
 const startSession=()=>{setSessionSeed(Date.now());setPhase("playing")};
 const replay=()=>setSessionSeed(Date.now());
 if(phase==="setup")return <div className="mx-auto max-w-3xl px-4 py-10 md:py-16">
  <Link href="/wine-nerds" className="wine-back"><ArrowLeft className="h-4 w-4"/>{locale==="de"?"Zum Weinkeller":"To the wine cellar"}</Link>
  <p className="wine-kicker mt-10">{localize(game.eyebrow,locale)}</p>
  <h1 className="mt-3 text-4xl font-black tracking-[-.05em] text-[var(--wine-cream)] md:text-6xl">{localize(game.title,locale)}</h1>
  <p className="mt-5 max-w-2xl text-base leading-7 text-[var(--wine-muted)]">{localize(game.description,locale)}</p>
  <div className="mt-10 border-y border-[var(--wine-line)] py-7">
   <p className="wine-kicker">{locale==="de"?"Schwierigkeit":"Difficulty"}</p>
   <div className="mt-3 grid grid-cols-3 gap-2">{(["easy","medium","hard"] as Difficulty[]).map(d=><button key={d} onClick={()=>setDifficulty(d)} className={`wine-option ${difficulty===d?"is-selected":""}`}>{d==="easy"?(locale==="de"?"Einstieg":"Cellar door"):d==="medium"?(locale==="de"?"Service":"Service"):(locale==="de"?"Prüfung":"Exam")}</button>)}</div>
   <label className="mt-5 flex min-h-11 cursor-pointer items-center gap-3 text-sm text-[var(--wine-muted)]"><input type="checkbox" checked={practice} onChange={e=>setPractice(e.target.checked)} className="h-5 w-5 accent-[var(--wine-copper)]"/><span><b className="text-[var(--wine-cream)]">{locale==="de"?"Übungsmodus":"Practice mode"}</b> · {locale==="de"?"speichert keine XP, Stempel oder Scores":"saves no XP, stamps or scores"}</span></label>
  </div>
  {gameId==="sommelier-exam"&&<p className="mt-5 text-xs leading-5 text-[var(--wine-muted)]">{locale==="de"?"Inoffizielle Übungsprüfung. Nicht mit WSET oder einer anderen Zertifizierungsstelle verbunden. Kein Alkoholkonsum erforderlich.":"Unofficial practice exam. Not affiliated with WSET or any certification body. No alcohol consumption is required."}</p>}
  <button type="button" data-testid="wine-start-session" className="wine-button mt-8 w-full sm:w-auto" onClick={startSession}>{locale==="de"?"Session starten":"Start session"}<ArrowRight className="h-4 w-4"/></button>
 </div>;
 const props={gameId,difficulty,practice,seed:sessionSeed,onReplay:replay,onExit:()=>setPhase("setup")};
 if(gameId==="wine-map")return <MapGame key={sessionSeed} {...props}/>;
 if(gameId==="aroma-atelier")return <AromaAtelierGame key={sessionSeed} {...props}/>;
 if(gameId==="cellar-builder")return <CellarBuilder key={sessionSeed} {...props}/>;
 if(gameId==="label-decoder")return <LabelDecoderGame key={sessionSeed} {...props}/>;
 if(gameId==="regional-connections")return <ConnectionsGame key={sessionSeed} {...props}/>;
 if(gameId==="appellation-ladder")return <LadderGame key={sessionSeed} {...props}/>;
 if(gameId==="winemakers-dilemma")return <DilemmaGame key={sessionSeed} {...props}/>;
 if(gameId==="same-grape")return <SameGrapeGame key={sessionSeed} {...props}/>;
 if(gameId==="cellar-mystery")return <MysteryGame key={sessionSeed} {...props}/>;
 if(gameId==="tasting-note-builder")return <NoteBuilder key={sessionSeed} {...props}/>;
 return <ChoiceGame key={sessionSeed} {...props}/>;
}

interface PlayProps {gameId:WineGameId;difficulty:Difficulty;practice:boolean;seed:number;onReplay:()=>void;onExit:()=>void}
function useFinish({gameId,difficulty,practice}:PlayProps) {
 const progress=useWineProgression(s=>s.record), add=useWineScores(s=>s.add), daily=useWineDaily(s=>s.complete);
 return (score:number,correct:number,total:number,streak:number,start:number)=>{
  const run:WineRun={id:`wine-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,gameId,difficulty,practice,score,correct,total,bestStreak:streak,durationMs:Date.now()-start,createdAt:Date.now()};
  progress(run);add(run);if(!practice){daily(new Date().toISOString().slice(0,10));void fetch("/api/wine-scores",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(run)}).catch(()=>undefined)}return run;
 };
}
function PlayHeader({gameId,round,total,score,practice,onExit}:{gameId:WineGameId;round:number;total:number;score:number;practice:boolean;onExit:()=>void}){
 const {locale}=useT();return <header className="border-b border-[var(--wine-line)] bg-black/15"><div className="mx-auto flex min-h-16 max-w-4xl items-center gap-4 px-4"><button onClick={onExit} className="wine-icon" aria-label="Exit"><X className="h-5 w-5"/></button><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-[var(--wine-cream)]">{localize(getWineGame(gameId).title,locale)}</p><div className="mt-1 h-1 bg-white/10"><div className="h-full bg-[var(--wine-copper)]" style={{width:`${Math.min(100,round/Math.max(1,total)*100)}%`}}/></div></div><span className="font-mono text-sm font-bold">{score}</span>{practice&&<span className="hidden text-[10px] uppercase tracking-wider text-[var(--wine-vine)] sm:block">practice</span>}</div></header>
}
function structureLevel(text:string,trait:"body"|"acidity"|"tannin"){
 const segment=text.toLowerCase().split(",").find(part=>part.includes(trait))??text.toLowerCase();
 if(segment.includes("very high"))return 5;if(segment.includes("high"))return 4;if(segment.includes("medium-high"))return 4;if(segment.includes("medium"))return 3;if(segment.includes("low-medium"))return 2;if(segment.includes("low"))return 1;return 2;
}
function TerroirDossier({grape,locale}:{grape:typeof GRAPES[number];locale:"en"|"de"}){
 return <section className="wine-terroir-dossier" aria-label={locale==="de"?"Visuelles Lagen-Dossier":"Visual site dossier"}>
  <div className="wine-vineyard-scene"><span className="wine-site-sun"/><span className="wine-site-slope"/><span className="wine-vine-row row-a"/><span className="wine-vine-row row-b"/><span className="wine-vine-row row-c"/><span className="wine-soil-layer layer-a"/><span className="wine-soil-layer layer-b"/><span className="wine-scene-label label-climate">{localize(grape.climate,locale)}</span><span className="wine-scene-label label-soil">{locale==="de"?"Boden: herkunftsspezifisch":"Soil: origin-specific"}</span></div>
  <div className="wine-evidence-ledger"><p className="wine-kicker">{locale==="de"?"Beobachtbare Indizien":"Observed evidence"}</p><strong>{localize(grape.structure,locale)}</strong><div>{grape.aromas.map(a=><span key={a}>{a}</span>)}</div><small>{locale==="de"?"Exposition und Boden sind keine festen Rebsortenmerkmale; sie bleiben Teil der Lagenanalyse.":"Exposure and soil are not fixed grape traits; they remain part of site analysis."}</small></div>
 </section>
}
function GrapeDnaBoard({grape,locale}:{grape:typeof GRAPES[number];locale:"en"|"de"}){
 const metrics=[["acidity",structureLevel(grape.structure.en,"acidity")],["tannin",structureLevel(grape.structure.en,"tannin")],["body",structureLevel(grape.structure.en,"body")]] as const;
 return <section className="wine-dna-board" aria-label={locale==="de"?"Anonymes Rebsortenprofil":"Anonymous grape profile"}>
  <div className="wine-dna-mark"><i/><i/><i/><i/><i/><i/><span>?</span></div><div className="wine-dna-data"><p className="wine-kicker">{locale==="de"?"Anonyme Probe":"Anonymous sample"}</p><div className="wine-climate-band"><span>{locale==="de"?"kühl":"cool"}</span><b style={{left:grape.climate.en.includes("warm")?"72%":grape.climate.en.includes("moderate")?"50%":"24%"}}/><span>{locale==="de"?"warm":"warm"}</span></div>{metrics.map(([label,value])=><ProfileMeter key={label} label={label} value={value}/>)}</div><div className="wine-dna-aromas">{grape.aromas.map((a,i)=><span key={a}><i>{String(i+1).padStart(2,"0")}</i>{a}</span>)}</div>
 </section>
}
function PairingDuelScene({pairing,locale,selected}:{pairing:typeof PAIRINGS[number];locale:"en"|"de";selected:string|null}){
 return <div className={`wine-pairing-arena ${selected?`leans-${selected}`:""}`}><div className="wine-duel-bottle bottle-left"><i/><span>A</span></div><div className="wine-pairing-plate"><i/><span>{localize(pairing.dish,locale)}</span></div><div className="wine-duel-bottle bottle-right"><i/><span>B</span></div><div className="wine-duel-line"/></div>
}
function ChoiceGame(props:PlayProps){
 const {locale}=useT();const isExam=props.gameId==="sommelier-exam";const count=isExam?12:ROUND_COUNTS[props.difficulty];
 const questions=useMemo(()=> {
  if (!isExam) return questionsFor(props.gameId,props.seed).slice(0,count);
  return shuffle([
   ...questionsFor("terroir-detective",props.seed),
   ...questionsFor("grape-dna",props.seed+1),
   ...questionsFor("aroma-atelier",props.seed+2),
   ...questionsFor("pairing-duel",props.seed+3),
   ...questionsFor("label-decoder",props.seed+4),
   ...questionsFor("wine-map",props.seed+5),
  ],props.seed+6).slice(0,count);
 },[props.gameId,props.seed,count,isExam]);
 const [index,setIndex]=useState(0),[selected,setSelected]=useState<string|null>(null),[score,setScore]=useState(0),[correct,setCorrect]=useState(0),[streak,setStreak]=useState(0),[best,setBest]=useState(0),[done,setDone]=useState(false);const [start]=useState(Date.now());
 const encounter=useWineDex(s=>s.encounter), finish=useFinish(props); const q=questions[index];const evidenceGrape=(props.gameId==="terroir-detective"||props.gameId==="grape-dna")?GRAPES.find(g=>g.id===q.answer):null;const pairing=props.gameId==="pairing-duel"?PAIRINGS.find(p=>p.id===q.entity?.id):null;
 const answer=(id:string)=>{if(selected)return;setSelected(id);const ok=id===q.answer;const next=ok?streak+1:0;if(ok){setCorrect(x=>x+1);setScore(x=>x+100+Math.min(100,next*10));setBest(Math.max(best,next));}setStreak(next);if(q.entity&&!props.practice)encounter(q.entity.id,q.entity.type,props.gameId,ok)};
 const next=()=>{if(index+1>=questions.length){finish(score+(selected===q.answer?0:0),correct,questions.length,best,start);setDone(true)}else{setIndex(x=>x+1);setSelected(null)}};
 if(done)return <Result {...props} score={score} correct={correct} total={questions.length} onReplay={props.onReplay}/>;
 return <><PlayHeader gameId={props.gameId} round={index+1} total={questions.length} score={score} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-3xl px-4 py-8">
  {isExam&&<div className="mb-5 flex items-center gap-2 text-xs text-[var(--wine-muted)]"><Clock3 className="h-4 w-4"/>{locale==="de"?"Inoffizielle gemischte Übung · 12 Aufgaben":"Unofficial mixed practice · 12 prompts"}</div>}
  <p className="wine-kicker">{locale==="de"?`Aufgabe ${index+1} von ${questions.length}`:`Prompt ${index+1} of ${questions.length}`}</p>
  <h1 className="mt-4 text-2xl font-black leading-tight text-[var(--wine-cream)] md:text-4xl">{localize(q.prompt,locale)}</h1>
  {props.gameId==="terroir-detective"&&evidenceGrape&&<TerroirDossier grape={evidenceGrape} locale={locale}/>}
  {props.gameId==="grape-dna"&&evidenceGrape&&<GrapeDnaBoard grape={evidenceGrape} locale={locale}/>}
  {pairing&&<PairingDuelScene pairing={pairing} locale={locale} selected={selected}/>}
  <div className={`mt-8 grid gap-3 sm:grid-cols-2 ${pairing?"wine-duel-choices":""}`}>{q.choices.map((c,choiceIndex)=>{const reveal=selected!==null,ok=c.id===q.answer,chosen=c.id===selected;return <button key={c.id} disabled={reveal} onClick={()=>answer(c.id)} className={`${pairing?"wine-duel-challenger":"wine-answer"} ${pairing?`challenger-${choiceIndex}`:""} ${reveal&&ok?"is-correct":""} ${reveal&&chosen&&!ok?"is-wrong":""}`}><span>{pairing&&<b>{choiceIndex?"B":"A"}</b>}{localize(c.label,locale)}</span>{reveal&&ok&&<Check className="h-5 w-5"/>}{reveal&&chosen&&!ok&&<X className="h-5 w-5"/>}</button>})}</div>
  {selected&&<div className="wine-reveal"><p className="wine-kicker">{selected===q.answer?(locale==="de"?"Stimmige Begründung":"Defensible reasoning"):(locale==="de"?"Lernmoment":"Study the miss")}</p><p className="mt-2 leading-6">{localize(q.explanation,locale)}</p><button onClick={next} className="wine-button mt-5">{index+1===questions.length?(locale==="de"?"Auswertung":"Results"):(locale==="de"?"Nächste Aufgabe":"Next prompt")}<ArrowRight className="h-4 w-4"/></button></div>}
 </div></>;
}
function aromaFamily(aroma:string){
 const value=aroma.toLowerCase();
 if(/rose|violet|flower/.test(value))return "floral";
 if(/herb|mint|leaf|pepper/.test(value))return "herbal";
 if(/cedar|vanilla|toast|smoke|butter/.test(value))return "winemaking";
 if(/leather|earth|floor|petrol|honey/.test(value))return "maturation";
 if(/clove|liquorice|ginger/.test(value))return "spice";
 return "fruit";
}
function AromaAtelierGame(props:PlayProps){
 const {locale}=useT();const count=ROUND_COUNTS[props.difficulty];
 const rounds=useMemo(()=>shuffle(GRAPES.filter(g=>g.aromas.length>=3),props.seed).slice(0,count),[props.seed,count]);
 const [index,setIndex]=useState(0),[selected,setSelected]=useState<string[]>([]),[revealed,setRevealed]=useState(false),[score,setScore]=useState(0),[correct,setCorrect]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());
 const finish=useFinish(props),encounter=useWineDex(s=>s.encounter),target=rounds[index];
 const tokens=useMemo(()=>shuffle([...target.aromas.slice(0,3),...GRAPES.filter(g=>g.id!==target.id).flatMap(g=>g.aromas).filter(a=>!target.aromas.includes(a)).slice(0,5)],props.seed+index),[target,props.seed,index]);
 const hits=selected.filter(a=>target.aromas.includes(a)).length;
 const submit=()=>{if(selected.length!==3)return;setRevealed(true);if(hits===3){setCorrect(x=>x+1);setScore(x=>x+300)}if(!props.practice)encounter(target.id,"grape",props.gameId,hits===3)};
 const next=()=>{const nextScore=score,nextCorrect=correct;if(index+1===rounds.length){finish(nextScore,nextCorrect,rounds.length,nextCorrect,start);setDone(true)}else{setIndex(x=>x+1);setSelected([]);setRevealed(false)}};
 if(done)return <Result {...props} score={score} correct={correct} total={rounds.length} onReplay={props.onReplay}/>;
 return <><PlayHeader gameId={props.gameId} round={index+1} total={rounds.length} score={score} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-4xl px-4 py-7">
  <div className="text-center"><p className="wine-kicker">{locale==="de"?"Wähle drei häufig verbundene Aromen":"Choose three commonly associated aromas"}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{target.name}</h1><p className="mt-2 text-sm text-[var(--wine-muted)]">{localize(target.climate,locale)} · {localize(target.structure,locale)}</p></div>
  <div className="wine-aroma-stage mt-6">
   <div className="wine-aroma-orbit" aria-live="polite">{selected.map((a,i)=><span key={a} className={`wine-aroma-attached family-${aromaFamily(a)}`} style={{"--token-index":i} as React.CSSProperties}>{a}</span>)}</div>
   <div className="wine-glass" aria-hidden><div className="wine-glass-bowl"><div className="wine-glass-fill"/></div><div className="wine-glass-stem"/><div className="wine-glass-foot"/></div>
   <span className="wine-grape-card">{target.name}<small>{selected.length}/3</small></span>
  </div>
  <div className="mt-7 flex flex-wrap justify-center gap-2">{tokens.map(a=>{const chosen=selected.includes(a),isCorrect=target.aromas.includes(a);return <button key={a} disabled={revealed} onClick={()=>setSelected(s=>chosen?s.filter(x=>x!==a):s.length<3?[...s,a]:s)} className={`wine-aroma-token family-${aromaFamily(a)} ${chosen?"is-selected":""} ${revealed&&chosen&&isCorrect?"is-correct":""} ${revealed&&chosen&&!isCorrect?"is-wrong":""}`}>{a}</button>})}</div>
  {!revealed?<button disabled={selected.length!==3} onClick={submit} className="wine-button mx-auto mt-7 flex">{locale==="de"?"Aromen prüfen":"Check aromas"}</button>:<div className="wine-reveal"><p className="font-bold">{hits===3?(locale==="de"?"Das Profil sitzt.":"The profile holds together."):(locale==="de"?`${hits}/3 passen typischerweise.`:`${hits}/3 are commonly associated.`)}</p><p className="mt-2 text-sm text-[var(--wine-muted)]">{locale==="de"?"Assoziationen sind kontextabhängig – Herkunft, Reife und Ausbau verändern das Bild.":"Associations remain contextual: origin, ripeness and winemaking all shift the picture."}</p><button onClick={next} className="wine-button mt-4">{locale==="de"?"Weiter":"Continue"}<ArrowRight className="h-4 w-4"/></button></div>}
 </div></>;
}
function LabelDecoderGame(props:PlayProps){
 const {locale}=useT();const count=ROUND_COUNTS[props.difficulty];const rounds=useMemo(()=>shuffle(APPELLATIONS,props.seed).slice(0,count),[props.seed,count]);const [index,setIndex]=useState(0),[selected,setSelected]=useState<string|null>(null),[score,setScore]=useState(0),[correct,setCorrect]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props),encounter=useWineDex(s=>s.encounter),a=rounds[index],region=REGIONS.find(r=>r.id===a.regionId)!;
 const mode=index%3;const pool=mode===0?APPELLATIONS.map(x=>({id:x.id,label:localize(x.style,locale)})):mode===1?APPELLATIONS.map(x=>({id:x.id,label:localize(x.level,locale)})):REGIONS.map(x=>({id:x.id,label:localize(x.country,locale)}));const answer=mode===2?region.id:a.id;const choices=useMemo(()=>shuffle([{id:answer,label:mode===0?localize(a.style,locale):mode===1?localize(a.level,locale):localize(region.country,locale)},...pool.filter(x=>x.id!==answer).slice(0,3)],props.seed+index),[answer,a,region,pool,mode,locale,props.seed,index]);
 const choose=(id:string)=>{if(selected)return;setSelected(id);const ok=id===answer;if(ok){setCorrect(x=>x+1);setScore(x=>x+250)}if(!props.practice)encounter(a.id,"appellation",props.gameId,ok)};
 const next=()=>{if(index+1===rounds.length){finish(score,correct,rounds.length,correct,start);setDone(true)}else{setIndex(x=>x+1);setSelected(null)}};
 if(done)return <Result {...props} score={score} correct={correct} total={rounds.length} onReplay={props.onReplay}/>;
 const question=mode===0?(locale==="de"?"Welchen Stil deutet die Appellation an?":"What style does the appellation suggest?"):mode===1?(locale==="de"?"Welche Art Herkunftsbegriff ist markiert?":"What kind of origin term is highlighted?"):(locale==="de"?"Welches Herkunftsland gehört dazu?":"Which country of origin belongs here?");
 return <><PlayHeader gameId={props.gameId} round={index+1} total={rounds.length} score={score} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-4xl px-4 py-7">
  <p className="wine-kicker text-center">{locale==="de"?"Fiktives Etikett · keine Handelsmarke":"Synthetic label · no commercial trademark"}</p><h1 className="mt-2 text-center text-2xl font-black text-[var(--wine-cream)]">{question}</h1>
  <div className="wine-label-workbench mt-6"><div className="wine-bottle"><div className="wine-bottle-neck"/><div className="wine-bottle-body"><div className="wine-paper-label"><span className="wine-label-producer">NORTH LANTERN ESTATE</span><strong className={`wine-label-field ${mode===0?"is-hot":""}`}>{a.name}</strong><span className={`wine-label-field ${mode===1?"is-hot":""}`}>{localize(a.level,locale)}</span><span className={`wine-label-field ${mode===2?"is-hot":""}`}>{localize(region.country,locale)}</span><b>2022</b></div></div></div>
   {selected&&<div className="wine-label-callouts"><p><span>01</span>{a.name} → {localize(region.name,locale)}</p><p><span>02</span>{localize(a.level,locale)}</p><p><span>03</span>{localize(region.country,locale)}</p><p><span>04</span>{localize(a.style,locale)}</p></div>}
  </div>
  <div className="mt-6 grid gap-2 sm:grid-cols-2">{choices.map(c=><button key={c.id} disabled={!!selected} onClick={()=>choose(c.id)} className={`wine-answer ${selected&&c.id===answer?"is-correct":""} ${selected===c.id&&c.id!==answer?"is-wrong":""}`}>{c.label}</button>)}</div>
  {selected&&<div className="wine-reveal"><p>{locale==="de"?`${a.name} sitzt in ${localize(region.name,locale)} und steht hier für ${localize(a.style,locale)}.`:`${a.name} sits within ${localize(region.name,locale)} and here signals ${localize(a.style,locale)}.`}</p><button onClick={next} className="wine-button mt-4">{locale==="de"?"Nächstes Etikett":"Next label"}<ArrowRight className="h-4 w-4"/></button></div>}
 </div></>;
}
function MapGame(props:PlayProps){
 const {locale}=useT();const regions=useMemo(()=>shuffle(REGIONS,props.seed).slice(0,ROUND_COUNTS[props.difficulty]),[props.seed,props.difficulty]);const [i,setI]=useState(0),[pin,setPin]=useState<[number,number]|null>(null),[confirmed,setConfirmed]=useState(false),[resetSignal,setResetSignal]=useState(0),[score,setScore]=useState(0),[correct,setCorrect]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props),encounter=useWineDex(s=>s.encounter),target=regions[i];const result=confirmed&&pin?scoreMapClick(pin[1],pin[0],target):null;
 const next=()=>{if(result){setScore(x=>x+result.score);if(result.correct)setCorrect(x=>x+1);if(!props.practice)encounter(target.id,"region",props.gameId,result.correct)}if(i+1===regions.length){finish(score+(result?.score??0),correct+(result?.correct?1:0),regions.length,0,start);setDone(true)}else{setI(x=>x+1);setPin(null);setConfirmed(false);setResetSignal(x=>x+1)}};
 if(done)return <Result {...props} score={score} correct={correct} total={regions.length} onReplay={props.onReplay}/>;
 return <><PlayHeader gameId={props.gameId} round={i+1} total={regions.length} score={score} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="wine-kicker">{locale==="de"?"Atlas-Aufgabe":"Atlas assignment"}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{localize(target.name,locale)} · {localize(target.country,locale)}</h1></div><button type="button" onClick={()=>setResetSignal(x=>x+1)} className="wine-button wine-button-quiet"><LocateFixed className="h-4 w-4"/>{locale==="de"?"Weltansicht":"World view"}</button></div>
  <p className="mt-3 text-xs leading-5 text-[var(--wine-muted)]">{locale==="de"?"Ziehen oder mit zwei Fingern bewegen · Mausrad/Pinch und +/− zum Zoomen · kurz tippen, um den Pin zu setzen oder zu versetzen.":"Drag or use two fingers to move · wheel/pinch and +/− to zoom · briefly tap to place or reposition your pin."}</p>
  <div className="wine-real-map relative mt-4 h-[420px] overflow-hidden border border-[var(--wine-line)] sm:h-[520px]"><PinMap onPin={(lng,lat)=>{if(!confirmed)setPin([lng,lat])}} userPin={pin} target={confirmed?[target.lng,target.lat]:null} locked={confirmed} resetSignal={resetSignal} initialScale={1}/><Compass/></div>
  {!confirmed?<div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-[var(--wine-muted)]">{pin?(locale==="de"?"Pin gesetzt — du kannst ihn noch versetzen.":"Pin placed — you can still reposition it."):(locale==="de"?"Setze zuerst einen Pin auf die echte Weltkarte.":"Place a pin on the real world map first.")}</p><button type="button" disabled={!pin} onClick={()=>setConfirmed(true)} className="wine-button">{locale==="de"?"Pin bestätigen":"Lock in pin"}<Check className="h-4 w-4"/></button></div>:result&&<div className="wine-reveal"><div className="flex flex-wrap items-baseline gap-x-4 gap-y-1"><p className="text-2xl font-black">{Math.round(result.distance).toLocaleString(locale)} km</p><b className="font-mono text-[var(--wine-copper)]">+{result.score}</b></div><p className="mt-2 text-[var(--wine-muted)]">{localize(target.climate,locale)} · {target.grapes.map(id=>GRAPES.find(g=>g.id===id)?.name).join(", ")}</p><button className="wine-button mt-5" onClick={next}>{locale==="de"?"Weiter":"Continue"}<ArrowRight className="h-4 w-4"/></button></div>}
 </div></>;
}
function CellarBuilder(props:PlayProps){
 const {locale}=useT();const brief=CELLAR_BRIEFS[props.seed%CELLAR_BRIEFS.length];const [selected,setSelected]=useState<string[]>([]),[feedback,setFeedback]=useState<string|null>(null),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props);const cost=CELLAR_BOTTLES.filter(b=>selected.includes(b.id)).reduce((s,b)=>s+b.price,0);const covered=new Set(CELLAR_BOTTLES.filter(b=>selected.includes(b.id)).map(b=>b.category));const missing=brief.needs.filter(n=>!covered.has(n));const valid=cost<=brief.budget&&missing.length===0;
 const roles=[{id:"sparkling",label:locale==="de"?"Aperitif":"Aperitif",accept:["sparkling"]},{id:"crisp-white",label:locale==="de"?"Frischer Weißwein":"Crisp white",accept:["white"]},{id:"textural-white",label:locale==="de"?"Texturierter Weißwein":"Textural white",accept:["white"]},{id:"light-red",label:locale==="de"?"Leichter Rotwein":"Light red",accept:["red","rosé"]},{id:"structured-red",label:locale==="de"?"Strukturierter Rotwein":"Structured red",accept:["red"]},{id:"sweet",label:locale==="de"?"Süß / Fortified":"Sweet / fortified",accept:["sweet","fortified"]}];const rack=roles.map((role,i)=>({role,bottle:CELLAR_BOTTLES.filter(b=>selected.includes(b.id)&&role.accept.includes(b.category))[i===2||i===4?1:0]}));
 const submit=()=>{if(!selected.length)return;if(cost>brief.budget){setFeedback(locale==="de"?`Noch €${cost-brief.budget} über Budget. Entferne oder tausche eine Flasche.`:`€${cost-brief.budget} over budget. Remove or swap a bottle.`);return}if(missing.length){setFeedback(locale==="de"?`Noch offen: ${missing.join(", ")}.`:`Still missing: ${missing.join(", ")}.`);return}setFeedback(locale==="de"?"Starke Abdeckung: Budget und Pflichtrollen stimmen.":"Strong coverage: budget and required roles are balanced.");finish(1000,1,1,0,start);setDone(true)};
 if(done)return <Result {...props} score={valid?1000:400} correct={valid?1:0} total={1} onReplay={props.onReplay}/>;
 return <><PlayHeader gameId={props.gameId} round={1} total={1} score={Math.max(0,1000-cost*3)} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="wine-kicker">{localize(brief.title,locale)}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{locale==="de"?`Baue einen Keller unter €${brief.budget}`:`Build a cellar under €${brief.budget}`}</h1></div><div className="wine-budget"><span>€{cost}</span><small>/ €{brief.budget}</small><div><i style={{width:`${Math.min(100,cost/brief.budget*100)}%`}} className={cost>brief.budget?"is-over":""}/></div></div></div>
  <div className="mt-5 flex flex-wrap gap-2">{brief.needs.map(n=><span key={n} className={`wine-coverage ${covered.has(n)?"is-covered":""}`}><i/>{n}</span>)}</div>
  <div className="wine-cellar-rack mt-7">{rack.map(({role,bottle})=><div key={role.id} className={`wine-rack-slot ${bottle?"is-filled":""}`}><span className="wine-rack-role">{role.label}</span>{bottle?<button aria-label={`${bottle.name} entfernen`} onClick={()=>{setSelected(s=>s.filter(x=>x!==bottle.id));setFeedback(null)}} className="wine-rack-bottle"><i/><b>{bottle.name}</b><small>€{bottle.price}</small></button>:<span className="wine-rack-empty">+</span>}</div>)}</div>
  <p className="wine-kicker mt-8">{locale==="de"?"Flaschenbank · tippen zum Einlagern":"Bottle bank · tap to rack"}</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{CELLAR_BOTTLES.map(b=><button key={b.id} onClick={()=>{setSelected(s=>s.includes(b.id)?s.filter(x=>x!==b.id):[...s,b.id]);setFeedback(null)}} className={`wine-bottle-card ${selected.includes(b.id)?"is-selected":""}`}><i className={`wine-mini-bottle bottle-${b.category}`}/><span><b>{b.name}</b><small>{b.category} · €{b.price}</small></span></button>)}</div>
  <div className="wine-reveal flex flex-wrap items-center justify-between gap-4">{feedback?<p className={valid?"text-[var(--wine-vine)]":"text-[var(--wine-muted)]"}>{feedback}</p>:<p className="text-[var(--wine-muted)]">{locale==="de"?"Decke alle Lichter ab, ohne das Budget zu sprengen.":"Light every required category without breaking budget."}</p>}<button disabled={!selected.length} onClick={submit} className="wine-button">{locale==="de"?"Keller bewerten":"Evaluate cellar"}</button></div>
 </div></>;
}
function ConnectionsGame(props:PlayProps){
 const {locale}=useT();const groups=useMemo(()=>[
  {id:"bordeaux",items:[locale==="de"?"Frankreich":"France","Cabernet Sauvignon","maritime","Pauillac"]},
  {id:"rioja",items:[locale==="de"?"Spanien":"Spain","Tempranillo","Atlantic influence","Rioja Alta"]},
  {id:"barossa",items:[locale==="de"?"Australien":"Australia","Shiraz","warm Mediterranean","Barossa GI"]},
  {id:"mosel",items:[locale==="de"?"Deutschland":"Germany","Riesling","steep slate slopes","Mosel"]},
 ],[locale]);const items=useMemo(()=>shuffle(groups.flatMap(g=>g.items.map((label,i)=>({id:`${g.id}-${i}`,group:g.id,label}))),props.seed+2),[groups,props.seed]);const [selected,setSelected]=useState<string[]>([]),[solved,setSolved]=useState<string[]>([]),[mistakes,setMistakes]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props);
 const submit=()=>{const picked=items.filter(x=>selected.includes(x.id));if(picked.length===4&&new Set(picked.map(x=>x.group)).size===1){const next=[...solved,picked[0].group];setSolved(next);setSelected([]);if(next.length===4){finish(Math.max(200,1000-mistakes*100),4,4,4,start);setDone(true)}}else{setMistakes(x=>x+1);setSelected([])}};
 if(done)return <Result {...props} score={Math.max(200,1000-mistakes*100)} correct={4} total={4} onReplay={props.onReplay}/>;
 return <><PlayHeader gameId={props.gameId} round={solved.length+1} total={4} score={solved.length*250-mistakes*25} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-3xl px-4 py-8"><h1 className="text-3xl font-black text-[var(--wine-cream)]">{locale==="de"?"Finde vier Begriffe mit einer gemeinsamen Wein-Verbindung.":"Find four terms with one wine connection."}</h1><div className="mt-7 grid grid-cols-2 gap-2 sm:grid-cols-4">{items.filter(x=>!solved.includes(x.group)).map(x=><button key={x.id} onClick={()=>setSelected(s=>s.includes(x.id)?s.filter(id=>id!==x.id):s.length<4?[...s,x.id]:s)} className={`wine-tile ${selected.includes(x.id)?"is-selected":""}`}>{x.label}</button>)}</div><button disabled={selected.length!==4} onClick={submit} className="wine-button mt-6">{locale==="de"?"Gruppe prüfen":"Check group"}</button>{mistakes>0&&<p className="mt-3 text-sm text-[var(--wine-muted)]">{mistakes} {locale==="de"?"Fehlversuche":"misses"}</p>}</div></>;
}
function LadderGame(props:PlayProps){
 const {locale}=useT();const chain=useMemo(()=>{const a=APPELLATIONS[props.seed%APPELLATIONS.length],r=REGIONS.find(x=>x.id===a.regionId)!;return [{key:"country",answer:localize(r.country,locale),options:shuffle([...new Set(REGIONS.map(x=>localize(x.country,locale)))],props.seed).slice(0,3)},{key:"region",answer:localize(r.name,locale),options:shuffle(REGIONS.map(x=>localize(x.name,locale)),props.seed+1).slice(0,3)},{key:"appellation",answer:a.name,options:shuffle(APPELLATIONS.map(x=>x.name),props.seed+2).slice(0,3)},{key:"style",answer:localize(a.style,locale),options:shuffle(APPELLATIONS.map(x=>localize(x.style,locale)),props.seed+3).slice(0,3)}].map(x=>({...x,options:shuffle([...new Set([...x.options,x.answer])],props.seed+4).slice(0,4)}))},[props.seed,locale]);const [step,setStep]=useState(0),[score,setScore]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props),current=chain[step];const answer=(v:string)=>{const ok=v===current.answer;const next=score+(ok?250:0);setScore(next);if(step===chain.length-1){finish(next,Math.round(next/250),4,0,start);setDone(true)}else setStep(x=>x+1)};
 if(done)return <Result {...props} score={score} correct={Math.round(score/250)} total={4} onReplay={props.onReplay}/>;
 return <><PlayHeader gameId={props.gameId} round={step+1} total={4} score={score} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-2xl px-4 py-8"><p className="wine-kicker">{chain.slice(0,step).map(x=>x.answer).join(" → ")|| (locale==="de"?"Beginne beim Land":"Begin with the country")}</p><h1 className="mt-4 text-4xl font-black capitalize text-[var(--wine-cream)]">{current.key}</h1><div className="mt-8 grid gap-3">{current.options.map(o=><button key={o} onClick={()=>answer(o)} className="wine-answer">{o}<ArrowRight className="h-4 w-4"/></button>)}</div></div></>;
}
function DilemmaGame(props:PlayProps){
 const {locale}=useT();const scenarios=useMemo(()=>shuffle(DILEMMAS,props.seed).slice(0,3),[props.seed]);const [step,setStep]=useState(0),[profile,setProfile]=useState({acidity:3,body:3,fruit:3,tannin:2,risk:2}),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props),d=scenarios[step];const clamp=(n:number)=>Math.max(0,Math.min(5,n));const choose=(c:typeof d.choices[number])=>{const early=c.id==="early",later=c.id==="later";const next={acidity:clamp(profile.acidity+c.delta.freshness),body:clamp(profile.body+c.delta.body),fruit:clamp(profile.fruit+(later?2:early?-1:1)),tannin:clamp(profile.tannin+(later?1:0)),risk:clamp(profile.risk+(later?2:early?1:0))};setProfile(next);if(step===2){finish(800,3,3,3,start);setDone(true)}else setStep(x=>x+1)};
 if(done)return <Result {...props} score={800} correct={3} total={3} onReplay={props.onReplay} note={locale==="de"?"Deine Entscheidungen haben ein eigenständiges, nicht absolut „richtiges“ Stilprofil erzeugt.":"Your decisions produced a distinct style profile rather than one absolute correct wine."} profile={profile}/>;
 const stages=locale==="de"?["Austrieb","Saison","Lese","Gärung","Reife"]:["Budburst","Season","Harvest","Ferment","Ageing"];
 return <><PlayHeader gameId={props.gameId} round={step+1} total={3} score={step*250} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-7">
  <div className="wine-vintage-timeline">{stages.map((s,i)=><div key={s} className={`wine-vintage-stage ${i<=step+2?"is-past":""} ${i===step+2?"is-current":""}`}><i/>{s}</div>)}</div>
  <div className="mt-7 grid gap-7 lg:grid-cols-[1fr_260px]"><section><p className="wine-kicker">{locale==="de"?"Entscheidung mit Trade-offs":"A decision with trade-offs"}</p><h1 className="mt-3 text-3xl font-black text-[var(--wine-cream)]">{localize(d.setup,locale)}</h1><div className="mt-7 grid gap-3">{d.choices.map(c=><button key={c.id} onClick={()=>choose(c)} className="wine-decision-card"><span className="wine-decision-weather">{c.id==="early"?"☀︎":c.id==="later"?"◒":"↔"}</span><span><b>{localize(c.label,locale)}</b><small>{localize(c.effect,locale)}</small></span><ArrowRight className="h-5 w-5 shrink-0"/></button>)}</div></section>
  <aside className="wine-profile-panel"><p className="wine-kicker">{locale==="de"?"Prognose":"Projected wine"}</p>{Object.entries(profile).map(([key,value])=><ProfileMeter key={key} label={key} value={value}/>)}</aside></div>
 </div></>;
}
function SameGrapeGame(props:PlayProps){
 const {locale}=useT();const grape=GRAPES[props.seed%GRAPES.length],a=grape.regions[0],b=grape.regions[1]??"another region";const traits=[`cooler / fresher expression`,`warmer / richer expression`,`more restrained fruit`,`riper fruit weight`];const [assigned,setAssigned]=useState<Record<string,"a"|"b">>({}),[done,setDone]=useState(false),[finalCorrect,setFinalCorrect]=useState(0),[start]=useState(Date.now());const finish=useFinish(props);const submit=()=>{const correct=[0,1,2,3].filter(i=>assigned[i]===(i%2===0?"a":"b")).length;setFinalCorrect(correct);finish(correct*250,correct,4,correct,start);setDone(true)};
 if(done)return <Result {...props} score={finalCorrect*250} correct={finalCorrect} total={4} onReplay={props.onReplay}/>;
 return <><PlayHeader gameId={props.gameId} round={Object.keys(assigned).length} total={4} score={Object.keys(assigned).length*200} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-3xl px-4 py-8"><p className="wine-kicker">{grape.name}</p><h1 className="mt-3 text-3xl font-black text-[var(--wine-cream)]">{locale==="de"?`Ordne die Stilhinweise ${a} oder ${b} zu.`:`Assign each style clue to ${a} or ${b}.`}</h1><div className="mt-7 space-y-3">{traits.map((t,i)=><div key={t} className="wine-assign"><span>{locale==="de"?t.replace("cooler","kühler").replace("warmer","wärmer").replace("fruit","Frucht"):t}</span><div className="flex gap-2"><button onClick={()=>setAssigned(x=>({...x,[i]:"a"}))} className={`wine-mini ${assigned[i]==="a"?"is-selected":""}`}>{a}</button><button onClick={()=>setAssigned(x=>({...x,[i]:"b"}))} className={`wine-mini ${assigned[i]==="b"?"is-selected":""}`}>{b}</button></div></div>)}</div><button disabled={Object.keys(assigned).length<4} onClick={submit} className="wine-button mt-6">{locale==="de"?"Vergleich prüfen":"Review comparison"}</button></div></>;
}
function MysteryGame(props:PlayProps){
 const {locale}=useT();const answer=GRAPES[props.seed%GRAPES.length];const options=useMemo(()=>shuffle([answer,...GRAPES.filter(g=>g.id!==answer.id).slice(0,4)],props.seed),[answer,props.seed]);const clues=[answer.climate,answer.clue,{en:`Structure: ${answer.structure.en}`,de:`Struktur: ${answer.structure.de}`}];const [shown,setShown]=useState(1),[wrong,setWrong]=useState<string|null>(null),[done,setDone]=useState(false),[score,setScore]=useState(0),[start]=useState(Date.now());const finish=useFinish(props);const decoys=options.filter(o=>o.id!==answer.id);const eliminated=new Set(decoys.slice(0,Math.min(decoys.length,Math.ceil(shown*decoys.length/3))).map(x=>x.id));const choose=(id:string)=>{if(eliminated.has(id))return;const ok=id===answer.id;if(!ok){setWrong(id);return}const s=Math.max(300,1000-(shown-1)*200);setScore(s);finish(s,1,1,0,start);setDone(true)};
 if(done)return <Result {...props} score={score} correct={score?1:0} total={1} onReplay={props.onReplay} note={localize(answer.clue,locale)}/>;
 return <><PlayHeader gameId={props.gameId} round={shown} total={3} score={1000-(shown-1)*200} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-7"><p className="wine-kicker">{locale==="de"?"Fallakte 27-B":"Case file 27-B"}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{locale==="de"?"Welche Flasche übersteht die Beweislage?":"Which bottle survives the evidence?"}</h1>
  <div className="wine-evidence-board mt-6"><div className="wine-clue-stack">{clues.slice(0,shown).map((c,i)=><article key={i} className="wine-clue-card" style={{"--clue-tilt":`${i%2?2:-2}deg`} as React.CSSProperties}><span>0{i+1}</span><p>{localize(c,locale)}</p></article>)}{shown<3&&<button onClick={()=>{setShown(x=>x+1);setWrong(null)}} className="wine-clue-reveal">+ {locale==="de"?"Hinweis aufdecken (-200)":"Reveal evidence (-200)"}</button>}</div>
   <div className="wine-suspects">{options.map((o,i)=>{const crossed=eliminated.has(o.id);return <button key={o.id} disabled={crossed} onClick={()=>choose(o.id)} className={`wine-suspect ${crossed?"is-crossed":""} ${wrong===o.id?"is-wrong":""}`}><span className="wine-suspect-bottle"><i/><em>{String(i+1).padStart(2,"0")}</em></span><b>{o.name}</b><small>{localize(o.structure,locale)}</small>{crossed&&<span className="wine-conflict">{locale==="de"?"widerspricht Hinweis":"conflicts with clue"}</span>}</button>})}</div>
  </div>
  {wrong&&<div className="wine-reveal"><p className="font-bold">{locale==="de"?"Diese Flasche widerspricht der bisherigen Beweislage.":"That bottle conflicts with the accumulated evidence."}</p><p className="mt-2 text-sm text-[var(--wine-muted)]">{localize(clues[Math.min(shown-1,2)],locale)}</p></div>}
 </div></>;
}
function NoteBuilder(props:PlayProps){
 const {locale}=useT();const appearance=["pale ruby","deep ruby","pale lemon"],aromas=["fresh red fruit","ripe dark fruit","citrus","fresh herbs","violet","cedar"],conclusions=["best enjoyed young","can develop further","drink now"];const [look,setLook]=useState(""),[nose,setNose]=useState<string[]>([]),[structure,setStructure]=useState({acidity:3,tannin:2,body:3,sweetness:1,alcohol:3}),[conclusion,setConclusion]=useState(""),[done,setDone]=useState(false),[finalScore,setFinalScore]=useState(0),[start]=useState(Date.now());const finish=useFinish(props);const completed=(look?1:0)+(nose.length>=2?1:0)+1+(conclusion?1:0);const submit=()=>{const aromaFit=(look==="pale ruby"&&nose.includes("fresh red fruit"))||(look==="deep ruby"&&nose.includes("ripe dark fruit"))||(look==="pale lemon"&&(nose.includes("citrus")||nose.includes("fresh herbs")));const structureFit=(look==="pale lemon"&&structure.tannin<=1)||(look==="pale ruby"&&structure.body<=3)||(look==="deep ruby"&&structure.body>=3&&structure.tannin>=2);const coherent=aromaFit&&structureFit;const s=coherent?1000:700;setFinalScore(s);finish(s,coherent?5:4,5,0,start);setDone(true)};
 if(done)return <Result {...props} score={finalScore} correct={finalScore===1000?5:4} total={5} onReplay={props.onReplay} note={finalScore===1000?(locale==="de"?"Aussehen, Aromen und Struktur bilden ein plausibles Ganzes.":"Appearance, aromas and structure form a defensible whole."):(locale==="de"?"Einige Beobachtungen widersprechen sich. Eine helle Farbe und sehr hohes Tannin oder eine tiefe Farbe ohne Körper brauchen mehr Begründung.":"Some observations pull apart. Pale colour with very high tannin, or deep colour without body, needs stronger reasoning.")} profile={structure}/>;
 const fillClass=look==="deep ruby"?"fill-deep":look==="pale lemon"?"fill-lemon":"fill-pale";
 return <><PlayHeader gameId={props.gameId} round={completed} total={4} score={completed*180} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-7"><p className="wine-kicker">{locale==="de"?"Eigenes, nicht-proprietäres Lernschema":"Original, non-proprietary learning framework"}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{locale==="de"?"Komponiere eine stimmige Tasting Note.":"Compose a coherent tasting note."}</h1>
  <div className="wine-note-workbench mt-7"><aside className="wine-note-visual"><div className={`wine-tasting-glass ${fillClass}`}><div className="wine-tasting-bowl"><i/></div><div className="wine-tasting-stem"/><div className="wine-tasting-foot"/></div><div className="wine-note-aromas">{nose.map((a,i)=><span key={a} style={{"--note-index":i} as React.CSSProperties}>{a}</span>)}</div></aside>
  <section className="wine-notebook"><fieldset><legend><span>01</span>{locale==="de"?"Aussehen":"Appearance"}</legend><div className="wine-segments">{appearance.map(v=><button type="button" key={v} onClick={()=>setLook(v)} className={look===v?"is-selected":""}>{v}</button>)}</div></fieldset>
   <fieldset><legend><span>02</span>{locale==="de"?"Nase · 2–3 wählen":"Nose · choose 2–3"}</legend><div className="flex flex-wrap gap-2">{aromas.map(v=><button type="button" key={v} onClick={()=>setNose(s=>s.includes(v)?s.filter(x=>x!==v):s.length<3?[...s,v]:s)} className={`wine-aroma-token family-${aromaFamily(v)} ${nose.includes(v)?"is-selected":""}`}>{v}</button>)}</div></fieldset>
   <fieldset><legend><span>03</span>{locale==="de"?"Struktur":"Structure"}</legend><div className="wine-structure-controls">{Object.entries(structure).map(([key,value])=><label key={key}><span>{key}<b>{value}/5</b></span><input aria-label={key} type="range" min="1" max="5" step="1" value={value} onChange={e=>setStructure(s=>({...s,[key]:Number(e.target.value)}))}/></label>)}</div></fieldset>
   <fieldset><legend><span>04</span>{locale==="de"?"Schluss":"Conclusion"}</legend><div className="wine-segments">{conclusions.map(v=><button type="button" key={v} onClick={()=>setConclusion(v)} className={conclusion===v?"is-selected":""}>{v}</button>)}</div></fieldset>
  </section></div><button disabled={!look||nose.length<2||!conclusion} onClick={submit} className="wine-button mt-7">{locale==="de"?"Notiz prüfen":"Review note"}</button>
 </div></>;
}
function ProfileMeter({label,value}:{label:string;value:number}){return <div className="wine-profile-meter"><span>{label}<b>{value}/5</b></span><div>{Array.from({length:5},(_,i)=><i key={i} className={i<value?"is-on":""}/>)}</div></div>}
function Result(props:PlayProps&{score:number;correct:number;total:number;onReplay:()=>void;note?:string;profile?:Record<string,number>}){
 const {locale}=useT();const accuracy=Math.round(props.correct/Math.max(1,props.total)*100);return <div className="mx-auto max-w-3xl px-4 py-12 md:py-20"><p className="wine-kicker">{props.practice?(locale==="de"?"Übungsrunde beendet":"Practice complete"):(locale==="de"?"Kellerpass gestempelt":"Cellar passport stamped")}</p><h1 className="mt-3 text-5xl font-black tracking-[-.05em] text-[var(--wine-cream)]">{props.score} <span className="text-2xl text-[var(--wine-copper)]">pts</span></h1><div className="mt-8 grid grid-cols-2 gap-3"><div className="wine-stat"><span>{props.correct}/{props.total}</span><small>{locale==="de"?"stimmig":"defensible"}</small></div><div className="wine-stat"><span>{accuracy}%</span><small>{locale==="de"?"Genauigkeit":"accuracy"}</small></div></div>{props.profile&&<div className="wine-profile-panel mt-5"><p className="wine-kicker">{locale==="de"?"Dein visuelles Weinprofil":"Your visual wine profile"}</p>{Object.entries(props.profile).map(([key,value])=><ProfileMeter key={key} label={key} value={value}/>)}</div>}{props.note&&<p className="wine-reveal">{props.note}</p>}<p className="mt-6 text-sm leading-6 text-[var(--wine-muted)]">{props.practice?(locale==="de"?"Wie versprochen wurde nichts gespeichert.":"As promised, nothing was saved."):(locale==="de"?"XP, Kompetenzfortschritt und neue Wine-Dex-Begegnungen wurden separat gespeichert.":"XP, competency progress and new Wine-Dex encounters were saved separately.")}</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={props.onReplay} className="wine-button"><RotateCcw className="h-4 w-4"/>{locale==="de"?"Nochmal":"Play again"}</button><Link href="/wine-nerds" className="wine-button wine-button-quiet">{locale==="de"?"Zum Keller":"Wine cellar"}</Link></div></div>
}
