"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Clock3, RotateCcw, Sparkles, X, LocateFixed } from "lucide-react";
import { useT } from "@/i18n/I18nProvider";
import { getWineGame } from "@/wine/registry";
import type { WineCompetency, WineGameId, WineRun } from "@/wine/types";
import { localize } from "@/wine/types";
import { questionsFor, scoreMapClick, shuffle, type WineQuestion } from "@/wine/engine";
import { APPELLATIONS, CELLAR_BOTTLES, CELLAR_BRIEFS, GRAPES, PAIRINGS, REGIONS } from "@/wine/content";
import { useWineDaily, useWineDex, useWineProgression, useWineScores } from "@/wine/store";
import { PinMap } from "@/components/map/pin-map";
import { Compass } from "@/components/map/compass";
import { AROMA_WHEEL_FAMILIES, SAME_GRAPE_PAIRS, SERVICE_SCENARIOS, VINTAGE_SCENARIOS, aromaWheelFamily, type ServiceDecision } from "@/wine/visual-content";
import { buildDeductionCase, incompatibleIds, type DeductionGameId } from "@/wine/deduction";
import { CONFIDENCE_MULTIPLIER, WINE_DIFFICULTY, deductionScore, objectiveScore, type Confidence } from "@/wine/session";
import { WineRunHud } from "@/components/wine/gameplay/wine-run-hud";
import { DeductionBoard } from "@/components/wine/gameplay/deduction-board";
import { WINE_COMPETENCIES } from "@/wine/progression";

type Difficulty="easy"|"medium"|"hard";
const ROUND_COUNTS:Record<Difficulty,number>={easy:5,medium:8,hard:12};

export function WineGameRunner({gameId}:{gameId:WineGameId}) {
 const {locale}=useT(); const game=getWineGame(gameId);
 const [difficulty,setDifficulty]=useState<Difficulty>("medium");
 const [practice,setPractice]=useState(false); const [phase,setPhase]=useState<"setup"|"playing">("setup"); const [sessionSeed,setSessionSeed]=useState(0);
 const startSession=()=>{setSessionSeed(Date.now());setPhase("playing")};
 const replay=()=>setSessionSeed(Date.now());
 if(phase==="setup")return <div className="mx-auto max-w-3xl px-4 py-10 md:py-16">
  <Link href="/wine-nerds" className="wine-back"><ArrowLeft className="h-4 w-4"/>{locale==="de"?"Zum Weinkeller":"To the wine cellar"}</Link>
  <p className="wine-kicker mt-10">{localize(game.eyebrow,locale)}</p>
  <h1 className="mt-3 text-4xl font-black tracking-[-.05em] text-[var(--wine-cream)] md:text-6xl">{localize(game.title,locale)}</h1>
  <p className="mt-5 max-w-2xl text-base leading-7 text-[var(--wine-muted)]">{localize(game.description,locale)}</p>
  <div className="mt-10 border-y border-[var(--wine-line)] py-7">
   <p className="wine-kicker">{locale==="de"?"Schwierigkeit":"Difficulty"}</p>
   <div className="mt-3 grid grid-cols-3 gap-2">{(["easy","medium","hard"] as Difficulty[]).map(d=><button key={d} onClick={()=>setDifficulty(d)} className={`wine-option ${difficulty===d?"is-selected":""}`}>{d==="easy"?(locale==="de"?"Einstieg":"Cellar door"):d==="medium"?(locale==="de"?"Service":"Service"):(locale==="de"?"Prüfung":"Exam")}</button>)}</div>
   <label className="mt-5 flex min-h-11 cursor-pointer items-center gap-3 text-sm text-[var(--wine-muted)]"><input type="checkbox" checked={practice} onChange={e=>setPractice(e.target.checked)} className="h-5 w-5 accent-[var(--wine-copper)]"/><span><b className="text-[var(--wine-cream)]">{locale==="de"?"Übungsmodus":"Practice mode"}</b> · {locale==="de"?"speichert keine XP, Stempel oder Scores":"saves no XP, stamps or scores"}</span></label>
  </div>
  {gameId==="sommelier-exam"&&<p className="mt-5 text-xs leading-5 text-[var(--wine-muted)]">{locale==="de"?"Inoffizielle Übungsprüfung. Nicht mit WSET oder einer anderen Zertifizierungsstelle verbunden. Kein Alkoholkonsum erforderlich.":"Unofficial practice exam. Not affiliated with WSET or any certification body. No alcohol consumption is required."}</p>}
  <button type="button" data-testid="wine-start-session" className="wine-button mt-8 w-full sm:w-auto" onClick={startSession}>{locale==="de"?"Session starten":"Start session"}<ArrowRight className="h-4 w-4"/></button>
 </div>;
 const props={gameId,difficulty,practice,seed:sessionSeed,onReplay:replay,onExit:()=>setPhase("setup")};
 if(gameId==="wine-map")return <MapGame key={sessionSeed} {...props}/>;
 if(gameId==="terroir-detective"||gameId==="grape-dna"||gameId==="cellar-mystery")return <DeductionGame key={sessionSeed} {...props} gameId={gameId}/>;
 if(gameId==="aroma-atelier")return <AromaAtelierGame key={sessionSeed} {...props}/>;
 if(gameId==="pairing-duel")return <PairingDuelGame key={sessionSeed} {...props}/>;
 if(gameId==="cellar-builder")return <CellarBuilder key={sessionSeed} {...props}/>;
 if(gameId==="label-decoder")return <LabelDecoderGame key={sessionSeed} {...props}/>;
 if(gameId==="regional-connections")return <ConnectionsGame key={sessionSeed} {...props}/>;
 if(gameId==="appellation-ladder")return <LadderGame key={sessionSeed} {...props}/>;
 if(gameId==="winemakers-dilemma")return <DilemmaGame key={sessionSeed} {...props}/>;
 if(gameId==="same-grape")return <SameGrapeGame key={sessionSeed} {...props}/>;
 if(gameId==="tasting-note-builder")return <NoteBuilder key={sessionSeed} {...props}/>;
 if(gameId==="service-challenge")return <ServiceChallenge key={sessionSeed} {...props}/>;
 return <ChoiceGame key={sessionSeed} {...props}/>;
}

interface PlayProps {gameId:WineGameId;difficulty:Difficulty;practice:boolean;seed:number;onReplay:()=>void;onExit:()=>void}
function useFinish({gameId,difficulty,practice}:PlayProps) {
 const progress=useWineProgression(s=>s.record), add=useWineScores(s=>s.add), daily=useWineDaily(s=>s.complete);
 return (score:number,correct:number,total:number,streak:number,start:number)=>{
  const run:WineRun={id:`wine-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,gameId,difficulty,practice,score,correct,total,bestStreak:streak,durationMs:Date.now()-start,createdAt:Date.now()};
  progress(run);add(run);if(!practice){daily(new Date().toISOString().slice(0,10));void fetch("/api/wine-scores",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(run)}).catch(()=>undefined)}return run;
 };
}
function PlayHeader({gameId,round,total,score,practice,onExit}:{gameId:WineGameId;round:number;total:number;score:number;practice:boolean;onExit:()=>void}){
 const {locale}=useT();return <header className="border-b border-[var(--wine-line)] bg-black/15"><div className="mx-auto flex min-h-16 max-w-4xl items-center gap-4 px-4"><button onClick={onExit} className="wine-icon" aria-label="Exit"><X className="h-5 w-5"/></button><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-[var(--wine-cream)]">{localize(getWineGame(gameId).title,locale)}</p><div className="mt-1 h-1 bg-white/10"><div className="h-full bg-[var(--wine-copper)]" style={{width:`${Math.min(100,round/Math.max(1,total)*100)}%`}}/></div></div><span className="font-mono text-sm font-bold">{score}</span>{practice&&<span className="hidden text-[10px] uppercase tracking-wider text-[var(--wine-vine)] sm:block">practice</span>}</div></header>
}
function structureLevel(text:string,trait:"body"|"acidity"|"tannin"){
 const segment=text.toLowerCase().split(",").find(part=>part.includes(trait))??text.toLowerCase();
 if(segment.includes("very high"))return 5;if(segment.includes("high"))return 4;if(segment.includes("medium-high"))return 4;if(segment.includes("medium"))return 3;if(segment.includes("low-medium"))return 2;if(segment.includes("low"))return 1;return 2;
}
function TerroirDossier({grape,locale}:{grape:typeof GRAPES[number];locale:"en"|"de"}){
 return <section className="wine-terroir-dossier" aria-label={locale==="de"?"Visuelles Lagen-Dossier":"Visual site dossier"}>
  <div className="wine-vineyard-scene"><span className="wine-site-sun"/><span className="wine-site-slope"/><span className="wine-vine-row row-a"/><span className="wine-vine-row row-b"/><span className="wine-vine-row row-c"/><span className="wine-soil-layer layer-a"/><span className="wine-soil-layer layer-b"/><span className="wine-scene-label label-climate">{localize(grape.climate,locale)}</span><span className="wine-scene-label label-soil">{locale==="de"?"Boden: herkunftsspezifisch":"Soil: origin-specific"}</span></div>
  <div className="wine-evidence-ledger"><p className="wine-kicker">{locale==="de"?"Beobachtbare Indizien":"Observed evidence"}</p><strong>{localize(grape.structure,locale)}</strong><div>{grape.aromas.map(a=><span key={a}>{a}</span>)}</div><small>{locale==="de"?"Exposition und Boden sind keine festen Rebsortenmerkmale; sie bleiben Teil der Lagenanalyse.":"Exposure and soil are not fixed grape traits; they remain part of site analysis."}</small></div>
 </section>
}
function GrapeDnaBoard({grape,locale}:{grape:typeof GRAPES[number];locale:"en"|"de"}){
 const metrics=[["acidity",structureLevel(grape.structure.en,"acidity")],["tannin",structureLevel(grape.structure.en,"tannin")],["body",structureLevel(grape.structure.en,"body")]] as const;
 return <section className="wine-dna-board" aria-label={locale==="de"?"Anonymes Rebsortenprofil":"Anonymous grape profile"}>
  <div className="wine-dna-mark"><i/><i/><i/><i/><i/><i/><span>?</span></div><div className="wine-dna-data"><p className="wine-kicker">{locale==="de"?"Anonyme Probe":"Anonymous sample"}</p><div className="wine-climate-band"><span>{locale==="de"?"kühl":"cool"}</span><b style={{left:grape.climate.en.includes("warm")?"72%":grape.climate.en.includes("moderate")?"50%":"24%"}}/><span>{locale==="de"?"warm":"warm"}</span></div>{metrics.map(([label,value])=><ProfileMeter key={label} label={label} value={value}/>)}</div><div className="wine-dna-aromas">{grape.aromas.map((a,i)=><span key={a}><i>{String(i+1).padStart(2,"0")}</i>{a}</span>)}</div>
 </section>
}
function PairingDuelScene({pairing,locale,selected}:{pairing:typeof PAIRINGS[number];locale:"en"|"de";selected:string|null}){
 return <div className={`wine-pairing-arena ${selected?`leans-${selected}`:""}`}><div className="wine-duel-bottle bottle-left"><i/><span>A</span></div><div className="wine-pairing-plate"><i/><span>{localize(pairing.dish,locale)}</span></div><div className="wine-duel-bottle bottle-right"><i/><span>B</span></div><div className="wine-duel-line"/></div>
}
const EXAM_COMPETENCY_LABELS:Record<WineCompetency,{en:string;de:string}>={
 geography:{en:"Geography",de:"Geografie"},terroir:{en:"Terroir",de:"Terroir"},grapes:{en:"Grapes",de:"Rebsorten"},sensory:{en:"Sensory",de:"Sensorik"},
 pairing:{en:"Pairing",de:"Pairing"},service:{en:"Service",de:"Service"},production:{en:"Production",de:"Produktion"},theory:{en:"Theory",de:"Theorie"},
};
function examCompetency(q:WineQuestion):WineCompetency {
 if(q.id.startsWith("exam-service"))return "service";
 if(q.id.startsWith("exam-production"))return "production";
 if(q.id.startsWith("pairing"))return "pairing";
 if(q.id.startsWith("aroma"))return "sensory";
 if(q.id.startsWith("label"))return "theory";
 if(q.id.startsWith("region"))return "geography";
 if(q.id.includes("grape-dna"))return "grapes";
 return "terroir";
}
function examServiceQuestions(seed:number):WineQuestion[] {
 const decisionLabels={
  glass:{en:"Which glass is the best starting point?",de:"Welches Glas ist der beste Ausgangspunkt?"},
  temperature:{en:"Which temperature band is most defensible?",de:"Welcher Temperaturbereich ist am plausibelsten?"},
  decant:{en:"How should decanting be assessed?",de:"Wie sollte Dekantieren bewertet werden?"},
 } as const;
 const banks={
  glass:[["tulip","Tulip sparkling glass","Tulpenförmiges Schaumweinglas"],["medium-white","Medium white-wine glass","Mittleres Weißweinglas"],["medium-red","Medium red-wine glass","Mittleres Rotweinglas"],["large-red","Large red-wine glass","Großes Rotweinglas"],["small-sweet","Small sweet-wine glass","Kleines Süßweinglas"]],
  temperature:[["well-chilled","Well chilled","Gut gekühlt"],["cool","Cool","Kühl"],["lightly-chilled","Lightly chilled","Leicht gekühlt"],["cellar-cool","Cellar-cool","Kellerkühl"]],
  decant:[["no","Usually no","Meist nein"],["optional","Conditionally defensible","Situativ vertretbar"],["yes","Often defensible","Häufig vertretbar"]],
 } as const;
 const keys=["glass","temperature","decant"] as const;
 return SERVICE_SCENARIOS.map((scenario,i)=>{
  const key=keys[(i+seed)%keys.length];
  return {id:`exam-service-${scenario.id}-${key}`,prompt:{en:`${scenario.style.en} for ${scenario.context.en}: ${decisionLabels[key].en}`,de:`${scenario.style.de} für ${scenario.context.de}: ${decisionLabels[key].de}`},choices:banks[key].map(row=>({id:row[0],label:{en:row[1],de:row[2]}})),answer:scenario.answers[key],explanation:scenario.explanation,entity:{id:scenario.id,type:"style" as const}};
 });
}
function examProductionQuestions(seed:number):WineQuestion[] {
 return VINTAGE_SCENARIOS.map((scenario,i)=>{
  const stage=scenario.stages[(i+seed)%scenario.stages.length],answer=stage.choices[(i+seed)%stage.choices.length];
  return {id:`exam-production-${scenario.id}-${stage.id}`,prompt:{en:`In this fictional season, which decision produces this modeled consequence: “${answer.effect.en}”?`,de:`Welche Entscheidung erzeugt in diesem fiktiven Jahrgang diese modellierte Folge: „${answer.effect.de}“?`},choices:stage.choices.map(choice=>({id:choice.id,label:choice.label})),answer:answer.id,explanation:{en:`${answer.label.en}: ${answer.effect.en} This is a teaching model, not a universal prescription.`,de:`${answer.label.de}: ${answer.effect.de} Dies ist ein Lernmodell, keine allgemeingültige Vorschrift.`},entity:{id:scenario.id,type:"style" as const}};
 });
}
function DeductionGame(props:PlayProps&{gameId:DeductionGameId}){
 const {locale}=useT(),profile=WINE_DIFFICULTY[props.difficulty];const caseFile=useMemo(()=>buildDeductionCase(props.gameId,props.seed,profile.suspects),[props.gameId,props.seed,profile.suspects]);const [revealed,setRevealed]=useState(0),[crossed,setCrossed]=useState<Set<string>>(new Set()),[selected,setSelected]=useState<string|null>(null),[confidence,setConfidence]=useState<Confidence>("standard"),[lives,setLives]=useState(profile.startingLives),[locked,setLocked]=useState(false),[outcome,setOutcome]=useState<"correct"|"retry"|"failed"|null>(null),[finalScore,setFinalScore]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props),encounter=useWineDex(s=>s.encounter);const clues=caseFile.clues.slice(0,revealed),incompatible=new Set(incompatibleIds(caseFile.suspects,clues));const availableClues=Math.max(0,Math.min(profile.clueBudget,caseFile.clues.length)-revealed);const provisional=Math.max(100,1000-revealed*profile.clueCost);
 const toggle=(id:string)=>setCrossed(old=>{const next=new Set(old);if(next.has(id))next.delete(id);else next.add(id);return next});
 const submit=()=>{if(!selected||locked)return;const ok=selected===caseFile.answer.id;const score=deductionScore(1000,revealed,props.difficulty,confidence,ok);setFinalScore(score);setLocked(true);setOutcome(ok?"correct":lives>1?"retry":"failed")};
 const proceed=()=>{if(outcome==="retry"){setLives(x=>x-1);setSelected(null);setLocked(false);setOutcome(null);setConfidence("safe");return}const ok=outcome==="correct";finish(finalScore,ok?1:0,1,ok?1:0,start);if(!props.practice)encounter(caseFile.answer.id,"grape",props.gameId,ok);setDone(true)};
 if(done)return <Result {...props} score={finalScore} correct={outcome==="correct"?1:0} total={1} onReplay={props.onReplay} note={localize(caseFile.answer.clue,locale)}/>;
 const names={ "terroir-detective":locale==="de"?"Lagenakte":"Site case file","grape-dna":locale==="de"?"DNA-Labor":"DNA lab","cellar-mystery":locale==="de"?"Kellerermittlung":"Cellar investigation"};
 return <><PlayHeader gameId={props.gameId} round={Math.max(1,revealed)} total={Math.min(profile.clueBudget,caseFile.clues.length)} score={provisional} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-6"><WineRunHud score={provisional} streak={outcome==="correct"?1:0} hints={availableClues} lives={lives}/><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="wine-kicker">{names[props.gameId]}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{locale==="de"?"Baue deine Schlussfolgerung aus bezahlten Indizien.":"Build your conclusion from evidence you choose to reveal."}</h1></div>{availableClues>0&&<button type="button" disabled={locked} onClick={()=>setRevealed(x=>x+1)} className="wine-button wine-button-quiet"><Sparkles className="h-4 w-4"/>{locale==="de"?`Indiz aufdecken (−${profile.clueCost})`:`Reveal clue (−${profile.clueCost})`}</button>}</div>
  <div className="wine-clue-ledger mt-5" aria-live="polite">{clues.length?clues.map((clue,i)=><article key={clue.id}><span>{String(i+1).padStart(2,"0")}</span><div><b>{localize(clue.label,locale)}</b><p>{localize(clue.detail,locale)}</p></div><small>{incompatible.size} {locale==="de"?"Konflikte":"conflicts"}</small></article>):<div className="wine-empty-evidence">{locale==="de"?"Noch keine Antwort-Hinweise sichtbar. Entscheide, wie viel Sicherheit du kaufen willst.":"No answer evidence is visible yet. Decide how much certainty to buy."}</div>}</div>
  <DeductionBoard suspects={caseFile.suspects} crossed={crossed} incompatible={incompatible} selected={selected} onToggle={toggle} onSelect={setSelected} locked={locked}/>
  <div className="wine-confidence-stake mt-5"><p className="wine-kicker">{locale==="de"?"Konfidenz setzen":"Stake confidence"}</p><div>{(["safe","standard","bold"] as Confidence[]).map(c=><button key={c} disabled={locked} aria-pressed={confidence===c} onClick={()=>setConfidence(c)} className={confidence===c?"is-selected":""}>{c}<b>×{CONFIDENCE_MULTIPLIER[c]}</b></button>)}</div><button disabled={!selected||locked} onClick={submit} className="wine-button">{locale==="de"?"Verdacht festlegen":"Lock suspect"}<Check className="h-4 w-4"/></button></div>
  {outcome&&<div className={`wine-reveal ${outcome==="correct"?"is-success":""}`} aria-live="assertive"><p className="font-bold">{outcome==="correct"?(locale==="de"?"Deduktion bestätigt.":"Deduction confirmed."):(locale==="de"?"Der Verdacht widerspricht mindestens einem Indiz.":"The suspect conflicts with at least one clue.")}</p><p className="mt-2 text-sm text-[var(--wine-muted)]">{outcome==="correct"?localize(caseFile.answer.clue,locale):(locale==="de"?"Überprüfe Konfliktmarker und manuelle Streichungen.":"Review the conflict markers and your manual eliminations.")}</p><button onClick={proceed} className="wine-button mt-4">{outcome==="retry"?(locale==="de"?"Akte reparieren":"Repair case"):(locale==="de"?"Auswertung":"Results")}<ArrowRight className="h-4 w-4"/></button></div>}
 </div></>;
}
function ChoiceGame(props:PlayProps){
 const {locale}=useT();const isExam=props.gameId==="sommelier-exam";const count=isExam?12:ROUND_COUNTS[props.difficulty];
 const questions=useMemo(()=> {
  if (!isExam) return questionsFor(props.gameId,props.seed).slice(0,count);
  const buckets=[
   questionsFor("terroir-detective",props.seed),questionsFor("grape-dna",props.seed+1),
   questionsFor("aroma-atelier",props.seed+2),questionsFor("pairing-duel",props.seed+3),
   questionsFor("label-decoder",props.seed+4),questionsFor("wine-map",props.seed+5),
   examServiceQuestions(props.seed+6),examProductionQuestions(props.seed+7),
  ];
  const anchors=buckets.map((bucket,i)=>shuffle(bucket,props.seed+i)[0]);
  const anchorIds=new Set(anchors.map(q=>q.id));
  return [...anchors,...shuffle(buckets.flat().filter(q=>!anchorIds.has(q.id)),props.seed+8)].slice(0,count);
 },[props.gameId,props.seed,count,isExam]);
 const [index,setIndex]=useState(0),[selected,setSelected]=useState<string|null>(null),[score,setScore]=useState(0),[correct,setCorrect]=useState(0),[streak,setStreak]=useState(0),[best,setBest]=useState(0),[done,setDone]=useState(false);const [start]=useState(Date.now());
 const [timed,setTimed]=useState(isExam),[paused,setPaused]=useState(false),[seconds,setSeconds]=useState(WINE_DIFFICULTY[props.difficulty].examSeconds);
 const [breakdown,setBreakdown]=useState<Record<WineCompetency,{correct:number;total:number}>>(()=>Object.fromEntries(WINE_COMPETENCIES.map(c=>[c,{correct:0,total:0}])) as Record<WineCompetency,{correct:number;total:number}>);
 const submitted=useRef(false);
 const encounter=useWineDex(s=>s.encounter), finish=useFinish(props); const q=questions[index];const evidenceGrape=(props.gameId==="terroir-detective"||props.gameId==="grape-dna")?GRAPES.find(g=>g.id===q.answer):null;const pairing=props.gameId==="pairing-duel"?PAIRINGS.find(p=>p.id===q.entity?.id):null;
 useEffect(()=>{if(!isExam||!timed||paused||done||seconds<=0)return;const timer=window.setInterval(()=>setSeconds(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[isExam,timed,paused,done,seconds]);
 useEffect(()=>{if(!isExam||!timed||seconds!==0||done||submitted.current)return;submitted.current=true;finish(score,correct,questions.length,best,start);setDone(true)},[isExam,timed,seconds,done,score,correct,questions.length,best,start,finish]);
 const answer=(id:string)=>{if(selected||paused)return;setSelected(id);const ok=id===q.answer;const next=ok?streak+1:0;if(ok){setCorrect(x=>x+1);setScore(x=>x+100+Math.min(100,next*10));setBest(Math.max(best,next));}setStreak(next);if(isExam){const competency=examCompetency(q);setBreakdown(old=>({...old,[competency]:{correct:old[competency].correct+(ok?1:0),total:old[competency].total+1}}))}if(q.entity&&!props.practice)encounter(q.entity.id,q.entity.type,props.gameId,ok)};
 const next=()=>{if(index+1>=questions.length){submitted.current=true;finish(score,correct,questions.length,best,start);setDone(true)}else{setIndex(x=>x+1);setSelected(null)}};
 if(done)return <Result {...props} score={score} correct={correct} total={questions.length} onReplay={props.onReplay} breakdown={isExam?breakdown:undefined}/>;
 return <><PlayHeader gameId={props.gameId} round={index+1} total={questions.length} score={score} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-3xl px-4 py-8">
  {isExam&&<div className="wine-exam-controls mb-5"><div><Clock3 className="h-4 w-4"/><span>{timed?`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`:(locale==="de"?"Ohne Zeitlimit":"Untimed")}</span></div><button type="button" onClick={()=>{setTimed(value=>!value);setPaused(false)}}>{timed?(locale==="de"?"Zeitlimit aus":"Disable timer"):(locale==="de"?"Zeitlimit an":"Enable timer")}</button>{timed&&<button type="button" aria-pressed={paused} onClick={()=>setPaused(value=>!value)}>{paused?(locale==="de"?"Fortsetzen":"Resume"):(locale==="de"?"Pause":"Pause")}</button>}<small>{locale==="de"?"Inoffizielle gemischte Übung · 8 Kompetenzfelder":"Unofficial mixed practice · 8 competency areas"}</small></div>}
  {paused&&<div className="wine-reveal" role="status"><b>{locale==="de"?"Prüfung pausiert":"Exam paused"}</b><p className="mt-2 text-sm text-[var(--wine-muted)]">{locale==="de"?"Zeit und Eingaben sind angehalten.":"Timer and answers are paused."}</p></div>}
  <p className="wine-kicker">{locale==="de"?`Aufgabe ${index+1} von ${questions.length}`:`Prompt ${index+1} of ${questions.length}`}</p>
  <h1 className="mt-4 text-2xl font-black leading-tight text-[var(--wine-cream)] md:text-4xl">{localize(q.prompt,locale)}</h1>
  {props.gameId==="terroir-detective"&&evidenceGrape&&<TerroirDossier grape={evidenceGrape} locale={locale}/>}
  {props.gameId==="grape-dna"&&evidenceGrape&&<GrapeDnaBoard grape={evidenceGrape} locale={locale}/>}
  {pairing&&<PairingDuelScene pairing={pairing} locale={locale} selected={selected}/>}
  <div className={`mt-8 grid gap-3 sm:grid-cols-2 ${pairing?"wine-duel-choices":""}`}>{q.choices.map((c,choiceIndex)=>{const reveal=selected!==null,ok=c.id===q.answer,chosen=c.id===selected;return <button key={c.id} disabled={reveal} onClick={()=>answer(c.id)} className={`${pairing?"wine-duel-challenger":"wine-answer"} ${pairing?`challenger-${choiceIndex}`:""} ${reveal&&ok?"is-correct":""} ${reveal&&chosen&&!ok?"is-wrong":""}`}><span>{pairing&&<b>{choiceIndex?"B":"A"}</b>}{localize(c.label,locale)}</span>{reveal&&ok&&<Check className="h-5 w-5"/>}{reveal&&chosen&&!ok&&<X className="h-5 w-5"/>}</button>})}</div>
  {selected&&<div className="wine-reveal"><p className="wine-kicker">{selected===q.answer?(locale==="de"?"Stimmige Begründung":"Defensible reasoning"):(locale==="de"?"Lernmoment":"Study the miss")}</p><p className="mt-2 leading-6">{localize(q.explanation,locale)}</p><button onClick={next} className="wine-button mt-5">{index+1===questions.length?(locale==="de"?"Auswertung":"Results"):(locale==="de"?"Nächste Aufgabe":"Next prompt")}<ArrowRight className="h-4 w-4"/></button></div>}
 </div></>;
}
function aromaFamily(aroma:string){
 return aromaWheelFamily(aroma);
}
function AromaAtelierGame(props:PlayProps){
 const {locale}=useT();const count=ROUND_COUNTS[props.difficulty];
 const rounds=useMemo(()=>shuffle(GRAPES.filter(g=>g.aromas.length>=3),props.seed).slice(0,count),[props.seed,count]);
 const [index,setIndex]=useState(0),[selected,setSelected]=useState<string[]>([]),[activeFamily,setActiveFamily]=useState<string|null>(null),[revealed,setRevealed]=useState(false),[score,setScore]=useState(0),[correct,setCorrect]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());
 const finish=useFinish(props),encounter=useWineDex(s=>s.encounter),target=rounds[index];
 const tokens=useMemo(()=>shuffle([...target.aromas.slice(0,3),...GRAPES.filter(g=>g.id!==target.id).flatMap(g=>g.aromas).filter(a=>!target.aromas.includes(a)).slice(0,5)],props.seed+index),[target,props.seed,index]);
 const hits=selected.filter(a=>target.aromas.includes(a)).length;
 const submit=()=>{if(selected.length!==3)return;setRevealed(true);if(hits===3){setCorrect(x=>x+1);setScore(x=>x+300)}if(!props.practice)encounter(target.id,"grape",props.gameId,hits===3)};
 const next=()=>{const nextScore=score,nextCorrect=correct;if(index+1===rounds.length){finish(nextScore,nextCorrect,rounds.length,nextCorrect,start);setDone(true)}else{setIndex(x=>x+1);setSelected([]);setActiveFamily(null);setRevealed(false)}};
 if(done)return <Result {...props} score={score} correct={correct} total={rounds.length} onReplay={props.onReplay}/>;
 return <><PlayHeader gameId={props.gameId} round={index+1} total={rounds.length} score={score} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-4xl px-4 py-7">
  <div className="text-center"><p className="wine-kicker">{locale==="de"?"Wähle drei häufig verbundene Aromen":"Choose three commonly associated aromas"}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{target.name}</h1><p className="mt-2 text-sm text-[var(--wine-muted)]">{localize(target.climate,locale)} · {localize(target.structure,locale)}</p></div>
  <div className="wine-aroma-wheel-stage mt-6">
   <div className="wine-aroma-wheel" aria-label={locale==="de"?"Aromenrad mit sechs Familien":"Aroma wheel with six families"}>
    {AROMA_WHEEL_FAMILIES.map((family,i)=><button type="button" key={family.id} disabled={revealed} aria-pressed={activeFamily===family.id} onClick={()=>setActiveFamily(value=>value===family.id?null:family.id)} className={`wine-wheel-family wheel-${i} ${activeFamily===family.id?"is-active":""}`}><b>{localize(family.label,locale)}</b><span>{selected.filter(a=>aromaFamily(a)===family.id).join(" · ")||"—"}</span></button>)}
    <div className="wine-wheel-core"><span>{target.name}</span><small>{selected.length}/3</small></div>
   </div>
   <div className="wine-wheel-legend">{AROMA_WHEEL_FAMILIES.map(f=><span key={f.id} className={`family-${f.id}`}>{localize(f.label,locale)}</span>)}</div>
  </div>
  <p className="mt-6 text-center text-xs text-[var(--wine-muted)]">{activeFamily?(locale==="de"?`Aromen aus „${localize(AROMA_WHEEL_FAMILIES.find(f=>f.id===activeFamily)!.label,locale)}“ – Segment erneut wählen, um alle zu sehen.`:`Aromas from “${localize(AROMA_WHEEL_FAMILIES.find(f=>f.id===activeFamily)!.label,locale)}” — select the segment again to show all.`):(locale==="de"?"Wähle ein Segment des Rads oder direkt drei Aromenkarten.":"Choose a wheel segment, then build a three-aroma profile.")}</p>
  <div className="mt-4 flex min-h-24 flex-wrap content-start justify-center gap-2">{tokens.filter(a=>!activeFamily||aromaFamily(a)===activeFamily||selected.includes(a)).map(a=>{const chosen=selected.includes(a),isCorrect=target.aromas.includes(a);return <button key={a} disabled={revealed} onClick={()=>setSelected(s=>chosen?s.filter(x=>x!==a):s.length<3?[...s,a]:s)} className={`wine-aroma-token family-${aromaFamily(a)} ${chosen?"is-selected":""} ${revealed&&chosen&&isCorrect?"is-correct":""} ${revealed&&chosen&&!isCorrect?"is-wrong":""}`}>{a}</button>})}</div>
  {!revealed?<button disabled={selected.length!==3} onClick={submit} className="wine-button mx-auto mt-7 flex">{locale==="de"?"Aromen prüfen":"Check aromas"}</button>:<div className="wine-reveal"><p className="font-bold">{hits===3?(locale==="de"?"Das Profil sitzt.":"The profile holds together."):(locale==="de"?`${hits}/3 passen typischerweise.`:`${hits}/3 are commonly associated.`)}</p><p className="mt-2 text-sm text-[var(--wine-muted)]">{locale==="de"?"Assoziationen sind kontextabhängig – Herkunft, Reife und Ausbau verändern das Bild.":"Associations remain contextual: origin, ripeness and winemaking all shift the picture."}</p><button onClick={next} className="wine-button mt-4">{locale==="de"?"Weiter":"Continue"}<ArrowRight className="h-4 w-4"/></button></div>}
 </div></>;
}
function PairingDuelGame(props:PlayProps){
 const {locale}=useT();const roundCount=props.difficulty==="easy"?3:props.difficulty==="medium"?5:7;
 const rounds=useMemo(()=>shuffle([...PAIRINGS],props.seed).slice(0,roundCount),[props.seed,roundCount]);
 const [index,setIndex]=useState(0),[phase,setPhase]=useState<0|1|2>(0),[selected,setSelected]=useState<string|null>(null),[score,setScore]=useState(0),[correct,setCorrect]=useState(0),[streak,setStreak]=useState(0),[best,setBest]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());
 const finish=useFinish(props),encounter=useWineDex(s=>s.encounter),pairing=rounds[index];
 const principles=useMemo(()=>Array.from(new Map(PAIRINGS.map(p=>[p.principleId,{id:p.principleId,label:p.principle}])).values()),[]);
 const principleChoices=useMemo(()=>shuffle([{id:pairing.principleId,label:pairing.principle},...shuffle(principles.filter(p=>p.id!==pairing.principleId),props.seed+index).slice(0,2)],props.seed+index+41),[pairing,principles,props.seed,index]);
 const answer=phase===0?pairing.answer:phase===1?pairing.principleId:pairing.modifierAnswer;
 const choices=phase===1?principleChoices:[{id:"a",label:pairing.a},{id:"b",label:pairing.b}];
 const explanation=phase===0?pairing.why:phase===1?pairing.principle:pairing.modifierWhy;
 const choose=(id:string)=>{if(selected)return;setSelected(id);const ok=id===answer,nextStreak=ok?streak+1:0;if(ok){setCorrect(value=>value+1);setScore(value=>value+200+Math.min(100,nextStreak*15));setBest(value=>Math.max(value,nextStreak))}setStreak(nextStreak)};
 const proceed=()=>{if(phase<2){setPhase(value=>(value+1) as 0|1|2);setSelected(null);return}if(!props.practice)encounter(pairing.id,"style",props.gameId,selected===answer);if(index+1===rounds.length){finish(score,correct,rounds.length*3,best,start);setDone(true)}else{setIndex(value=>value+1);setPhase(0);setSelected(null)}};
 if(done)return <Result {...props} score={score} correct={correct} total={rounds.length*3} onReplay={props.onReplay}/>;
 const prompt=phase===0?(locale==="de"?"Wähle das stärkere Ausgangspairing.":"Choose the stronger opening pairing."):phase===1?(locale==="de"?"Welches Prinzip trägt deine Wahl?":"Which principle supports your choice?"):(locale==="de"?"Der Pass ändert sich – entscheide neu.":"The pass changes — decide again.");
 return <><PlayHeader gameId={props.gameId} round={index*3+phase+1} total={rounds.length*3} score={score} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-4xl px-4 py-7"><WineRunHud score={score} streak={streak}/><div className="mt-6 text-center"><p className="wine-kicker">{locale==="de"?`Gang ${index+1} · Phase ${phase+1}/3`:`Course ${index+1} · phase ${phase+1}/3`}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{prompt}</h1>{phase===2&&<p className="wine-pairing-modifier mt-4">{localize(pairing.modifier,locale)}</p>}</div><PairingDuelScene pairing={pairing} locale={locale} selected={phase===1?null:selected}/><div className={`mt-6 grid gap-3 ${phase===1?"sm:grid-cols-3":"sm:grid-cols-2 wine-duel-choices"}`}>{choices.map((choice,i)=>{const revealed=selected!==null,ok=choice.id===answer,chosen=choice.id===selected;return <button type="button" key={choice.id} disabled={revealed} onClick={()=>choose(choice.id)} className={`${phase===1?"wine-answer":"wine-duel-challenger"} ${revealed&&ok?"is-correct":""} ${revealed&&chosen&&!ok?"is-wrong":""}`}><span>{phase!==1&&<b>{i?"B":"A"}</b>}{localize(choice.label,locale)}</span>{revealed&&ok&&<Check className="h-5 w-5"/>}{revealed&&chosen&&!ok&&<X className="h-5 w-5"/>}</button>})}</div>{selected&&<div className="wine-reveal" aria-live="polite"><p className="wine-kicker">{selected===answer?(locale==="de"?"Punkt für den Pass":"Point to the pass"):(locale==="de"?"Balance kippt":"Balance shifts")}</p><p className="mt-2 leading-6">{localize(explanation,locale)}</p><button onClick={proceed} className="wine-button mt-4">{phase===2?(index+1===rounds.length?(locale==="de"?"Auswertung":"Results"):(locale==="de"?"Nächster Gang":"Next course")):(locale==="de"?"Nächste Phase":"Next phase")}<ArrowRight className="h-4 w-4"/></button></div>}</div></>;
}
function LabelDecoderGame(props:PlayProps){
 const {locale}=useT();const count=ROUND_COUNTS[props.difficulty];const rounds=useMemo(()=>shuffle(APPELLATIONS,props.seed).slice(0,count),[props.seed,count]);const [index,setIndex]=useState(0),[selected,setSelected]=useState<string|null>(null),[score,setScore]=useState(0),[correct,setCorrect]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props),encounter=useWineDex(s=>s.encounter),a=rounds[index],region=REGIONS.find(r=>r.id===a.regionId)!;
 const mode=index%3;const pool=mode===0?APPELLATIONS.map(x=>({id:x.id,label:localize(x.style,locale)})):mode===1?APPELLATIONS.map(x=>({id:x.id,label:localize(x.level,locale)})):REGIONS.map(x=>({id:x.id,label:localize(x.country,locale)}));const answer=mode===2?region.id:a.id,answerLabel=mode===0?localize(a.style,locale):mode===1?localize(a.level,locale):localize(region.country,locale);const uniqueDecoys=Array.from(new Map(pool.filter(x=>x.id!==answer&&x.label!==answerLabel).map(x=>[x.label,x])).values());const choices=useMemo(()=>shuffle([{id:answer,label:answerLabel},...shuffle(uniqueDecoys,props.seed+index+11).slice(0,3)],props.seed+index),[answer,answerLabel,uniqueDecoys,props.seed,index]);
 const choose=(id:string)=>{if(selected)return;setSelected(id);const ok=id===answer;if(ok){setCorrect(x=>x+1);setScore(x=>x+250)}if(!props.practice)encounter(a.id,"appellation",props.gameId,ok)};
 const next=()=>{if(index+1===rounds.length){finish(score,correct,rounds.length,correct,start);setDone(true)}else{setIndex(x=>x+1);setSelected(null)}};
 if(done)return <Result {...props} score={score} correct={correct} total={rounds.length} onReplay={props.onReplay}/>;
 const question=mode===0?(locale==="de"?"Welchen Stil deutet die Appellation an?":"What style does the appellation suggest?"):mode===1?(locale==="de"?"Welche Art Herkunftsbegriff ist markiert?":"What kind of origin term is highlighted?"):(locale==="de"?"Welches Herkunftsland gehört dazu?":"Which country of origin belongs here?");
 return <><PlayHeader gameId={props.gameId} round={index+1} total={rounds.length} score={score} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-4xl px-4 py-7">
  <p className="wine-kicker text-center">{locale==="de"?"Fiktives Etikett · keine Handelsmarke":"Synthetic label · no commercial trademark"}</p><h1 className="mt-2 text-center text-2xl font-black text-[var(--wine-cream)]">{question}</h1>
  <div className="wine-label-workbench mt-6"><div className="wine-bottle"><div className="wine-bottle-neck"/><div className="wine-bottle-body"><div className="wine-paper-label"><span className="wine-label-producer">NORTH LANTERN ESTATE</span><strong className={`wine-label-field ${mode===0?"is-hot":""}`}>{a.name}</strong><span aria-label={mode===1&&!selected?(locale==="de"?"Verdeckter Herkunftsbegriff":"Hidden origin term"):undefined} className={`wine-label-field ${mode===1?"is-hot":""} ${mode===1&&!selected?"is-redacted":""}`}>{mode===1&&!selected?"REVEAL BY INFERENCE":localize(a.level,locale)}</span><span aria-label={mode===2&&!selected?(locale==="de"?"Verdecktes Herkunftsland":"Hidden origin country"):undefined} className={`wine-label-field ${mode===2?"is-hot":""} ${mode===2&&!selected?"is-redacted":""}`}>{mode===2&&!selected?"ORIGIN SEALED":localize(region.country,locale)}</span><b>2022</b></div></div></div>
   {selected&&<div className="wine-label-callouts"><p><span>01</span>{a.name} → {localize(region.name,locale)}</p><p><span>02</span>{localize(a.level,locale)}</p><p><span>03</span>{localize(region.country,locale)}</p><p><span>04</span>{localize(a.style,locale)}</p></div>}
  </div>
  <div className="mt-6 grid gap-2 sm:grid-cols-2">{choices.map(c=><button key={c.id} disabled={!!selected} onClick={()=>choose(c.id)} className={`wine-answer ${selected&&c.id===answer?"is-correct":""} ${selected===c.id&&c.id!==answer?"is-wrong":""}`}>{c.label}</button>)}</div>
  {selected&&<div className="wine-reveal"><p>{locale==="de"?`${a.name} sitzt in ${localize(region.name,locale)} und steht hier für ${localize(a.style,locale)}.`:`${a.name} sits within ${localize(region.name,locale)} and here signals ${localize(a.style,locale)}.`}</p><button onClick={next} className="wine-button mt-4">{locale==="de"?"Nächstes Etikett":"Next label"}<ArrowRight className="h-4 w-4"/></button></div>}
 </div></>;
}
function MapGame(props:PlayProps){
 const {locale}=useT();const regions=useMemo(()=>shuffle(REGIONS,props.seed).slice(0,ROUND_COUNTS[props.difficulty]),[props.seed,props.difficulty]);const [i,setI]=useState(0),[pin,setPin]=useState<[number,number]|null>(null),[confirmed,setConfirmed]=useState(false),[resetSignal,setResetSignal]=useState(0),[score,setScore]=useState(0),[correct,setCorrect]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props),encounter=useWineDex(s=>s.encounter),target=regions[i];const result=confirmed&&pin?scoreMapClick(pin[1],pin[0],target):null;
 const next=()=>{if(result){setScore(x=>x+result.score);if(result.correct)setCorrect(x=>x+1);if(!props.practice)encounter(target.id,"region",props.gameId,result.correct)}if(i+1===regions.length){finish(score+(result?.score??0),correct+(result?.correct?1:0),regions.length,0,start);setDone(true)}else{setI(x=>x+1);setPin(null);setConfirmed(false);setResetSignal(x=>x+1)}};
 if(done)return <Result {...props} score={score} correct={correct} total={regions.length} onReplay={props.onReplay}/>;
 return <><PlayHeader gameId={props.gameId} round={i+1} total={regions.length} score={score} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="wine-kicker">{locale==="de"?"Atlas-Aufgabe":"Atlas assignment"}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{localize(target.name,locale)} · {localize(target.country,locale)}</h1></div><button type="button" onClick={()=>setResetSignal(x=>x+1)} className="wine-button wine-button-quiet"><LocateFixed className="h-4 w-4"/>{locale==="de"?"Weltansicht":"World view"}</button></div>
  <p className="mt-3 text-xs leading-5 text-[var(--wine-muted)]">{locale==="de"?"Ziehen oder mit zwei Fingern bewegen · Mausrad/Pinch und +/− zum Zoomen · kurz tippen, um den Pin zu setzen oder zu versetzen.":"Drag or use two fingers to move · wheel/pinch and +/− to zoom · briefly tap to place or reposition your pin."}</p>
  <div className="wine-real-map relative mt-4 h-[420px] overflow-hidden border border-[var(--wine-line)] sm:h-[520px]"><PinMap onPin={(lng,lat)=>{if(!confirmed)setPin([lng,lat])}} userPin={pin} target={confirmed?[target.lng,target.lat]:null} locked={confirmed} resetSignal={resetSignal} initialScale={1}/><Compass/></div>
  {!confirmed?<div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-[var(--wine-muted)]">{pin?(locale==="de"?"Pin gesetzt — du kannst ihn noch versetzen.":"Pin placed — you can still reposition it."):(locale==="de"?"Setze zuerst einen Pin auf die echte Weltkarte.":"Place a pin on the real world map first.")}</p><button type="button" disabled={!pin} onClick={()=>setConfirmed(true)} className="wine-button">{locale==="de"?"Pin bestätigen":"Lock in pin"}<Check className="h-4 w-4"/></button></div>:result&&<div className="wine-reveal"><div className="flex flex-wrap items-baseline gap-x-4 gap-y-1"><p className="text-2xl font-black">{Math.round(result.distance).toLocaleString(locale)} km</p><b className="font-mono text-[var(--wine-copper)]">+{result.score}</b></div><p className="mt-2 text-[var(--wine-muted)]">{localize(target.climate,locale)} · {target.grapes.map(id=>GRAPES.find(g=>g.id===id)?.name).join(", ")}</p><button className="wine-button mt-5" onClick={next}>{locale==="de"?"Weiter":"Continue"}<ArrowRight className="h-4 w-4"/></button></div>}
 </div></>;
}
function CellarBuilder(props:PlayProps){
 const {locale}=useT();const brief=CELLAR_BRIEFS[props.seed%CELLAR_BRIEFS.length];const [selected,setSelected]=useState<string[]>([]),[feedback,setFeedback]=useState<string|null>(null),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props);const cost=CELLAR_BOTTLES.filter(b=>selected.includes(b.id)).reduce((s,b)=>s+b.price,0);const covered=new Set(CELLAR_BOTTLES.filter(b=>selected.includes(b.id)).map(b=>b.category));const missing=brief.needs.filter(n=>!covered.has(n));const valid=cost<=brief.budget&&missing.length===0;
 const roles=[{id:"sparkling",label:locale==="de"?"Aperitif":"Aperitif",accept:["sparkling"]},{id:"crisp-white",label:locale==="de"?"Frischer Weißwein":"Crisp white",accept:["white"]},{id:"textural-white",label:locale==="de"?"Texturierter Weißwein":"Textural white",accept:["white"]},{id:"light-red",label:locale==="de"?"Leichter Rotwein":"Light red",accept:["red","rosé"]},{id:"structured-red",label:locale==="de"?"Strukturierter Rotwein":"Structured red",accept:["red"]},{id:"sweet",label:locale==="de"?"Süß / Fortified":"Sweet / fortified",accept:["sweet","fortified"]}];const rack=roles.map((role,i)=>({role,bottle:CELLAR_BOTTLES.filter(b=>selected.includes(b.id)&&role.accept.includes(b.category))[i===2||i===4?1:0]}));
 const submit=()=>{if(!selected.length)return;if(cost>brief.budget){setFeedback(locale==="de"?`Noch €${cost-brief.budget} über Budget. Entferne oder tausche eine Flasche.`:`€${cost-brief.budget} over budget. Remove or swap a bottle.`);return}if(missing.length){setFeedback(locale==="de"?`Noch offen: ${missing.join(", ")}.`:`Still missing: ${missing.join(", ")}.`);return}setFeedback(locale==="de"?"Starke Abdeckung: Budget und Pflichtrollen stimmen.":"Strong coverage: budget and required roles are balanced.");finish(1000,1,1,0,start);setDone(true)};
 if(done)return <Result {...props} score={valid?1000:400} correct={valid?1:0} total={1} onReplay={props.onReplay}/>;
 return <><PlayHeader gameId={props.gameId} round={1} total={1} score={Math.max(0,1000-cost*3)} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="wine-kicker">{localize(brief.title,locale)}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{locale==="de"?`Baue einen Keller unter €${brief.budget}`:`Build a cellar under €${brief.budget}`}</h1></div><div className="wine-budget"><span>€{cost}</span><small>/ €{brief.budget}</small><div><i style={{width:`${Math.min(100,cost/brief.budget*100)}%`}} className={cost>brief.budget?"is-over":""}/></div></div></div>
  <div className="mt-5 flex flex-wrap gap-2">{brief.needs.map(n=><span key={n} className={`wine-coverage ${covered.has(n)?"is-covered":""}`}><i/>{n}</span>)}</div>
  <div className="wine-cellar-rack mt-7">{rack.map(({role,bottle})=><div key={role.id} className={`wine-rack-slot ${bottle?"is-filled":""}`}><span className="wine-rack-role">{role.label}</span>{bottle?<button aria-label={`${bottle.name} entfernen`} onClick={()=>{setSelected(s=>s.filter(x=>x!==bottle.id));setFeedback(null)}} className="wine-rack-bottle"><i/><b>{bottle.name}</b><small>€{bottle.price}</small></button>:<span className="wine-rack-empty">+</span>}</div>)}</div>
  <p className="wine-kicker mt-8">{locale==="de"?"Flaschenbank · tippen zum Einlagern":"Bottle bank · tap to rack"}</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{CELLAR_BOTTLES.map(b=><button key={b.id} onClick={()=>{setSelected(s=>s.includes(b.id)?s.filter(x=>x!==b.id):[...s,b.id]);setFeedback(null)}} className={`wine-bottle-card ${selected.includes(b.id)?"is-selected":""}`}><i className={`wine-mini-bottle bottle-${b.category}`}/><span><b>{b.name}</b><small>{b.category} · €{b.price}</small></span></button>)}</div>
  <div className="wine-reveal flex flex-wrap items-center justify-between gap-4">{feedback?<p className={valid?"text-[var(--wine-vine)]":"text-[var(--wine-muted)]"}>{feedback}</p>:<p className="text-[var(--wine-muted)]">{locale==="de"?"Decke alle Lichter ab, ohne das Budget zu sprengen.":"Light every required category without breaking budget."}</p>}<button disabled={!selected.length} onClick={submit} className="wine-button">{locale==="de"?"Keller bewerten":"Evaluate cellar"}</button></div>
 </div></>;
}
function ConnectionsGame(props:PlayProps){
 const {locale}=useT();const groups=useMemo(()=>[
  {id:"bordeaux",items:[locale==="de"?"Frankreich":"France","Cabernet Sauvignon","maritime","Pauillac"]},
  {id:"rioja",items:[locale==="de"?"Spanien":"Spain","Tempranillo","Atlantic influence","Rioja Alta"]},
  {id:"barossa",items:[locale==="de"?"Australien":"Australia","Shiraz","warm Mediterranean","Barossa GI"]},
  {id:"mosel",items:[locale==="de"?"Deutschland":"Germany","Riesling","steep slate slopes","Mosel"]},
 ],[locale]);const items=useMemo(()=>shuffle(groups.flatMap(g=>g.items.map((label,i)=>({id:`${g.id}-${i}`,group:g.id,label}))),props.seed+2),[groups,props.seed]);const [selected,setSelected]=useState<string[]>([]),[solved,setSolved]=useState<string[]>([]),[mistakes,setMistakes]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props);
 const submit=()=>{const picked=items.filter(x=>selected.includes(x.id));if(picked.length===4&&new Set(picked.map(x=>x.group)).size===1){const next=[...solved,picked[0].group];setSolved(next);setSelected([]);if(next.length===4){finish(Math.max(200,1000-mistakes*100),4,4,4,start);setDone(true)}}else{setMistakes(x=>x+1);setSelected([])}};
 if(done)return <Result {...props} score={Math.max(200,1000-mistakes*100)} correct={4} total={4} onReplay={props.onReplay}/>;
 return <><PlayHeader gameId={props.gameId} round={solved.length+1} total={4} score={solved.length*250-mistakes*25} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-3xl px-4 py-8"><h1 className="text-3xl font-black text-[var(--wine-cream)]">{locale==="de"?"Finde vier Begriffe mit einer gemeinsamen Wein-Verbindung.":"Find four terms with one wine connection."}</h1><div className="mt-7 grid grid-cols-2 gap-2 sm:grid-cols-4">{items.filter(x=>!solved.includes(x.group)).map(x=><button key={x.id} onClick={()=>setSelected(s=>s.includes(x.id)?s.filter(id=>id!==x.id):s.length<4?[...s,x.id]:s)} className={`wine-tile ${selected.includes(x.id)?"is-selected":""}`}>{x.label}</button>)}</div><button disabled={selected.length!==4} onClick={submit} className="wine-button mt-6">{locale==="de"?"Gruppe prüfen":"Check group"}</button>{mistakes>0&&<p className="mt-3 text-sm text-[var(--wine-muted)]">{mistakes} {locale==="de"?"Fehlversuche":"misses"}</p>}</div></>;
}
function LadderGame(props:PlayProps){
 const {locale}=useT();const chain=useMemo(()=>{const a=APPELLATIONS[props.seed%APPELLATIONS.length],r=REGIONS.find(x=>x.id===a.regionId)!;return {a,r,levels:[{key:"country",label:locale==="de"?"Land":"Country",answer:localize(r.country,locale),pool:[...new Set(REGIONS.map(x=>localize(x.country,locale)))]},{key:"region",label:locale==="de"?"Region":"Region",answer:localize(r.name,locale),pool:REGIONS.map(x=>localize(x.name,locale))},{key:"appellation",label:"Appellation",answer:a.name,pool:APPELLATIONS.map(x=>x.name)},{key:"style",label:locale==="de"?"Typischer Stil":"Typical style",answer:localize(a.style,locale),pool:APPELLATIONS.map(x=>localize(x.style,locale))}].map((x,i)=>({...x,options:shuffle([x.answer,...shuffle([...new Set(x.pool.filter(v=>v!==x.answer))],props.seed+i).slice(0,3)],props.seed+i+9)}))}},[props.seed,locale]);const [step,setStep]=useState(0),[score,setScore]=useState(0),[correct,setCorrect]=useState(0),[complete,setComplete]=useState(false),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props),current=chain.levels[Math.min(step,3)];const answer=(v:string)=>{const ok=v===current.answer;setScore(s=>s+(ok?250:0));if(ok)setCorrect(c=>c+1);if(step===3){setStep(4);setComplete(true)}else setStep(x=>x+1)};const finalize=()=>{finish(score,correct,4,correct,start);setDone(true)};
 if(done)return <Result {...props} score={score} correct={Math.round(score/250)} total={4} onReplay={props.onReplay}/>;
 const revealed=step>=2;
 return <><PlayHeader gameId={props.gameId} round={Math.min(step+1,4)} total={4} score={score} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-7"><p className="wine-kicker">{locale==="de"?"Regionaler Locator · Marker zeigt den Regionenzentroid, keine Appellationsgrenze":"Regional locator · marker shows the region centroid, not an appellation boundary"}</p><div className="mt-5 grid gap-6 lg:grid-cols-[310px_1fr]">
  <ol className="wine-appellation-ladder">{chain.levels.map((level,i)=><li key={level.key} className={`${i<step?"is-locked":""} ${i===step?"is-current":""}`}><span>{String(i+1).padStart(2,"0")}</span><div><small>{level.label}</small><b>{i<step?level.answer:i===step?(locale==="de"?"Jetzt lösen":"Solve now"):"••••••"}</b></div>{i<step&&<Check className="h-5 w-5"/>}</li>)}</ol>
  <section><div className="wine-ladder-map relative h-[260px] overflow-hidden border border-[var(--wine-line)] sm:h-[320px]"><PinMap onPin={()=>undefined} locked target={revealed?[chain.r.lng,chain.r.lat]:null} focus={revealed?[chain.r.lng,chain.r.lat]:null} focusZoom={revealed?3:1} initialScale={1} controls={false}/><Compass/></div>
   {!complete?<><h1 className="mt-5 text-3xl font-black text-[var(--wine-cream)]">{current.label}</h1><div className="mt-4 grid gap-2 sm:grid-cols-2">{current.options.map(o=><button key={o} onClick={()=>answer(o)} className="wine-answer">{o}<ArrowRight className="h-4 w-4"/></button>)}</div></>:<div className="wine-reveal"><p className="wine-kicker">{locale==="de"?"Hierarchie vollständig":"Hierarchy complete"}</p><p className="mt-2 font-bold">{chain.levels.map(x=>x.answer).join(" → ")}</p><button onClick={finalize} className="wine-button mt-4">{locale==="de"?"Kellerpass stempeln":"Stamp passport"}<Check className="h-4 w-4"/></button></div>}
  </section></div>
 </div></>;
}
function DilemmaGame(props:PlayProps){
 const {locale}=useT();const scenario=VINTAGE_SCENARIOS[props.seed%VINTAGE_SCENARIOS.length];const [step,setStep]=useState(0),[profile,setProfile]=useState({...scenario.initial}),[pending,setPending]=useState<(typeof scenario.stages)[number]["choices"][number]|null>(null),[riskCost,setRiskCost]=useState(0),[finalScore,setFinalScore]=useState(0),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props),stage=scenario.stages[step];const clamp=(n:number)=>Math.max(0,Math.min(5,n));
 const choose=(choice:typeof stage.choices[number])=>{if(pending)return;const next=Object.fromEntries(Object.entries(profile).map(([key,value])=>[key,clamp(value+choice.delta[key as keyof typeof choice.delta])])) as typeof profile;setProfile(next);setRiskCost(value=>value+Math.max(0,choice.delta.pressure));setPending(choice)};
 const proceed=()=>{if(!pending)return;if(step===scenario.stages.length-1){const score=objectiveScore(profile,scenario.target,riskCost);setFinalScore(score);finish(score,score>=700?4:score>=500?3:2,4,0,start);setDone(true)}else{setStep(value=>value+1);setPending(null)}};
 if(done)return <Result {...props} score={finalScore} correct={finalScore>=700?4:3} total={4} onReplay={props.onReplay} note={locale==="de"?"Das Profil bewertet die Nähe zu deinem erklärten Stilziel – nicht einen angeblich perfekten Jahrgang.":"The profile scores alignment with the stated style objective, not a supposedly perfect vintage."} profile={profile}/>;
 const liveScore=objectiveScore(profile,scenario.target,riskCost);
 return <><PlayHeader gameId={props.gameId} round={step+1} total={4} score={liveScore} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-7">
  <p className="wine-kicker">{localize(scenario.title,locale)} · {localize(scenario.objective,locale)}</p><div className="wine-vintage-timeline mt-5">{scenario.stages.map((s,i)=><div key={s.id} className={`wine-vintage-stage ${i<step?"is-past":""} ${i===step?"is-current":""}`}><i/>{localize(s.label,locale)}</div>)}</div>
  <div className={`wine-vintage-scene season-${step}`}><span className="weather-mark">{step===0?"❄":step===1?"≋":step===2?"☀":"◒"}</span><div className="vine-line"/><p>{localize(stage.weather,locale)}</p></div>
  <div className="mt-6 grid gap-7 lg:grid-cols-[1fr_300px]"><section><p className="wine-kicker">{locale==="de"?"Fiktives Szenario · Entscheidung mit Trade-offs":"Fictional scenario · a decision with trade-offs"}</p><h1 className="mt-3 text-3xl font-black text-[var(--wine-cream)]">{localize(scenario.brief,locale)}</h1><div className="mt-6 grid gap-3">{stage.choices.map(c=><button key={c.id} disabled={!!pending} onClick={()=>choose(c)} className={`wine-decision-card ${pending?.id===c.id?"is-selected":""}`}><span className="wine-decision-weather">{c.id==="early"?"☀︎":c.id==="later"?"◒":"↔"}</span><span><b>{localize(c.label,locale)}</b><small>{locale==="de"?"Entscheidung festlegen":"Commit decision"}</small></span><ArrowRight className="h-5 w-5 shrink-0"/></button>)}</div>{pending&&<div className="wine-reveal is-success" aria-live="polite"><p className="wine-kicker">{locale==="de"?"Sofortige Folge":"Immediate consequence"}</p><p className="mt-2 leading-6">{localize(pending.effect,locale)}</p><div className="mt-3 flex flex-wrap gap-2">{Object.entries(pending.delta).filter(([,value])=>value!==0).map(([key,value])=><span className="wine-delta-chip" key={key}>{key} {value>0?"+":""}{value}</span>)}</div><button onClick={proceed} className="wine-button mt-4">{step===scenario.stages.length-1?(locale==="de"?"Jahrgang bewerten":"Score vintage"):(locale==="de"?"Nächste Saisonphase":"Next season stage")}<ArrowRight className="h-4 w-4"/></button></div>}</section>
  <aside className="wine-profile-panel"><div className="flex items-center justify-between gap-3"><p className="wine-kicker">{locale==="de"?"Ist / Ziel":"Current / target"}</p><b className="font-mono text-[var(--wine-copper)]">{liveScore}</b></div>{Object.entries(profile).map(([key,value])=><div key={key} className="wine-target-meter"><ProfileMeter label={key} value={value}/><small>{locale==="de"?"Ziel":"Target"} {scenario.target[key as keyof typeof scenario.target]}/5</small></div>)}<p className="mt-4 text-xs text-[var(--wine-muted)]">{locale==="de"?`Kumulatives Risikogewicht: ${riskCost}`:`Cumulative risk weight: ${riskCost}`}</p></aside></div>
 </div></>;
}
function SameGrapeGame(props:PlayProps){
 const {locale}=useT();const pair=SAME_GRAPE_PAIRS[props.seed%SAME_GRAPE_PAIRS.length],grape=GRAPES.find(g=>g.id===pair.grapeId)!,a=REGIONS.find(r=>r.id===pair.regionAId)!,b=REGIONS.find(r=>r.id===pair.regionBId)!;const [assigned,setAssigned]=useState<Record<string,"a"|"b">>({}),[reviewed,setReviewed]=useState(false),[done,setDone]=useState(false),[finalCorrect,setFinalCorrect]=useState(0),[start]=useState(Date.now());const finish=useFinish(props);const submit=()=>{const correct=pair.tendencies.filter(t=>assigned[t.id]===t.target).length;setFinalCorrect(correct);setReviewed(true)};const finalize=()=>{finish(finalCorrect*250,finalCorrect,4,finalCorrect,start);setDone(true)};
 if(done)return <Result {...props} score={finalCorrect*250} correct={finalCorrect} total={4} onReplay={props.onReplay}/>;
 const panel=(region:typeof a,side:"a"|"b")=><article className="wine-region-world"><div className="wine-mini-region-map relative h-[170px] overflow-hidden"><PinMap onPin={()=>undefined} locked target={[region.lng,region.lat]} focus={[region.lng,region.lat]} focusZoom={2.2} initialScale={1} controls={false}/><Compass/></div><p className="wine-kicker mt-3">{localize(region.country,locale)} · {region.lat>=0?(locale==="de"?"Nordhalbkugel":"Northern hemisphere"):(locale==="de"?"Südhalbkugel":"Southern hemisphere")}</p><h2>{localize(region.name,locale)}</h2><p>{localize(region.climate,locale)}</p>{reviewed&&<div className="wine-region-profile">{pair.tendencies.filter(t=>t.target===side).map(t=><span key={t.id}>{localize(t.label,locale)}</span>)}</div>}</article>;
 return <><PlayHeader gameId={props.gameId} round={Object.keys(assigned).length} total={4} score={reviewed?finalCorrect*250:Object.keys(assigned).length*150} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-7"><div className="text-center"><p className="wine-kicker">{locale==="de"?"Eine Rebe · zwei reale Regionen":"One grape · two real regions"}</p><h1 className="mt-2 text-4xl font-black text-[var(--wine-cream)]">{grape.name}</h1></div><div className={`wine-split-world mt-6 ${reviewed?"is-connected":""}`}>{panel(a,"a")}<div className="wine-grape-bridge"><span>{grape.name}</span><i/></div>{panel(b,"b")}</div>
  {!reviewed?<><div className="mt-7 space-y-3">{pair.tendencies.map(t=><div key={t.id} className="wine-assign"><span>{localize(t.label,locale)}</span><div className="flex gap-2"><button aria-pressed={assigned[t.id]==="a"} onClick={()=>setAssigned(x=>({...x,[t.id]:"a"}))} className={`wine-mini ${assigned[t.id]==="a"?"is-selected":""}`}>{localize(a.name,locale)}</button><button aria-pressed={assigned[t.id]==="b"} onClick={()=>setAssigned(x=>({...x,[t.id]:"b"}))} className={`wine-mini ${assigned[t.id]==="b"?"is-selected":""}`}>{localize(b.name,locale)}</button></div></div>)}</div><button disabled={Object.keys(assigned).length<4} onClick={submit} className="wine-button mt-6">{locale==="de"?"Vergleich prüfen":"Review comparison"}</button></>:<div className="wine-reveal"><p className="font-bold">{finalCorrect}/4 {locale==="de"?"Tendenzen stimmig zugeordnet":"tendencies defensibly assigned"}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{pair.tendencies.map(t=><p key={t.id} className="text-sm"><b>{localize(t.label,locale)}:</b> {localize(t.rationale,locale)}</p>)}</div><p className="mt-3 text-xs text-[var(--wine-muted)]">{locale==="de"?"Dies sind begründete Tendenzen, keine Garantien für jede Flasche.":"These are defensible tendencies, not guarantees for every bottle."}</p><button onClick={finalize} className="wine-button mt-4">{locale==="de"?"Profil speichern":"Save profile"}<Check className="h-4 w-4"/></button></div>}
 </div></>;
}
function MysteryGame(props:PlayProps){
 const {locale}=useT();const answer=GRAPES[props.seed%GRAPES.length];const options=useMemo(()=>shuffle([answer,...GRAPES.filter(g=>g.id!==answer.id).slice(0,4)],props.seed),[answer,props.seed]);const clues=[answer.climate,answer.clue,{en:`Structure: ${answer.structure.en}`,de:`Struktur: ${answer.structure.de}`}];const [shown,setShown]=useState(1),[wrong,setWrong]=useState<string|null>(null),[done,setDone]=useState(false),[score,setScore]=useState(0),[start]=useState(Date.now());const finish=useFinish(props);const decoys=options.filter(o=>o.id!==answer.id);const eliminated=new Set(decoys.slice(0,Math.min(decoys.length,Math.ceil(shown*decoys.length/3))).map(x=>x.id));const choose=(id:string)=>{if(eliminated.has(id))return;const ok=id===answer.id;if(!ok){setWrong(id);return}const s=Math.max(300,1000-(shown-1)*200);setScore(s);finish(s,1,1,0,start);setDone(true)};
 if(done)return <Result {...props} score={score} correct={score?1:0} total={1} onReplay={props.onReplay} note={localize(answer.clue,locale)}/>;
 return <><PlayHeader gameId={props.gameId} round={shown} total={3} score={1000-(shown-1)*200} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-7"><p className="wine-kicker">{locale==="de"?"Fallakte 27-B":"Case file 27-B"}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{locale==="de"?"Welche Flasche übersteht die Beweislage?":"Which bottle survives the evidence?"}</h1>
  <div className="wine-evidence-board mt-6"><div className="wine-clue-stack">{clues.slice(0,shown).map((c,i)=><article key={i} className="wine-clue-card" style={{"--clue-tilt":`${i%2?2:-2}deg`} as React.CSSProperties}><span>0{i+1}</span><p>{localize(c,locale)}</p></article>)}{shown<3&&<button onClick={()=>{setShown(x=>x+1);setWrong(null)}} className="wine-clue-reveal">+ {locale==="de"?"Hinweis aufdecken (-200)":"Reveal evidence (-200)"}</button>}</div>
   <div className="wine-suspects">{options.map((o,i)=>{const crossed=eliminated.has(o.id);return <button key={o.id} disabled={crossed} onClick={()=>choose(o.id)} className={`wine-suspect ${crossed?"is-crossed":""} ${wrong===o.id?"is-wrong":""}`}><span className="wine-suspect-bottle"><i/><em>{String(i+1).padStart(2,"0")}</em></span><b>{o.name}</b><small>{localize(o.structure,locale)}</small>{crossed&&<span className="wine-conflict">{locale==="de"?"widerspricht Hinweis":"conflicts with clue"}</span>}</button>})}</div>
  </div>
  {wrong&&<div className="wine-reveal"><p className="font-bold">{locale==="de"?"Diese Flasche widerspricht der bisherigen Beweislage.":"That bottle conflicts with the accumulated evidence."}</p><p className="mt-2 text-sm text-[var(--wine-muted)]">{localize(clues[Math.min(shown-1,2)],locale)}</p></div>}
 </div></>;
}
function NoteBuilder(props:PlayProps){
 const {locale}=useT();const appearance=["pale ruby","deep ruby","pale lemon"],aromas=["fresh red fruit","ripe dark fruit","citrus","fresh herbs","violet","cedar"],conclusions=["best enjoyed young","can develop further","drink now"];const [look,setLook]=useState(""),[nose,setNose]=useState<string[]>([]),[structure,setStructure]=useState({acidity:3,tannin:2,body:3,sweetness:1,alcohol:3}),[conclusion,setConclusion]=useState(""),[done,setDone]=useState(false),[finalScore,setFinalScore]=useState(0),[start]=useState(Date.now());const finish=useFinish(props);const completed=(look?1:0)+(nose.length>=2?1:0)+1+(conclusion?1:0);const submit=()=>{const aromaFit=(look==="pale ruby"&&nose.includes("fresh red fruit"))||(look==="deep ruby"&&nose.includes("ripe dark fruit"))||(look==="pale lemon"&&(nose.includes("citrus")||nose.includes("fresh herbs")));const structureFit=(look==="pale lemon"&&structure.tannin<=1)||(look==="pale ruby"&&structure.body<=3)||(look==="deep ruby"&&structure.body>=3&&structure.tannin>=2);const coherent=aromaFit&&structureFit;const s=coherent?1000:700;setFinalScore(s);finish(s,coherent?5:4,5,0,start);setDone(true)};
 if(done)return <Result {...props} score={finalScore} correct={finalScore===1000?5:4} total={5} onReplay={props.onReplay} note={finalScore===1000?(locale==="de"?"Aussehen, Aromen und Struktur bilden ein plausibles Ganzes.":"Appearance, aromas and structure form a defensible whole."):(locale==="de"?"Einige Beobachtungen widersprechen sich. Eine helle Farbe und sehr hohes Tannin oder eine tiefe Farbe ohne Körper brauchen mehr Begründung.":"Some observations pull apart. Pale colour with very high tannin, or deep colour without body, needs stronger reasoning.")} profile={structure}/>;
 const fillClass=look==="deep ruby"?"fill-deep":look==="pale lemon"?"fill-lemon":"fill-pale";
 return <><PlayHeader gameId={props.gameId} round={completed} total={4} score={completed*180} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-7"><p className="wine-kicker">{locale==="de"?"Eigenes, nicht-proprietäres Lernschema":"Original, non-proprietary learning framework"}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{locale==="de"?"Komponiere eine stimmige Tasting Note.":"Compose a coherent tasting note."}</h1>
  <div className="wine-note-workbench mt-7"><aside className="wine-note-visual"><div className={`wine-tasting-glass ${fillClass}`}><div className="wine-tasting-bowl"><i/></div><div className="wine-tasting-stem"/><div className="wine-tasting-foot"/></div><div className="wine-note-aromas">{nose.map((a,i)=><span key={a} style={{"--note-index":i} as React.CSSProperties}>{a}</span>)}</div></aside>
  <section className="wine-notebook"><fieldset><legend><span>01</span>{locale==="de"?"Aussehen":"Appearance"}</legend><div className="wine-segments">{appearance.map(v=><button type="button" key={v} onClick={()=>setLook(v)} className={look===v?"is-selected":""}>{v}</button>)}</div></fieldset>
   <fieldset><legend><span>02</span>{locale==="de"?"Nase · 2–3 wählen":"Nose · choose 2–3"}</legend><div className="flex flex-wrap gap-2">{aromas.map(v=><button type="button" key={v} onClick={()=>setNose(s=>s.includes(v)?s.filter(x=>x!==v):s.length<3?[...s,v]:s)} className={`wine-aroma-token family-${aromaFamily(v)} ${nose.includes(v)?"is-selected":""}`}>{v}</button>)}</div></fieldset>
   <fieldset><legend><span>03</span>{locale==="de"?"Struktur":"Structure"}</legend><div className="wine-structure-controls">{Object.entries(structure).map(([key,value])=><label key={key}><span>{key}<b>{value}/5</b></span><input aria-label={key} type="range" min="1" max="5" step="1" value={value} onChange={e=>setStructure(s=>({...s,[key]:Number(e.target.value)}))}/></label>)}</div></fieldset>
   <fieldset><legend><span>04</span>{locale==="de"?"Schluss":"Conclusion"}</legend><div className="wine-segments">{conclusions.map(v=><button type="button" key={v} onClick={()=>setConclusion(v)} className={conclusion===v?"is-selected":""}>{v}</button>)}</div></fieldset>
  </section></div><button disabled={!look||nose.length<2||!conclusion} onClick={submit} className="wine-button mt-7">{locale==="de"?"Notiz prüfen":"Review note"}</button>
 </div></>;
}
function ServiceChallenge(props:PlayProps){
 type ServiceStep=ServiceDecision|"interruption";const {locale}=useT();const scenario=SERVICE_SCENARIOS[props.seed%SERVICE_SCENARIOS.length];const interruption=[
  {prompt:{en:"A guest says the wine feels too warm. What now?",de:"Ein Gast findet den Wein zu warm. Was nun?"},answer:"measure",why:{en:"Acknowledge the guest, verify the condition and adjust without argument.",de:"Gästewunsch anerkennen, Zustand prüfen und ohne Diskussion anpassen."}},
  {prompt:{en:"A guest reports a possible cork fault. What now?",de:"Ein Gast meldet einen möglichen Korkfehler. Was nun?"},answer:"inspect",why:{en:"Pause service, assess the bottle and replace it when the concern is confirmed.",de:"Service pausieren, Flasche prüfen und bei bestätigtem Verdacht ersetzen."}},
  {prompt:{en:"A guest asks for a different glass. What now?",de:"Ein Gast bittet um ein anderes Glas. Was nun?"},answer:"accommodate",why:{en:"Explain briefly if useful, then accommodate a reasonable preference.",de:"Falls hilfreich kurz erklären, dann einen vernünftigen Wunsch erfüllen."}},
 ][props.seed%3];const decisions:ServiceStep[]=["glass","temperature","decant","first-step","interruption"];const [step,setStep]=useState(0),[answers,setAnswers]=useState<Partial<Record<ServiceStep,string>>>({}),[feedback,setFeedback]=useState<{ok:boolean;answer:string;why:{en:string;de:string}}|null>(null),[correct,setCorrect]=useState(0),[reviewed,setReviewed]=useState(false),[done,setDone]=useState(false),[start]=useState(Date.now());const finish=useFinish(props),encounter=useWineDex(s=>s.encounter);const choiceSets:Record<ServiceStep,{id:string;label:{en:string;de:string}}[]>={
  glass:[{id:"tulip",label:{en:"Tulip sparkling glass",de:"Tulpenförmiges Schaumweinglas"}},{id:"medium-white",label:{en:"Medium white-wine glass",de:"Mittleres Weißweinglas"}},{id:"medium-red",label:{en:"Medium red-wine glass",de:"Mittleres Rotweinglas"}},{id:"large-red",label:{en:"Large red-wine glass",de:"Großes Rotweinglas"}},{id:"small-sweet",label:{en:"Small sweet-wine glass",de:"Kleines Süßweinglas"}}],
  temperature:[{id:"well-chilled",label:{en:"Well chilled",de:"Gut gekühlt"}},{id:"cool",label:{en:"Cool",de:"Kühl"}},{id:"lightly-chilled",label:{en:"Lightly chilled",de:"Leicht gekühlt"}},{id:"cellar-cool",label:{en:"Cellar-cool",de:"Kellerkühl"}}],
  decant:[{id:"no",label:{en:"Usually no",de:"Meist nein"}},{id:"optional",label:{en:"Conditionally defensible",de:"Situativ vertretbar"}},{id:"yes",label:{en:"Often defensible",de:"Häufig vertretbar"}}],
  "first-step":[{id:"present",label:{en:"Present and confirm the bottle first",de:"Flasche zuerst präsentieren und bestätigen"}},{id:"open",label:{en:"Open immediately",de:"Sofort öffnen"}},{id:"pour",label:{en:"Pour every glass first",de:"Zuerst alle Gläser füllen"}}],
  interruption:[{id:"measure",label:{en:"Acknowledge, verify temperature, then adjust",de:"Anerkennen, Temperatur prüfen, dann anpassen"}},{id:"inspect",label:{en:"Pause and assess the bottle condition",de:"Pausieren und Flaschenzustand prüfen"}},{id:"accommodate",label:{en:"Clarify and accommodate the preference",de:"Wunsch klären und erfüllen"}},{id:"dismiss",label:{en:"Dismiss the concern and continue",de:"Einwand abweisen und fortfahren"}}],
 };const labels:Record<ServiceStep,{en:string;de:string}>={glass:{en:"Choose the glass",de:"Wähle das Glas"},temperature:{en:"Set the temperature band",de:"Wähle den Temperaturbereich"},decant:{en:"Assess decanting",de:"Bewerte Dekantieren"},"first-step":{en:"Choose the first service step",de:"Wähle den ersten Serviceschritt"},interruption:interruption.prompt};const expected=(key:ServiceStep)=>key==="interruption"?interruption.answer:scenario.answers[key];const select=(value:string)=>{if(feedback)return;const key=decisions[step],answer=expected(key),ok=value===answer;setAnswers(a=>({...a,[key]:value}));if(ok)setCorrect(c=>c+1);setFeedback({ok,answer,why:key==="interruption"?interruption.why:scenario.explanation})};const proceed=()=>{if(step===decisions.length-1)setReviewed(true);else{setStep(s=>s+1);setFeedback(null)}};const finalize=()=>{const score=correct*200;finish(score,correct,5,correct,start);if(!props.practice)encounter(scenario.id,"style",props.gameId,correct>=4);setDone(true)};
 if(done)return <Result {...props} score={correct*200} correct={correct} total={5} onReplay={props.onReplay}/>;
 const tempIndex=["well-chilled","cool","lightly-chilled","cellar-cool"].indexOf(answers.temperature??"cool");
 return <><PlayHeader gameId={props.gameId} round={reviewed?5:step+1} total={5} score={correct*200} practice={props.practice} onExit={props.onExit}/><div className="mx-auto max-w-5xl px-4 py-7"><p className="wine-kicker">{locale==="de"?"Service-Station · rein pädagogische Übung":"Service station · educational practice only"}</p><h1 className="mt-2 text-3xl font-black text-[var(--wine-cream)]">{localize(scenario.title,locale)}</h1><p className="mt-2 text-sm text-[var(--wine-muted)]">{localize(scenario.context,locale)} · {locale==="de"?"Kein Alkoholkonsum erforderlich oder empfohlen.":"No alcohol consumption is required or encouraged."}</p>
  <div className="wine-service-station mt-6"><div className="wine-service-table"><span className="service-plate"/><span className={`service-glass glass-${answers.glass??"unset"}`}><i/></span><span className="service-bottle"><i/></span>{answers.decant&&answers.decant!=="no"&&<span className="service-decanter"/>}<span className="service-napkin"/></div><div className="wine-service-gauge"><span>{locale==="de"?"Temperatur":"Temperature"}</span><div><i style={{height:`${25+tempIndex*20}%`}}/></div><b>{answers.temperature?localize(choiceSets.temperature.find(x=>x.id===answers.temperature)!.label,locale):"—"}</b></div><ol className="wine-service-rail">{decisions.map((d,i)=><li key={d} className={`${i<step||reviewed?"is-done":""} ${i===step&&!reviewed?"is-current":""}`}><span>{String(i+1).padStart(2,"0")}</span>{localize(labels[d],locale)}{answers[d]&&<Check className="h-4 w-4"/>}</li>)}</ol></div>
  {!reviewed?<section className="mt-6"><p className="wine-kicker">{localize(labels[decisions[step]],locale)}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{choiceSets[decisions[step]].map(c=><button key={c.id} disabled={!!feedback} aria-pressed={answers[decisions[step]]===c.id} onClick={()=>select(c.id)} className={`wine-answer ${feedback&&c.id===feedback.answer?"is-correct":""} ${feedback&&!feedback.ok&&answers[decisions[step]]===c.id?"is-wrong":""}`}>{localize(c.label,locale)}<ArrowRight className="h-4 w-4"/></button>)}</div>{feedback&&<div className={`wine-reveal ${feedback.ok?"is-success":""}`} aria-live="polite"><p className="font-bold">{feedback.ok?(locale==="de"?"Servicepunkt sitzt.":"Service call aligned."):(locale==="de"?"Kurs korrigieren.":"Correct the course.")}</p><p className="mt-2 text-sm text-[var(--wine-muted)]">{localize(feedback.why,locale)}</p><button onClick={proceed} className="wine-button mt-4">{step===decisions.length-1?(locale==="de"?"Service auswerten":"Review service"):(locale==="de"?"Nächster Schritt":"Next step")}<ArrowRight className="h-4 w-4"/></button></div>}</section>:<div className="wine-reveal"><p className="font-bold">{correct}/5 {locale==="de"?"Serviceentscheidungen stimmig":"service decisions aligned"}</p><p className="mt-2 text-sm text-[var(--wine-muted)]">{localize(scenario.explanation,locale)}</p><div className="mt-3 grid gap-1 text-xs">{decisions.map(d=><p key={d}><b>{localize(labels[d],locale)}:</b> {localize(choiceSets[d].find(x=>x.id===expected(d))!.label,locale)}</p>)}</div><button onClick={finalize} className="wine-button mt-4">{locale==="de"?"Service abschließen":"Complete service"}<Check className="h-4 w-4"/></button></div>}
 </div></>;
}
function ProfileMeter({label,value}:{label:string;value:number}){return <div className="wine-profile-meter"><span>{label}<b>{value}/5</b></span><div>{Array.from({length:5},(_,i)=><i key={i} className={i<value?"is-on":""}/>)}</div></div>}
function Result(props:PlayProps&{score:number;correct:number;total:number;onReplay:()=>void;note?:string;profile?:Record<string,number>;breakdown?:Record<WineCompetency,{correct:number;total:number}>}){
 const {locale}=useT();const accuracy=Math.round(props.correct/Math.max(1,props.total)*100);return <div className="mx-auto max-w-3xl px-4 py-12 md:py-20"><p className="wine-kicker">{props.practice?(locale==="de"?"Übungsrunde beendet":"Practice complete"):(locale==="de"?"Kellerpass gestempelt":"Cellar passport stamped")}</p><h1 className="mt-3 text-5xl font-black tracking-[-.05em] text-[var(--wine-cream)]">{props.score} <span className="text-2xl text-[var(--wine-copper)]">pts</span></h1><div className="mt-8 grid grid-cols-2 gap-3"><div className="wine-stat"><span>{props.correct}/{props.total}</span><small>{locale==="de"?"stimmig":"defensible"}</small></div><div className="wine-stat"><span>{accuracy}%</span><small>{locale==="de"?"Genauigkeit":"accuracy"}</small></div></div>{props.breakdown&&<section className="wine-competency-breakdown mt-5"><p className="wine-kicker">{locale==="de"?"Kompetenzprofil":"Competency profile"}</p><div>{WINE_COMPETENCIES.map(competency=>{const value=props.breakdown![competency],rate=value.total?value.correct/value.total:0;return <article key={competency}><span>{localize(EXAM_COMPETENCY_LABELS[competency],locale)}</span><div><i style={{width:`${rate*100}%`}}/></div><b>{value.correct}/{value.total}</b></article>})}</div></section>}{props.profile&&<div className="wine-profile-panel mt-5"><p className="wine-kicker">{locale==="de"?"Dein visuelles Weinprofil":"Your visual wine profile"}</p>{Object.entries(props.profile).map(([key,value])=><ProfileMeter key={key} label={key} value={value}/>)}</div>}{props.note&&<p className="wine-reveal">{props.note}</p>}<p className="mt-6 text-sm leading-6 text-[var(--wine-muted)]">{props.practice?(locale==="de"?"Wie versprochen wurde nichts gespeichert.":"As promised, nothing was saved."):(locale==="de"?"XP, Kompetenzfortschritt und neue Wine-Dex-Begegnungen wurden separat gespeichert.":"XP, competency progress and new Wine-Dex encounters were saved separately.")}</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={props.onReplay} className="wine-button"><RotateCcw className="h-4 w-4"/>{locale==="de"?"Nochmal":"Play again"}</button><Link href="/wine-nerds" className="wine-button wine-button-quiet">{locale==="de"?"Zum Keller":"Wine cellar"}</Link></div></div>
}
