import type {PokeGameDefinition,PokeGameId} from "./types";

export const POKE_GAMES:PokeGameDefinition[]=[
 ["guess-that-pokemon","Guess That Pokémon","Errate das Pokémon","See it. Name it. Lock it.","Sehen. Benennen. Verriegeln.","Identify clear specimen artwork across a seeded generation pool—four choices or expert text input.","Erkenne klare Spezies-Artworks in einem gesetzten Generationenpool – mit vier Antworten oder Experten-Texteingabe.","recognition","cyan"],
 ["poke-path-expedition","PokéPath Expedition","PokéPath-Expedition","A route through nine regions","Eine Route durch neun Regionen","Choose a starter, cross changing regional sectors and build a resilient six-member field team.","Wähle einen Starter, durchquere wechselnde Regionssektoren und stelle ein widerstandsfähiges Sechser-Team zusammen.","exploration","green"],
 ["region-ranger","Region Ranger","Region Ranger","Calibrate the regional atlas","Kalibriere den Regionsatlas","Survey towns and landmarks across nine original zoomable schematic atlases.","Vermesse Orte und Landmarken auf neun eigenen zoombaren Schematlanten.","locations","cyan"],
 ["habitat-hunt","Habitat Hunt","Habitat-Jagd","Read the ecosystem","Lies das Ökosystem","Combine biome, weather and time clues to locate a specimen in rotating regional sectors.","Kombiniere Biom-, Wetter- und Zeitspuren, um ein Exemplar in wechselnden Regionssektoren zu finden.","ecology","green"],
 ["type-clash-arena","Battle Circuit","Battle Circuit","Survive the whole circuit","Überstehe den ganzen Circuit","Choose a partner and manage persistent HP, energy, moves and pit-stop upgrades through a seeded battle circuit.","Wähle einen Partner und verwalte dauerhafte KP, Energie, Attacken und Pit-Stop-Upgrades in einem gesetzten Battle Circuit.","types","red"],
 ["gym-draft-gauntlet","Gym Draft Gauntlet","Typen-Prüfungs-Draft","Draft for the unknown","Drafte fürs Unbekannte","Build six under a point budget, then stress-test coverage across a seeded sequence of type trials.","Baue sechs Pokémon unter einem Punktelimit und teste ihre Coverage in einer gesetzten Folge von Typenprüfungen.","teamcraft","amber"],
 ["evolution-lab","Evolution Lab","Evolutionslabor","Reconstruct the family","Rekonstruiere die Familie","Solve a seeded series of evolution chains with curated conditions.","Löse eine gesetzte Serie von Entwicklungsketten mit kuratierten Bedingungen.","evolution","cyan"],
 ["binder-ascension","Binder Ascension","Binder-Aufstieg","Climb with your collection","Steige mit deiner Sammlung auf","Build a deck from owned binder cards, read enemy intents and climb a seeded archive tower through risky routes.","Baue ein Deck aus eigenen Binder-Karten, lies gegnerische Absichten und erklimme einen gesetzten Archivturm über riskante Pfade.","deckcraft","amber"],
 ["field-scanner","Field Scanner","Feldscanner","Resolve the silhouette","Entschlüssle die Silhouette","Spend signal strength on factual hints and identify changing specimens across the selected run.","Kaufe sachliche Hinweise mit Signalstärke und identifiziere wechselnde Exemplare im gewählten Run.","recognition","cyan"],
 ["cry-radar","Cry Radar","Ruf-Radar","Listen. Compare. Lock.","Hören. Vergleichen. Festlegen.","Read an animated spectrum and identify a seeded sequence of real cries without autoplay.","Lies das animierte Spektrum und erkenne eine gesetzte Folge echter Rufe ohne Autoplay.","audio","red"],
 ["poke-grid","PokéGrid","PokéGrid","Solve nine intersections","Löse neun Schnittmengen","Complete a series of 3×3 predicate matrices without repeating a species within a grid.","Vervollständige eine Serie von 3×3-Eigenschaftsmatrizen, ohne eine Spezies im Raster zu wiederholen.","taxonomy","amber"],
 ["professor-case-files","Professor’s Case Files","Professor-Fallakten","One specimen remains","Ein Exemplar bleibt","Solve seeded dossiers by revealing evidence, crossing out suspects and staking confidence.","Löse gesetzte Akten, indem du Beweise aufdeckst, Verdächtige streichst und Vertrauen setzt.","deduction","red"],
].map(([id,en,de,ee,ed,descriptionEn,descriptionDe,competency,signal])=>({
 id:id as PokeGameId,title:{en:String(en),de:String(de)},eyebrow:{en:String(ee),de:String(ed)},description:{en:String(descriptionEn),de:String(descriptionDe)},competency:competency as PokeGameDefinition["competency"],signal:signal as PokeGameDefinition["signal"],
}));

export const POKE_GAME_IDS=POKE_GAMES.map((game)=>game.id);
export const isPokeGameId=(id:string):id is PokeGameId=>POKE_GAME_IDS.includes(id as PokeGameId);
export const getPokeGame=(id:PokeGameId)=>POKE_GAMES.find((game)=>game.id===id)!;
