import { species } from "./data";
import type { Localized, Species } from "./types";
import {seedHash,seededShuffle} from "./variety";

export type RegionId="kanto"|"johto"|"hoenn"|"sinnoh"|"unova"|"kalos"|"alola"|"galar"|"paldea";
export type Biome="forest"|"meadow"|"cave"|"coast"|"mountain"|"wetland"|"desert"|"snow"|"ruins"|"volcanic";
export interface RegionNode{id:string;name:Localized;x:number;y:number;biome:Biome}
export interface RegionDefinition{id:RegionId;generation:number;name:Localized;accent:string;secondary:string;path:string;nodes:RegionNode[]}
const n=(id:string,en:string,de:string,x:number,y:number,biome:Biome):RegionNode=>({id,name:{en,de},x,y,biome});
export const REGIONS:RegionDefinition[]=[
 {id:"kanto",generation:1,name:{en:"Kanto",de:"Kanto"},accent:"#45dff2",secondary:"#72d66d",path:"M12 18L42 9 62 18 84 15 91 39 78 55 91 70 65 91 40 86 17 96 9 69 18 52 8 35Z",nodes:[n("kanto-forest","Viridian Forest sector","Vertania-Wald-Sektor",28,38,"forest"),n("kanto-meadow","Pallet meadow sector","Alabastia-Wiesen-Sektor",27,77,"meadow"),n("kanto-cave","Mt. Moon cave sector","Mondberg-Höhlen-Sektor",48,29,"cave"),n("kanto-coast","Seafoam coast sector","Seeschaum-Küsten-Sektor",42,88,"coast"),n("kanto-ruins","Lavender ruin sector","Lavandia-Ruinen-Sektor",76,61,"ruins"),n("kanto-cerulean","Cerulean water sector","Azuria-Wasser-Sektor",61,30,"wetland"),n("kanto-cinnabar","Cinnabar volcanic sector","Zinnober-Vulkan-Sektor",67,87,"volcanic"),n("kanto-saffron","Saffron central sector","Saffronia-Zentral-Sektor",58,55,"ruins")]},
 {id:"johto",generation:2,name:{en:"Johto",de:"Johto"},accent:"#f0c257",secondary:"#7ed6b4",path:"M8 35L22 15 50 19 65 8 91 24 82 43 94 61 69 72 57 94 34 81 10 88 18 61Z",nodes:[n("johto-forest","Ilex Forest sector","Steineichenwald-Sektor",30,52,"forest"),n("johto-meadow","New Bark meadow","Neuborkia-Wiese",72,74,"meadow"),n("johto-mountain","Mt. Silver sector","Silberberg-Sektor",17,28,"mountain"),n("johto-wetland","Lake of Rage shore","See-des-Zorns-Ufer",58,24,"wetland"),n("johto-ruins","Ecruteak ruins","Teak-City-Ruinen",47,52,"ruins"),n("johto-goldenrod","Goldenrod plain sector","Dukatia-Ebenen-Sektor",36,69,"meadow"),n("johto-icepath","Ice Path sector","Eispfad-Sektor",75,31,"snow"),n("johto-whirl","Whirl coast sector","Strudel-Küsten-Sektor",18,69,"coast")]},
 {id:"hoenn",generation:3,name:{en:"Hoenn",de:"Hoenn"},accent:"#64b5ff",secondary:"#ff765e",path:"M9 47L20 22 44 13 58 28 79 19 94 43 78 59 89 79 61 91 44 75 23 91 11 69Z",nodes:[n("hoenn-forest","Petalburg Woods sector","Blütenburgwald-Sektor",25,54,"forest"),n("hoenn-coast","Slateport coast sector","Graphitport-Küsten-Sektor",55,78,"coast"),n("hoenn-volcanic","Mt. Chimney sector","Schlotberg-Sektor",44,30,"volcanic"),n("hoenn-cave","Granite cave sector","Granithöhlen-Sektor",19,72,"cave"),n("hoenn-meadow","Fortree canopy sector","Baumhausen-Sektor",72,43,"meadow"),n("hoenn-rustboro","Rustboro field sector","Metarost-Feldsektor",27,37,"meadow"),n("hoenn-sootopolis","Sootopolis water sector","Xeneroville-Wasser-Sektor",78,65,"coast"),n("hoenn-meteor","Meteor Falls cave sector","Meteorfälle-Höhlen-Sektor",35,22,"cave")]},
 {id:"sinnoh",generation:4,name:{en:"Sinnoh",de:"Sinnoh"},accent:"#a7b6ff",secondary:"#e6e9ef",path:"M17 94L9 60 22 37 17 14 42 8 52 25 67 11 89 29 78 53 92 74 69 91 45 81Z",nodes:[n("sinnoh-forest","Eterna Forest sector","Ewigenau-Wald-Sektor",28,54,"forest"),n("sinnoh-mountain","Mt. Coronet sector","Kraterberg-Sektor",53,42,"mountain"),n("sinnoh-wetland","Great Marsh sector","Großmoor-Sektor",39,78,"wetland"),n("sinnoh-snow","Snowpoint sector","Blizzach-Schnee-Sektor",68,20,"snow"),n("sinnoh-meadow","Twinleaf field sector","Zweiblattdorf-Feldsektor",27,87,"meadow"),n("sinnoh-hearthome","Hearthome central sector","Herzhofen-Zentral-Sektor",58,65,"ruins"),n("sinnoh-canalave","Canalave coast sector","Fleetburg-Küsten-Sektor",18,64,"coast"),n("sinnoh-stark","Stark volcanic sector","Kahlberg-Vulkan-Sektor",82,38,"volcanic")]},
 {id:"unova",generation:5,name:{en:"Unova",de:"Einall"},accent:"#ffb764",secondary:"#9f91ff",path:"M18 8L47 13 63 7 85 19 80 42 92 57 73 70 68 93 43 84 24 94 10 71 19 51 8 31Z",nodes:[n("unova-forest","Pinwheel Forest sector","Ewigenwald-Sektor",25,63,"forest"),n("unova-desert","Desert Resort sector","Wüstenresort-Sektor",52,57,"desert"),n("unova-ruins","Dragonspiral ruins","Drachenstiege-Ruinen",64,19,"ruins"),n("unova-meadow","Nuvema field sector","Avenitia-Feldsektor",42,88,"meadow"),n("unova-coast","Castelia coast sector","Stratos-Küsten-Sektor",55,75,"coast"),n("unova-nacrene","Nacrene archive sector","Septerna-Archiv-Sektor",30,74,"ruins"),n("unova-chargestone","Chargestone cave sector","Elektrolithhöhlen-Sektor",70,48,"cave"),n("unova-driftveil","Driftveil coast sector","Marea-Küsten-Sektor",74,71,"coast")]},
 {id:"kalos",generation:6,name:{en:"Kalos",de:"Kalos"},accent:"#ed8fbc",secondary:"#70c8ff",path:"M48 8L61 27 86 21 79 45 94 61 68 69 61 94 43 77 17 89 20 62 7 47 31 35 25 15Z",nodes:[n("kalos-forest","Santalune Forest sector","Nouvaria-Wald-Sektor",27,62,"forest"),n("kalos-cave","Reflection Cave sector","Spiegelhöhlen-Sektor",64,60,"cave"),n("kalos-meadow","Vaniville meadow","Escissia-Wiese",38,83,"meadow"),n("kalos-snow","Snowbelle sector","Fractalia-Schnee-Sektor",73,75,"snow"),n("kalos-wetland","Kalos wetland sector","Kalos-Feuchtgebiet-Sektor",51,43,"wetland"),n("kalos-lumiose","Lumiose central sector","Illumina-Zentral-Sektor",49,57,"ruins"),n("kalos-terminus","Terminus cave sector","Omega-Höhlen-Sektor",79,48,"cave"),n("kalos-azure","Azure coast sector","Azurbucht-Küsten-Sektor",26,77,"coast")]},
 {id:"alola",generation:7,name:{en:"Alola",de:"Alola"},accent:"#58e0c0",secondary:"#ff9d59",path:"M12 30L28 18 39 33 31 48 13 45ZM49 16L65 9 80 22 73 38 53 35ZM45 55L61 43 77 54 69 72 49 75ZM15 69L29 57 42 72 34 91 14 87Z",nodes:[n("alola-forest","Lush Jungle sector","Schattendschungel-Sektor",60,57,"forest"),n("alola-volcanic","Wela Volcano sector","Wela-Vulkan-Sektor",65,24,"volcanic"),n("alola-desert","Haina Desert sector","Haina-Wüsten-Sektor",25,78,"desert"),n("alola-coast","Melemele coast sector","Mele-Mele-Küsten-Sektor",25,35,"coast"),n("alola-mountain","Lanakila sector","Lanakila-Berg-Sektor",56,70,"mountain"),n("alola-poni","Poni coast sector","Poni-Küsten-Sektor",29,72,"coast"),n("alola-ulaula","Ula-Ula meadow sector","Ula-Ula-Wiesen-Sektor",58,46,"meadow"),n("alola-canyon","Vast Poni canyon sector","Canyon-von-Poni-Sektor",38,82,"mountain")]},
 {id:"galar",generation:8,name:{en:"Galar",de:"Galar"},accent:"#9b8cff",secondary:"#ff5e78",path:"M39 5L59 8 65 25 55 39 69 54 61 73 72 91 48 96 35 78 39 60 27 43 35 27Z",nodes:[n("galar-forest","Slumbering Weald sector","Schlummerwald-Sektor",44,77,"forest"),n("galar-meadow","Postwick field sector","Furlongham-Feldsektor",49,88,"meadow"),n("galar-ruins","Hammerlocke ruin sector","Claw-City-Ruinen-Sektor",54,48,"ruins"),n("galar-snow","Crown snow sector","Kronen-Schnee-Sektor",54,20,"snow"),n("galar-cave","Glimwood cave sector","Wirrschein-Höhlen-Sektor",45,60,"cave"),n("galar-motostoke","Motostoke field sector","Engine-City-Feldsektor",49,68,"meadow"),n("galar-wyndon","Wyndon central sector","Score-City-Zentral-Sektor",56,31,"ruins"),n("galar-lake","Wild Area lake sector","Naturzonen-See-Sektor",41,52,"wetland")]},
 {id:"paldea",generation:9,name:{en:"Paldea",de:"Paldea"},accent:"#ff756e",secondary:"#d7c65a",path:"M50 5L70 15 89 38 84 64 66 84 43 96 20 82 8 58 15 32 31 13Z",nodes:[n("paldea-meadow","Cabo Poco field sector","Cucharico-Feldsektor",55,81,"meadow"),n("paldea-forest","Tagtree sector","Schmierhain-Sektor",71,37,"forest"),n("paldea-desert","Asado Desert sector","Brutzelwüsten-Sektor",25,48,"desert"),n("paldea-snow","Glaseado sector","Montanata-Schnee-Sektor",54,19,"snow"),n("paldea-wetland","South marsh sector","Südlicher-Sumpf-Sektor",65,66,"wetland"),n("paldea-mesagoza","Mesagoza central sector","Mesalona-Zentral-Sektor",48,61,"ruins"),n("paldea-casseroya","Casseroya lake sector","Caldero-See-Sektor",33,31,"wetland"),n("paldea-east","East Paldea coast sector","Ost-Paldea-Küsten-Sektor",80,57,"coast")]},
];
export const REGION_BY_ID=new Map(REGIONS.map((region)=>[region.id,region]));
export const eligibleRegions=(cap:number)=>REGIONS.filter((region)=>region.generation<=Math.max(1,Math.min(9,cap)));
export const regionForGeneration=(generation:number)=>REGIONS.find((region)=>region.generation===generation)??REGIONS[0];

export interface HabitatRound {key:string;region:RegionDefinition;target:Species;validSectorIds:string[];clues:{biome:Biome;weather:Localized;time:Localized}}
const habitat=(regionId:RegionId,speciesId:number,biome:Biome,weather:Localized,time:Localized):HabitatRound=>{
 const region=REGION_BY_ID.get(regionId)!,matching=region.nodes.filter((node)=>node.biome===biome),chosen=matching[speciesId%Math.max(1,matching.length)];return{key:`${regionId}-${speciesId}`,region,target:species(speciesId),validSectorIds:chosen?[chosen.id]:[],clues:{biome,weather,time}};
};
export const HABITAT_ROUNDS:HabitatRound[]=[
 habitat("kanto",25,"forest",{en:"dry air",de:"trockene Luft"},{en:"day",de:"Tag"}),habitat("kanto",41,"cave",{en:"still air",de:"stehende Luft"},{en:"night",de:"Nacht"}),
 habitat("kanto",10,"forest",{en:"humid leaves",de:"feuchte Blätter"},{en:"dawn",de:"Morgengrauen"}),habitat("kanto",50,"cave",{en:"loose soil",de:"lockerer Boden"},{en:"day",de:"Tag"}),habitat("kanto",72,"coast",{en:"salt spray",de:"Salzgischt"},{en:"dusk",de:"Dämmerung"}),habitat("kanto",77,"meadow",{en:"warm breeze",de:"warme Brise"},{en:"day",de:"Tag"}),habitat("kanto",104,"ruins",{en:"dry dust",de:"trockener Staub"},{en:"night",de:"Nacht"}),
 habitat("johto",163,"forest",{en:"clear",de:"klar"},{en:"night",de:"Nacht"}),habitat("johto",179,"meadow",{en:"breeze",de:"Brise"},{en:"day",de:"Tag"}),
 habitat("johto",161,"meadow",{en:"cool breeze",de:"kühle Brise"},{en:"dawn",de:"Morgengrauen"}),habitat("johto",167,"forest",{en:"humid",de:"feucht"},{en:"night",de:"Nacht"}),habitat("johto",194,"wetland",{en:"light rain",de:"leichter Regen"},{en:"dusk",de:"Dämmerung"}),habitat("johto",200,"ruins",{en:"still air",de:"stehende Luft"},{en:"night",de:"Nacht"}),habitat("johto",207,"mountain",{en:"dry updraft",de:"trockener Aufwind"},{en:"day",de:"Tag"}),
 habitat("hoenn",278,"coast",{en:"sea wind",de:"Seewind"},{en:"day",de:"Tag"}),habitat("hoenn",304,"cave",{en:"mineral dust",de:"Mineralstaub"},{en:"day",de:"Tag"}),
 habitat("hoenn",265,"forest",{en:"warm rain",de:"warmer Regen"},{en:"dawn",de:"Morgengrauen"}),habitat("hoenn",302,"cave",{en:"still minerals",de:"ruhige Mineralluft"},{en:"night",de:"Nacht"}),habitat("hoenn",322,"volcanic",{en:"hot ash",de:"heiße Asche"},{en:"day",de:"Tag"}),habitat("hoenn",320,"coast",{en:"calm sea",de:"ruhige See"},{en:"dusk",de:"Dämmerung"}),habitat("hoenn",333,"meadow",{en:"high cloud",de:"hohe Wolken"},{en:"day",de:"Tag"}),
 habitat("sinnoh",403,"meadow",{en:"charged air",de:"geladene Luft"},{en:"dusk",de:"Dämmerung"}),habitat("sinnoh",459,"snow",{en:"snowfall",de:"Schneefall"},{en:"day",de:"Tag"}),
 habitat("sinnoh",396,"meadow",{en:"crosswind",de:"Seitenwind"},{en:"dawn",de:"Morgengrauen"}),habitat("sinnoh",406,"forest",{en:"morning dew",de:"Morgentau"},{en:"dawn",de:"Morgengrauen"}),habitat("sinnoh",410,"mountain",{en:"stone dust",de:"Steinstaub"},{en:"day",de:"Tag"}),habitat("sinnoh",422,"wetland",{en:"steady rain",de:"steter Regen"},{en:"dusk",de:"Dämmerung"}),habitat("sinnoh",425,"forest",{en:"quiet mist",de:"ruhiger Nebel"},{en:"night",de:"Nacht"}),
 habitat("unova",551,"desert",{en:"dry wind",de:"trockener Wind"},{en:"day",de:"Tag"}),habitat("unova",607,"ruins",{en:"still",de:"windstill"},{en:"night",de:"Nacht"}),
 habitat("unova",540,"forest",{en:"leaf moisture",de:"Blattfeuchte"},{en:"day",de:"Tag"}),habitat("unova",562,"ruins",{en:"cold dust",de:"kalter Staub"},{en:"night",de:"Nacht"}),habitat("unova",580,"coast",{en:"lake breeze",de:"Seebrise"},{en:"dawn",de:"Morgengrauen"}),habitat("unova",585,"meadow",{en:"seasonal wind",de:"saisonaler Wind"},{en:"day",de:"Tag"}),habitat("unova",595,"forest",{en:"charged leaves",de:"geladene Blätter"},{en:"dusk",de:"Dämmerung"}),
 habitat("kalos",661,"meadow",{en:"clear",de:"klar"},{en:"day",de:"Tag"}),habitat("kalos",704,"wetland",{en:"rain",de:"Regen"},{en:"dusk",de:"Dämmerung"}),
 habitat("kalos",664,"forest",{en:"soft rain",de:"sanfter Regen"},{en:"dawn",de:"Morgengrauen"}),habitat("kalos",688,"wetland",{en:"mineral spray",de:"Mineralgischt"},{en:"day",de:"Tag"}),habitat("kalos",703,"cave",{en:"crystal dust",de:"Kristallstaub"},{en:"night",de:"Nacht"}),habitat("kalos",712,"snow",{en:"cold fog",de:"kalter Nebel"},{en:"day",de:"Tag"}),habitat("kalos",669,"meadow",{en:"flower pollen",de:"Blütenpollen"},{en:"dusk",de:"Dämmerung"}),
 habitat("alola",744,"mountain",{en:"warm breeze",de:"warme Brise"},{en:"day",de:"Tag"}),habitat("alola",755,"forest",{en:"humid",de:"feucht"},{en:"night",de:"Nacht"}),
 habitat("alola",731,"forest",{en:"warm drizzle",de:"warmer Nieselregen"},{en:"dawn",de:"Morgengrauen"}),habitat("alola",747,"coast",{en:"salt current",de:"Salzströmung"},{en:"dusk",de:"Dämmerung"}),habitat("alola",749,"desert",{en:"dry heat",de:"trockene Hitze"},{en:"day",de:"Tag"}),habitat("alola",757,"volcanic",{en:"sulfur haze",de:"Schwefeldunst"},{en:"night",de:"Nacht"}),habitat("alola",764,"coast",{en:"sweet pollen",de:"süßer Pollen"},{en:"day",de:"Tag"}),
 habitat("galar",821,"meadow",{en:"overcast",de:"bewölkt"},{en:"day",de:"Tag"}),habitat("galar",872,"snow",{en:"powder snow",de:"Pulverschnee"},{en:"night",de:"Nacht"}),
 habitat("galar",824,"forest",{en:"cool dew",de:"kühler Tau"},{en:"dawn",de:"Morgengrauen"}),habitat("galar",843,"cave",{en:"dry grit",de:"trockener Sand"},{en:"day",de:"Tag"}),habitat("galar",864,"ruins",{en:"cold mist",de:"kalter Nebel"},{en:"night",de:"Nacht"}),habitat("galar",868,"meadow",{en:"sweet air",de:"süße Luft"},{en:"dusk",de:"Dämmerung"}),habitat("galar",878,"ruins",{en:"metallic rain",de:"metallischer Regen"},{en:"day",de:"Tag"}),
 habitat("paldea",921,"meadow",{en:"dry",de:"trocken"},{en:"day",de:"Tag"}),habitat("paldea",938,"wetland",{en:"rain",de:"Regen"},{en:"dusk",de:"Dämmerung"}),
 habitat("paldea",928,"forest",{en:"warm pollen",de:"warmer Pollen"},{en:"day",de:"Tag"}),habitat("paldea",932,"desert",{en:"mineral wind",de:"Mineralwind"},{en:"day",de:"Tag"}),habitat("paldea",974,"snow",{en:"fine snow",de:"feiner Schnee"},{en:"dawn",de:"Morgengrauen"}),habitat("paldea",946,"forest",{en:"strong gusts",de:"starke Böen"},{en:"dusk",de:"Dämmerung"}),habitat("paldea",960,"wetland",{en:"wet sand",de:"nasser Sand"},{en:"night",de:"Nacht"}),
];

export interface HabitatSectorProfile{node:RegionNode;biome:Biome;weather:Localized;time:Localized;matches:boolean}
const profileWeather:Localized[]=[{en:"clear air",de:"klare Luft"},{en:"light rain",de:"leichter Regen"},{en:"dry wind",de:"trockener Wind"},{en:"cold mist",de:"kalter Nebel"},{en:"warm breeze",de:"warme Brise"}];
const profileTimes:Localized[]=[{en:"dawn",de:"Morgengrauen"},{en:"day",de:"Tag"},{en:"dusk",de:"Dämmerung"},{en:"night",de:"Nacht"}];
export function habitatSectorProfiles(round:HabitatRound,seed:string):HabitatSectorProfile[]{
 return round.region.nodes.map((node,index)=>{
  const matches=round.validSectorIds.includes(node.id);
  if(matches)return{node,biome:round.clues.biome,weather:round.clues.weather,time:round.clues.time,matches:true};
  let weather=profileWeather[(seedHash(`${seed}:${node.id}:weather`)+index)%profileWeather.length];
  let time=profileTimes[(seedHash(`${seed}:${node.id}:time`)+index)%profileTimes.length];
  if(node.biome===round.clues.biome&&weather.en===round.clues.weather.en&&time.en===round.clues.time.en)time=profileTimes[(profileTimes.indexOf(time)+1)%profileTimes.length];
  return{node,biome:node.biome,weather,time,matches:false};
 });
}
export const habitatRoundsFor=(cap:number,count:number,seed="habitat-default")=>{
 const regions=seededShuffle(eligibleRegions(cap),`${seed}:regions`),perRegion=new Map(regions.map((region)=>[region.id,seededShuffle(HABITAT_ROUNDS.filter((round)=>round.region.id===region.id),`${seed}:${region.id}`)]));const cursors=new Map<RegionId,number>();const result:HabitatRound[]=[];
 for(let index=0;index<count;index++){const region=regions[index%regions.length],pool=perRegion.get(region.id)!;const cursor=cursors.get(region.id)??0;let item=pool[cursor%pool.length];cursors.set(region.id,cursor+1);if(result.at(-1)?.key===item.key&&pool.length>1)item=pool[(cursor+1)%pool.length];result.push(item)}return result;
};
export interface RangerRound{key:string;region:RegionDefinition;target:RegionNode}
export const rangerRoundsFor=(cap:number,count:number,seed="ranger-default"):RangerRound[]=>{
 const regions=seededShuffle(eligibleRegions(cap),`${seed}:regions`),bags=new Map(regions.map((region)=>[region.id,seededShuffle(region.nodes,`${seed}:${region.id}`)]));const cursors=new Map<RegionId,number>();const result:RangerRound[]=[];
 for(let index=0;index<count;index++){const region=regions[index%regions.length],pool=bags.get(region.id)!;const cursor=cursors.get(region.id)??0,target=pool[cursor%pool.length];cursors.set(region.id,cursor+1);result.push({key:`${region.id}-${target.id}`,region,target})}return result;
};
export function cycleWithoutImmediateDuplicates<T>(pool:readonly T[],count:number,key:(item:T)=>string):T[]{
 if(!pool.length||count<=0)return[];const result:T[]=[];let offset=Math.max(0,count%pool.length);
 for(let index=0;index<count;index++){let candidate=pool[(index*7+offset)%pool.length];if(result.length>0&&key(candidate)===key(result[result.length-1]))candidate=pool[(index*7+offset+1)%pool.length];result.push(candidate)}
 return result;
}
