"use client";
import {useMemo,useState} from "react";
import {Check,Crosshair,LockKeyhole,Shield,ShieldAlert,Swords} from "lucide-react";
import {KantoMap} from "../kanto-map";
import {PokemonSprite} from "../pokemon-sprite";
import {Feedback,RunHud,type GameProps} from "../gameplay";
import {MAP_NODES,RANGER_TARGETS} from "@/poke/maps";
import {SPECIES,STARTERS,species} from "@/poke/data";
import {TYPE_COLORS,typeMultiplier} from "@/poke/type-chart";

const expeditionLayers=[
 [{node:"forest",encounter:25},{node:"pewter",encounter:74}],
 [{node:"moon",encounter:41},{node:"cerulean",encounter:63}],
 [{node:"celadon",encounter:58},{node:"rock-tunnel",encounter:95}],
 [{node:"fuchsia",encounter:123},{node:"seafoam",encounter:86}],
] as const;

export function PokePathExpedition({locale,difficulty,onFinish}:GameProps){
 const [starter,setStarter]=useState<number|null>(null);const [layer,setLayer]=useState(0);const [team,setTeam]=useState<number[]>([]);const [hp,setHp]=useState(difficulty==="hard"?60:90);const [capsules,setCapsules]=useState(difficulty==="hard"?2:4);const [active,setActive]=useState<string>();const [encounter,setEncounter]=useState<number|null>(null);const [locked,setLocked]=useState<string[]>([]);
 const begin=(id:number)=>{setStarter(id);setTeam([id]);setActive("pallet")};
 const choose=(node:string,id:number)=>{setActive(node);setEncounter(id);setLocked(expeditionLayers[layer].filter((choice)=>choice.node!==node).map((choice)=>choice.node));setHp((value)=>Math.max(10,value-(difficulty==="hard"?18:12)))};
 const resolve=(catchIt:boolean)=>{let nextTeam=team;if(catchIt&&capsules>0){nextTeam=team.length<6?[...team,encounter!]:[...team.slice(1),encounter!];setTeam(nextTeam);setCapsules((value)=>value-1)}const next=layer+1;setEncounter(null);setLocked([]);if(next>=expeditionLayers.length){const coverage=new Set(nextTeam.flatMap((id)=>species(id).types)).size;const score=Math.round(hp*5+coverage*110+capsules*50);onFinish(score,coverage>=5?1:0,1,nextTeam)}else setLayer(next)};
 if(!starter)return <section className="poke-expedition-brief"><div><p className="poke-kicker">STARTER CLEARANCE</p><h2>{locale==="de"?"Wähle dein erstes Feldexemplar":"Choose your first field specimen"}</h2><p>{locale==="de"?"Sein Typ entscheidet, welche späteren Routen riskant oder effizient werden.":"Its type changes which later routes are risky or efficient."}</p></div><div className="poke-starter-bay">{STARTERS.map((entry)=><button key={entry.id} onClick={()=>begin(entry.id)}><PokemonSprite entry={entry}/><span>#{String(entry.id).padStart(3,"0")}</span><b>{entry.name[locale]}</b><small>{entry.types.join(" · ")}</small></button>)}</div></section>;
 return <div className="poke-expedition"><RunHud score={hp*5+team.length*100} round={layer+1} total={4} resource={capsules} label={locale==="de"?"MODULE":"CAPSULES"}/>
  <div className="poke-expedition-grid"><KantoMap locale={locale} activeNode={active}/>
   <aside className="poke-field-console"><header><span>TEAM / {team.length}·6</span><strong>HP {hp}</strong></header><div className="poke-team-tray">{[0,1,2,3,4,5].map((slot)=>team[slot]?<div key={slot}><PokemonSprite entry={species(team[slot])} size={72}/><small>{species(team[slot]).name[locale]}</small></div>:<div key={slot} className="is-empty">+</div>)}</div>
    {!encounter?<div className="poke-route-choice"><p>{locale==="de"?"Nur eine Route dieser Ebene bleibt offen.":"Only one route on this layer stays open."}</p>{expeditionLayers[layer].map((choice)=>{const node=MAP_NODES.find((item)=>item.id===choice.node)!;return <button key={choice.node} disabled={locked.includes(choice.node)} onClick={()=>choose(choice.node,choice.encounter)}><Crosshair/><span>{node.name[locale]}<small>{node.kind} · unknown signal</small></span>{locked.includes(choice.node)&&<LockKeyhole/>}</button>})}</div>
    :<div className="poke-encounter-card"><p className="poke-kicker">WILD SIGNAL</p><PokemonSprite entry={species(encounter)} size={145}/><h3>{species(encounter).name[locale]}</h3><div><button className="poke-primary" disabled={capsules===0} onClick={()=>resolve(true)}>{locale==="de"?"Fangen / ersetzen":"Catch / replace"}</button><button className="poke-secondary" onClick={()=>resolve(false)}>{locale==="de"?"Dokumentieren & weiter":"Log & continue"}</button></div></div>}
   </aside>
  </div>
 </div>;
}

const rangerRounds=["celadon","moon","fuchsia","cerulean","cinnabar"];
export function RegionRanger({locale,difficulty,onFinish}:GameProps){
 const [round,setRound]=useState(0);const [score,setScore]=useState(0);const [correctCount,setCorrectCount]=useState(0);const [streak,setStreak]=useState(0);const [feedback,setFeedback]=useState<{good:boolean;distance:number;nextScore:number;nextCorrect:number}|null>(null);
 const target=RANGER_TARGETS.find((node)=>node.id===rangerRounds[round])??RANGER_TARGETS[0];const radius=difficulty==="easy"?14:difficulty==="medium"?10:7;
 const place=(point:{x:number;y:number})=>{if(feedback)return;const distance=Math.hypot(point.x-target.x,point.y-target.y);const good=distance<=radius;const gained=good?Math.max(100,Math.round(700-distance*35))+streak*60:0;const nextScore=score+gained;const nextCorrect=correctCount+(good?1:0);setScore(nextScore);setCorrectCount(nextCorrect);setStreak(good?streak+1:0);setFeedback({good,distance,nextScore,nextCorrect})};
 const next=()=>{if(!feedback)return;const nr=round+1;if(nr>=rangerRounds.length)onFinish(feedback.nextScore,feedback.nextCorrect,5,[]);else{setRound(nr);setFeedback(null)}};
 return <div className="poke-ranger"><RunHud score={score} round={round+1} total={5}/><header className="poke-target-brief"><span>TARGET {String(round+1).padStart(2,"0")}</span><h2>{target.name[locale]}</h2><p>{locale==="de"?"Setze den Messpunkt. Das Ziel wird erst danach eingeblendet.":"Place the survey point. The target appears only after you lock it."}</p></header><KantoMap locale={locale} showLabels={false} onPlace={place} activeNode={feedback?target.id:undefined}/>{feedback&&<Feedback good={feedback.good}>{feedback.good?<Check/>:<Crosshair/>}<span><b>{feedback.good?(locale==="de"?"Signal erfasst":"Signal acquired"):(locale==="de"?"Außerhalb des Fangradius":"Outside capture radius")}</b><small>{feedback.distance.toFixed(1)} atlas units · snap radius {radius}</small></span><button onClick={next}>{locale==="de"?"Nächstes Ziel":"Next target"} →</button></Feedback>}</div>;
}

const huntTargets=[25,41,95,123,86];
export function HabitatHunt({locale,difficulty,onFinish}:GameProps){
 const [round,setRound]=useState(0);const [balls,setBalls]=useState(difficulty==="hard"?5:8);const [score,setScore]=useState(0);const [feedback,setFeedback]=useState<{good:boolean;node:string}|null>(null);
 const target=species(huntTargets[round]);const valid=MAP_NODES.filter((node)=>node.encounters.includes(target.id));
 const choose=(node:string)=>{if(feedback)return;const good=valid.some((item)=>item.id===node);setFeedback({good,node});if(good)setScore((value)=>value+400+balls*20);else setBalls((value)=>value-1)};
 const next=()=>{if(feedback?.good){const nr=round+1;if(nr>=huntTargets.length){onFinish(score+400+balls*20,round+1,5,huntTargets);return}setRound(nr)}setFeedback(null)};
 return <div className="poke-hunt"><RunHud score={score} round={round+1} total={5} resource={balls} label="CAPSULES"/><div className="poke-hunt-layout"><section className="poke-target-specimen"><span>FIRERED LEARNING TARGET</span><PokemonSprite entry={target} size={180}/><h2>{target.name[locale]}</h2><p>{locale==="de"?"Wähle den passenden kuratierten Feldsektor. Die Karte ist ein schematisches Lernfixture, keine exakte Encounter-Karte.":"Choose the matching curated field sector. This is a schematic learning fixture, not an exact encounter map."}</p></section><div><KantoMap locale={locale} activeNode={feedback?.node}/><div className="poke-node-selector">{MAP_NODES.filter((node)=>node.encounters.length).map((node)=><button key={node.id} onClick={()=>choose(node.id)} disabled={!!feedback}>{node.name[locale]} {locale==="de"?"· Feldsektor":"· field sector"}</button>)}</div></div></div>{feedback&&<Feedback good={feedback.good}><span><b>{feedback.good?(locale==="de"?"Lernfixture bestätigt":"Learning fixture confirmed"):(locale==="de"?"Kein Treffer in diesem Fixture":"No match in this fixture")}</b><small>{locale==="de"?"Scope: Kanto · Pokémon Feuerrot · eigene schematische, kuratierte Lernfixtures":"Scope: Kanto · Pokémon FireRed · original schematic curated learning fixtures"}</small></span><button onClick={next}>{feedback.good?(locale==="de"?"Weiter":"Continue"):(locale==="de"?"Erneut versuchen":"Try again")} →</button></Feedback>}</div>;
}

const clashRounds=[
 {attacker:4,defender:1,options:["fire","water","ground","normal"]},
 {attacker:25,defender:74,options:["electric","normal","flying","poison"]},
 {attacker:7,defender:95,options:["water","normal","electric","poison"]},
 {attacker:58,defender:46,options:["fire","grass","normal","ground"]},
 {attacker:66,defender:131,options:["fighting","ground","normal","ice"]},
];
export function TypeClashArena({locale,difficulty,generationCap,onFinish}:GameProps){
 const generationPairs=[{attacker:4,defender:1},{attacker:155,defender:152},{attacker:255,defender:252},{attacker:390,defender:387},{attacker:498,defender:495},{attacker:653,defender:650},{attacker:725,defender:722},{attacker:813,defender:810},{attacker:909,defender:906}];const scoped=generationCap===1?clashRounds:[{...generationPairs[generationCap-1],options:["fire","water","ground","normal"]},...clashRounds];const total=difficulty==="easy"?4:5;const [round,setRound]=useState(0);const [score,setScore]=useState(0);const [correctCount,setCorrectCount]=useState(0);const [hearts,setHearts]=useState(difficulty==="hard"?2:3);const [combo,setCombo]=useState(0);const [selected,setSelected]=useState<string|null>(null);const [outcome,setOutcome]=useState<{good:boolean;nextScore:number;nextCorrect:number;nextHearts:number}|null>(null);const data=scoped[round];const attacker=species(data.attacker),defender=species(data.defender);const best=Math.max(...data.options.map((option)=>typeMultiplier(option,defender.types)));const good=outcome?.good??false;
 const lock=(option:string)=>{if(selected)return;const success=typeMultiplier(option,defender.types)===best;const gained=success?300+combo*80:0;const nextScore=score+gained;const nextCorrect=correctCount+(success?1:0);const nextHearts=Math.max(0,hearts-(success?0:1));setSelected(option);setScore(nextScore);setCorrectCount(nextCorrect);setHearts(nextHearts);setOutcome({good:success,nextScore,nextCorrect,nextHearts});if(success)setCombo((value)=>value+1);else setCombo(0)};
 const next=()=>{if(!outcome)return;const encountered=[...scoped.slice(0,round+1).flatMap((item)=>[item.attacker,item.defender])];if(round+1>=total||outcome.nextHearts<=0)onFinish(outcome.nextScore,outcome.nextCorrect,total,encountered);else{setRound((value)=>value+1);setSelected(null);setOutcome(null)}};
 return <div className="poke-clash"><RunHud score={score} round={round+1} total={total} resource={hearts} label="HEARTS"/><section className="poke-battle-stage"><div className="poke-battle-scanlines"/><div className="poke-fighter is-player"><PokemonSprite entry={attacker} size={180}/><b>{attacker.name[locale]}</b><small>{attacker.types.join(" · ")}</small></div><Swords className="poke-clash-mark"/><div className="poke-fighter is-rival"><PokemonSprite entry={defender} size={180}/><b>{defender.name[locale]}</b><small>{defender.types.join(" · ")}</small></div></section><p className="poke-ruleset">{locale==="de"?"Regelwerk: moderne 18-Typen-Beziehungen · Doppeltypen werden multipliziert":"Ruleset: modern 18-type relations · dual defender multipliers multiply"}</p><div className="poke-move-deck">{data.options.map((option)=>{const multiplier=typeMultiplier(option,defender.types);return <button key={option} disabled={!!selected} onClick={()=>lock(option)} style={{"--type-color":TYPE_COLORS[option]} as React.CSSProperties}><span>{option.toUpperCase()}</span>{selected&&<b>{multiplier}×</b>}</button>})}</div>{selected&&<Feedback good={good}>{good?<Shield/>:<ShieldAlert/>}<span><b>{good?(locale==="de"?"Optimale Wirkung":"Optimal effect"):(locale==="de"?"Bessere Coverage verfügbar":"Stronger coverage available")}</b><small>{selected} → {defender.types.map((item)=>`${item} ${typeMultiplier(selected,[item])}×`).join(" · ")}</small></span><button onClick={next}>Next →</button></Feedback>}</div>;
}

const draftIds=[3,6,9,12,18,25,31,34,36,38,45,47,55,59,65,68,71,76,82,94,103,121,124,130,131,134,135,136,142,143];
const trials=["water","fire","psychic","dragon","ground"];
export function GymDraftGauntlet({locale,difficulty,generationCap,onFinish}:GameProps){
 const pool=useMemo(()=>{if(generationCap===1)return draftIds.map(species);const scoped=SPECIES.filter((entry)=>entry.generation<=generationCap);const step=Math.max(1,Math.floor(scoped.length/30));return scoped.filter((_,index)=>index%step===0).slice(0,30)},[generationCap]);const [draft,setDraft]=useState<number[]>([]);const [locked,setLocked]=useState(false);const budget=difficulty==="easy"?520:difficulty==="medium"?460:420;const cost=(id:number)=>Math.round(Object.values(species(id).stats).reduce((a,b)=>a+b,0)/6);const spent=draft.reduce((sum,id)=>sum+cost(id),0);
 const toggle=(id:number)=>setDraft((items)=>items.includes(id)?items.filter((item)=>item!==id):items.length<6&&spent+cost(id)<=budget?[...items,id]:items);
 const report=trials.map((trial)=>{const best=Math.max(...draft.flatMap((id)=>species(id).types.map((type)=>typeMultiplier(type,[trial]))));return{trial,best}});
 const coverage=report.filter((item)=>item.best>1).length;const typeDiversity=new Set(draft.flatMap((id)=>species(id).types)).size;const score=coverage*500+typeDiversity*80+Math.max(0,budget-spent);
 if(locked)return <div className="poke-draft-report"><RunHud score={score} round={5} total={5}/><header><p className="poke-kicker">AUTO-RESOLUTION / COVERAGE CONSOLE</p><h2>{locale==="de"?"Prüfungsbericht":"Trial report"}</h2></header><div className="poke-radar-console"><div className="poke-radar-rings">{report.map((item,index)=><span key={item.trial} style={{["--ray" as string]:`${index*72}deg`,["--reach" as string]:`${Math.min(90,item.best*35)}%`}}>{item.trial}<i/></span>)}</div><aside>{report.map((item)=><div key={item.trial} className={item.best>1?"is-pass":""}><b>{item.trial}</b><span>{item.best}× best available</span></div>)}</aside></div><button className="poke-primary" onClick={()=>onFinish(score,coverage,5,draft)}>{locale==="de"?"Run abschließen":"Complete run"}</button></div>;
 return <div className="poke-draft"><RunHud score={0} round={draft.length} total={6} resource={budget-spent} label="BUDGET"/><header className="poke-draft-header"><div><p className="poke-kicker">BLIND TYPE TRIAL SEQUENCE</p><h2>{locale==="de"?"Drafte sechs unter Budget":"Draft six under budget"}</h2></div><div>{spent}<small> / {budget}</small></div></header><div className="poke-draft-layout"><div className="poke-roster-wall">{pool.map((entry)=><button key={entry.id} onClick={()=>toggle(entry.id)} className={draft.includes(entry.id)?"is-drafted":""} disabled={!draft.includes(entry.id)&&(draft.length>=6||spent+cost(entry.id)>budget)}><PokemonSprite entry={entry} size={82}/><span>#{entry.id} · {cost(entry.id)}</span><b>{entry.name[locale]}</b></button>)}</div><aside className="poke-draft-tray"><span>FIELD SIX</span>{[0,1,2,3,4,5].map((slot)=>draft[slot]?<button key={slot} onClick={()=>toggle(draft[slot])}><PokemonSprite entry={species(draft[slot])} size={65}/><small>{species(draft[slot]).name[locale]}</small></button>:<div key={slot}>EMPTY</div>)}<p>{locale==="de"?"Coverage-Analyse bleibt bis zum Lock verborgen.":"Coverage analysis remains sealed until lock-in."}</p><button className="poke-primary" disabled={draft.length!==6} onClick={()=>setLocked(true)}>LOCK DRAFT <LockKeyhole/></button></aside></div></div>;
}
