"use client";
import {useMemo,useState} from "react";
import {Check,Crosshair,LockKeyhole,Shield,ShieldAlert,Swords} from "lucide-react";
import {KantoMap} from "../kanto-map";
import {RegionalAtlas} from "../regional-atlas";
import {PokemonSprite} from "../pokemon-sprite";
import {Feedback,RunHud,type GameProps} from "../gameplay";
import {MAP_NODES,RANGER_TARGETS} from "@/poke/maps";
import {SPECIES,species} from "@/poke/data";
import {TYPE_COLORS,typeMultiplier} from "@/poke/type-chart";
import {HABITAT_ROUNDS,eligibleRegions,habitatRoundsFor,rangerRoundsFor} from "@/poke/regions";
import {seededShuffle} from "@/poke/variety";
import {expeditionStarterRoster} from "@/poke/expedition";
export {BattleCircuit as TypeClashArena} from "./battle-circuit";
export {GymDraftGauntlet} from "./gym-draft-gauntlet";

const expeditionLayers=[
 [{node:"forest",encounter:25},{node:"pewter",encounter:74}],
 [{node:"moon",encounter:41},{node:"cerulean",encounter:63}],
 [{node:"celadon",encounter:58},{node:"rock-tunnel",encounter:95}],
 [{node:"fuchsia",encounter:123},{node:"seafoam",encounter:86}],
] as const;

export function PokePathExpedition({locale,difficulty,generationCap,roundCount,runSeed,onFinish}:GameProps){
 const regions=useMemo(()=>seededShuffle(eligibleRegions(generationCap),`${runSeed}:expedition-regions`),[generationCap,runSeed]);const starterRoster=useMemo(()=>expeditionStarterRoster(generationCap,runSeed),[generationCap,runSeed]);const [starter,setStarter]=useState<number|null>(null);const [layer,setLayer]=useState(0);const [team,setTeam]=useState<number[]>([]);const [hp,setHp]=useState(difficulty==="hard"?60:90);const [capsules,setCapsules]=useState(difficulty==="hard"?2:4);const [active,setActive]=useState<string>();const [encounter,setEncounter]=useState<number|null>(null);const [locked,setLocked]=useState<string[]>([]);const [score,setScore]=useState(0);const [history,setHistory]=useState<{region:string;sector:string;effect:string}[]>([]);const region=regions[layer%regions.length]??regions[0];const choices=region.nodes.slice(layer%3,layer%3+3).length>=2?region.nodes.slice(layer%3,layer%3+3):region.nodes.slice(0,3);const regionTargets=HABITAT_ROUNDS.filter((round)=>round.region.id===region.id);
 const begin=(id:number)=>{setStarter(id);setTeam([id]);setActive(region.nodes[0]?.id)};
 const choose=(node:string)=>{const picked=region.nodes.find((item)=>item.id===node)!;const hazard=["cave","volcanic","snow","desert"].includes(picked.biome);const bonus=["meadow","coast"].includes(picked.biome);const damage=hazard?(difficulty==="hard"?18:12):5;const nextHp=Math.max(0,hp-damage);setHp(nextHp);if(bonus)setCapsules((value)=>Math.min(6,value+1));const target=regionTargets[(layer+choices.findIndex((item)=>item.id===node))%Math.max(1,regionTargets.length)];const speciesSignal=layer%3===1?null:target?.target.id??null;setEncounter(speciesSignal??-1);setActive(node);setLocked(choices.filter((choice)=>choice.id!==node).map((choice)=>choice.id));setHistory((items)=>[...items,{region:region.name[locale],sector:picked.name[locale],effect:hazard?`−${damage} HP`:bonus?"+1 capsule":"research"}]);setScore((value)=>value+Math.max(40,160-damage*3))};
 const resolve=(catchIt:boolean)=>{let nextTeam=team;if(catchIt&&encounter&&encounter>0&&capsules>0){nextTeam=team.length<6?[...team,encounter]:[...team.slice(1),encounter];setTeam(nextTeam);setCapsules((value)=>value-1)}const next=layer+1;setEncounter(null);setLocked([]);if(next>=roundCount||hp<=0){const coverage=new Set(nextTeam.flatMap((id)=>species(id).types)).size;const finalScore=score+Math.round(hp*5+coverage*110+capsules*50);onFinish(finalScore,hp>0?next:Math.max(0,next-1),next,nextTeam)}else setLayer(next)};
 if(!starter)return <section className="poke-expedition-brief"><div><p className="poke-kicker">STARTER CLEARANCE</p><h2>{locale==="de"?"Wähle dein erstes Feldexemplar":"Choose your first field specimen"}</h2><p>{locale==="de"?"Sein Typ entscheidet, welche späteren Routen riskant oder effizient werden.":"Its type changes which later routes are risky or efficient."}</p></div><div className="poke-starter-bay">{starterRoster.map((entry)=><button key={entry.id} onClick={()=>begin(entry.id)}><PokemonSprite entry={entry}/><span>#{String(entry.id).padStart(3,"0")} · GEN {entry.generation}</span><b>{entry.name[locale]}</b><small>{entry.types.join(" · ")}</small></button>)}</div></section>;
 return <div className="poke-expedition" style={{"--region-accent":region.accent} as React.CSSProperties}><RunHud score={score+hp*5+team.length*100} round={layer+1} total={roundCount} resource={capsules} label="CAPSULES"/><div className="poke-region-transition"><span>EXPEDITION STAGE {layer+1}</span><b>{region.name[locale]}</b><i/></div>
  <div className="poke-expedition-grid"><RegionalAtlas region={region} locale={locale} activeSector={active}/>
   <aside className="poke-field-console"><header><span>TEAM / {team.length}·6</span><strong>HP {hp}</strong></header><div className="poke-team-tray">{[0,1,2,3,4,5].map((slot)=>team[slot]?<div key={slot}><PokemonSprite entry={species(team[slot])} size={72}/><small>{species(team[slot]).name[locale]}</small></div>:<div key={slot} className="is-empty">+</div>)}</div>
    {encounter===null?<div className="poke-route-choice"><p>{locale==="de"?"Route wählen: Gefahren kosten HP, günstige Biome liefern Ressourcen. Alternativen schließen sich.":"Choose a route: hazards cost HP, favorable biomes grant resources. Alternatives lock."}</p>{choices.map((node)=><button key={node.id} disabled={locked.includes(node.id)} onClick={()=>choose(node.id)}><Crosshair/><span>{node.name[locale]}<small>{node.biome} · {["cave","volcanic","snow","desert"].includes(node.biome)?"hazard signal":"field signal"}</small></span>{locked.includes(node.id)&&<LockKeyhole/>}</button>)}</div>
    :encounter>0?<div className="poke-encounter-card"><p className="poke-kicker">WILD SIGNAL</p><PokemonSprite entry={species(encounter)} size={145}/><h3>{species(encounter).name[locale]}</h3><div><button className="poke-primary" disabled={capsules===0} onClick={()=>resolve(true)}>{locale==="de"?"Fangen / ersetzen":"Catch / replace"}</button><button className="poke-secondary" onClick={()=>resolve(false)}>{locale==="de"?"Dokumentieren & weiter":"Log & continue"}</button></div></div>:<div className="poke-encounter-card"><p className="poke-kicker">FIELD EVENT</p><div className="poke-expedition-cache"><Shield/><b>{locale==="de"?"Keine Sichtung – aber wertvolle Habitatdaten.":"No sighting—but valuable habitat data."}</b></div><button className="poke-primary" onClick={()=>resolve(false)}>{locale==="de"?"Pfad fortsetzen":"Continue path"} →</button></div>}
   </aside>
  </div>
  <div className="poke-path-history">{history.map((item,index)=><span key={`${item.sector}-${index}`}><b>{index+1}</b>{item.region} · {item.sector}<small>{item.effect}</small></span>)}</div>
 </div>;
}

const rangerRounds=["celadon","moon","fuchsia","cerulean","cinnabar"];
export function RegionRanger({locale,difficulty,generationCap,roundCount,runSeed,onFinish}:GameProps){
 const rounds=useMemo(()=>rangerRoundsFor(generationCap,roundCount,runSeed),[generationCap,roundCount,runSeed]);const [round,setRound]=useState(0);const [score,setScore]=useState(0);const [correctCount,setCorrectCount]=useState(0);const [streak,setStreak]=useState(0);const [feedback,setFeedback]=useState<{good:boolean;distance:number;nextScore:number;nextCorrect:number}|null>(null);const current=rounds[round];const radius=difficulty==="easy"?14:difficulty==="medium"?10:7;if(!current)return null;
 const place=(point:{x:number;y:number})=>{if(feedback)return;const distance=Math.hypot(point.x-current.target.x,point.y-current.target.y);const close=distance<=radius*.45,good=distance<=radius;const gained=good?Math.max(100,Math.round(700-distance*35))+(close?180:0)+streak*60:0;const nextScore=score+gained;const nextCorrect=correctCount+(good?1:0);setScore(nextScore);setCorrectCount(nextCorrect);setStreak(good?streak+1:0);setFeedback({good,distance,nextScore,nextCorrect})};
 const next=()=>{if(!feedback)return;const nr=round+1;if(nr>=rounds.length)onFinish(feedback.nextScore,feedback.nextCorrect,nr,[]);else{setRound(nr);setFeedback(null)}};
 return <div className="poke-ranger" style={{"--region-accent":current.region.accent} as React.CSSProperties}><RunHud score={score} round={round+1} total={rounds.length} resource={streak} label="COMBO"/><div className="poke-region-transition" key={current.region.id}><span>REGION TRANSITION · GEN {current.region.generation}</span><b>{current.region.name[locale]}</b><i/></div><header className="poke-target-brief"><span>TARGET {String(round+1).padStart(2,"0")}</span><h2>{current.target.name[locale]}</h2><p>{locale==="de"?"Setze den Messpunkt durch den Kartenfog. Ziel und Distanzringe erscheinen erst nach dem Lock.":"Place the survey point through map fog. Target and distance rings appear only after lock."}</p></header><RegionalAtlas region={current.region} locale={locale} showLabels={false} fog={!feedback} showRings={!!feedback} onPlace={place} activeSector={feedback?current.target.id:undefined}/>{feedback&&<Feedback good={feedback.good}>{feedback.good?<Check/>:<Crosshair/>}<span><b>{feedback.good?(feedback.distance<=radius*.45?(locale==="de"?"Präzisions-Lock":"Precision lock"):(locale==="de"?"Signal erfasst":"Signal acquired")):(locale==="de"?"Außerhalb des Fangradius":"Outside capture radius")}</b><small>{feedback.distance.toFixed(1)} atlas units · radius {radius} · {current.region.name[locale]}</small></span><button onClick={next}>{locale==="de"?"Nächste Region":"Next region"} →</button></Feedback>}</div>;
}

const huntTargets=[25,41,95,123,86];
export function HabitatHunt({locale,difficulty,generationCap,roundCount,runSeed,onFinish}:GameProps){
 const rounds=useMemo(()=>habitatRoundsFor(generationCap,roundCount,runSeed),[generationCap,roundCount,runSeed]);const[index,setIndex]=useState(0);const[probes,setProbes]=useState(difficulty==="hard"?2:difficulty==="easy"?4:3);const[score,setScore]=useState(0);const[correct,setCorrect]=useState(0);const[revealedClues,setRevealedClues]=useState(1);const[feedback,setFeedback]=useState<{good:boolean;sector:string;nextScore:number;nextCorrect:number;nextProbes:number}|null>(null);const completedIds=rounds.slice(0,index+1).map((round)=>round.target.id);
 const current=rounds[index];if(!current)return <Feedback good={false}>No habitat fixtures available.</Feedback>;
 const choose=(sector:string)=>{if(feedback)return;const good=current.validSectorIds.includes(sector);const gained=good?Math.max(120,520-revealedClues*65+probes*30):0;const nextScore=score+gained,nextCorrect=correct+(good?1:0),nextProbes=Math.max(0,probes-(good?0:1));setScore(nextScore);setCorrect(nextCorrect);setProbes(nextProbes);setFeedback({good,sector,nextScore,nextCorrect,nextProbes})};
 const next=()=>{if(!feedback)return;if(index+1>=rounds.length||feedback.nextProbes<=0){onFinish(feedback.nextScore,feedback.nextCorrect,index+1,completedIds);return}setIndex((value)=>value+1);setFeedback(null);setRevealedClues(1);setProbes(difficulty==="hard"?2:difficulty==="easy"?4:3)};
 const node=current.region.nodes.find((item)=>item.id===feedback?.sector);
 return <div className="poke-hunt" style={{"--region-accent":current.region.accent} as React.CSSProperties}><RunHud score={score} round={index+1} total={rounds.length} resource={probes} label={locale==="de"?"SONDEN":"PROBES"}/><div className="poke-region-transition"><span>REGION {current.region.generation}/{generationCap}</span><b>{current.region.name[locale]}</b><i/></div><div className="poke-hunt-layout"><section className="poke-target-specimen" key={current.key}><span>{locale==="de"?"IMMUTABLES RUNDENZIEL":"IMMUTABLE ROUND TARGET"} · #{current.target.id}</span><PokemonSprite entry={current.target} size={190}/><h2>{current.target.name[locale]}</h2><div className="poke-ecology-tokens"><span>BIOME <b>{current.clues.biome}</b></span>{revealedClues>=2&&<span>WEATHER <b>{current.clues.weather[locale]}</b></span>}{revealedClues>=3&&<span>TIME <b>{current.clues.time[locale]}</b></span>}</div>{revealedClues<3&&<button className="poke-secondary" onClick={()=>setRevealedClues((value)=>value+1)}>{locale==="de"?"Weitere Umweltprobe −65":"Reveal environmental probe −65"}</button>}<p>{locale==="de"?"Leite den plausibelsten Sektor aus Biom, Wetter und Zeit ab. Die Fixtures sind intern konsistente Lernmodelle, keine exakten Encounter-Koordinaten.":"Infer the most plausible sector from biome, weather and time. Fixtures are internally consistent learning models, not exact encounter coordinates."}</p></section><RegionalAtlas region={current.region} locale={locale} onSector={choose} activeSector={feedback?.sector}/></div>{feedback&&<Feedback good={feedback.good}><span><b>{feedback.good?(locale==="de"?"Ökologische Signatur bestätigt":"Ecological signature confirmed"):(locale==="de"?"Sektor widerspricht den Umweltspuren":"Sector conflicts with the environmental evidence")}</b><small>{node?.name[locale]} · {node?.biome} · {current.region.name[locale]}</small></span><button onClick={next}>{feedback.good?(locale==="de"?"Nächste Region":"Next region"):(locale==="de"?"Sonde neu kalibrieren":"Recalibrate probe")} →</button></Feedback>}</div>;
}

const clashRounds=[
 {attacker:4,defender:1,options:["fire","water","ground","normal"]},
 {attacker:25,defender:74,options:["electric","normal","flying","poison"]},
 {attacker:7,defender:95,options:["water","normal","electric","poison"]},
 {attacker:58,defender:46,options:["fire","grass","normal","ground"]},
 {attacker:66,defender:131,options:["fighting","ground","normal","ice"]},
];
function LegacyTypeClashArena({locale,difficulty,generationCap,roundCount,onFinish}:GameProps){
 const rounds=useMemo(()=>{const pool=SPECIES.filter((entry)=>entry.generation<=generationCap&&!entry.mythical);return Array.from({length:roundCount},(_,index)=>{const attacker=pool[(index*37+generationCap*3)%pool.length],defender=pool[(index*67+71)%pool.length];const optionTypes=[...new Set([...attacker.types,["fire","water","grass","electric","ground","ice","fighting","psychic","rock","ghost"][index%10],["normal","flying","poison","bug","dragon","dark","steel","fairy"][index%8]])].slice(0,4);const options=optionTypes.map((type,slot)=>({id:`${index}-${type}`,type,power:[55,70,85,60][slot],modifier:[1.08,.94,1,1.04][slot],tag:slot===0?{en:"precise",de:"präzise"}:slot===1?{en:"guard break",de:"Schildbruch"}:{en:"standard",de:"standard"}}));return{attacker,defender,options}})},[generationCap,roundCount]);const [round,setRound]=useState(0);const [score,setScore]=useState(0);const [correctCount,setCorrectCount]=useState(0);const [hearts,setHearts]=useState(difficulty==="hard"?2:3);const [combo,setCombo]=useState(0);const [selected,setSelected]=useState<string|null>(null);const [outcome,setOutcome]=useState<{good:boolean;nextScore:number;nextCorrect:number;nextHearts:number;damage:number}|null>(null);const data=rounds[round],attacker=data.attacker,defender=data.defender;const damage=(move:typeof data.options[number])=>Math.round(move.power*typeMultiplier(move.type,defender.types)*(attacker.types.includes(move.type)?1.5:1)*move.modifier);const best=Math.max(...data.options.map(damage));const good=outcome?.good??false;
 const lock=(id:string)=>{if(selected)return;const move=data.options.find((item)=>item.id===id)!;const dealt=damage(move),success=dealt===best;const gained=success?dealt*3+combo*80:Math.round(dealt);const nextScore=score+gained,nextCorrect=correctCount+(success?1:0),nextHearts=Math.max(0,hearts-(success?0:1));setSelected(id);setScore(nextScore);setCorrectCount(nextCorrect);setHearts(nextHearts);setOutcome({good:success,nextScore,nextCorrect,nextHearts,damage:dealt});if(success)setCombo((value)=>value+1);else setCombo(0)};
 const next=()=>{if(!outcome)return;const completed=round+1,encountered=rounds.slice(0,completed).flatMap((item)=>[item.attacker.id,item.defender.id]);if(completed>=rounds.length||outcome.nextHearts<=0)onFinish(outcome.nextScore,outcome.nextCorrect,completed,encountered);else{setRound((value)=>value+1);setSelected(null);setOutcome(null)}};
 return <div className={`poke-clash ${outcome?"has-impact":""}`}><RunHud score={score} round={round+1} total={rounds.length} resource={hearts} label="SHIELDS"/><section className="poke-battle-stage"><div className="poke-battle-scanlines"/><div className="poke-fighter is-player"><PokemonSprite entry={attacker} size={180}/><b>{attacker.name[locale]}</b><small>{attacker.types.join(" · ")}</small></div><Swords className="poke-clash-mark"/><div className="poke-fighter is-rival"><PokemonSprite entry={defender} size={180}/><b>{defender.name[locale]}</b><small>{defender.types.join(" · ")}</small>{outcome&&<strong className="poke-impact-number">−{outcome.damage}</strong>}</div></section><p className="poke-ruleset">{locale==="de"?"Simulator: Power × moderne Typenwirkung × 1,5 STAB × Taktikmodifikator. Doppeltypen multiplizieren sich.":"Simulator: power × modern type effectiveness × 1.5 STAB × tactical modifier. Dual types multiply."}</p><div className="poke-move-deck">{data.options.map((move)=>{const multiplier=typeMultiplier(move.type,defender.types);return <button key={move.id} disabled={!!selected} onClick={()=>lock(move.id)} style={{"--type-color":TYPE_COLORS[move.type]} as React.CSSProperties}><span><b>{move.type.toUpperCase()}</b><small>{move.power} PWR · {move.tag[locale]}</small></span>{selected&&<strong>{damage(move)} DMG<small>{multiplier}×</small></strong>}</button>})}</div>{selected&&<Feedback good={good}>{good?<Shield/>:<ShieldAlert/>}<span><b>{good?(locale==="de"?"Optimale Schadenslinie":"Optimal damage line"):(locale==="de"?"Stärkere taktische Linie verfügbar":"Stronger tactical line available")}</b><small>{outcome?.damage} expected damage · combo {combo}</small></span><button onClick={next}>{locale==="de"?"Nächster Kampf":"Next clash"} →</button></Feedback>}</div>;
}

const draftIds=[3,6,9,12,18,25,31,34,36,38,45,47,55,59,65,68,71,76,82,94,103,121,124,130,131,134,135,136,142,143];
const trialPool=["water","fire","psychic","dragon","ground","flying","steel","fairy","dark","rock","electric","grass","ice","fighting","ghost","poison","bug"];
function LegacyGymDraftGauntlet({locale,difficulty,generationCap,roundCount,runSeed,onFinish}:GameProps){
 const pool=useMemo(()=>{if(generationCap===1)return seededShuffle(draftIds.map(species),runSeed);const scoped=seededShuffle(SPECIES.filter((entry)=>entry.generation<=generationCap),runSeed);const step=Math.max(1,Math.floor(scoped.length/30));return scoped.filter((_,index)=>index%step===0).slice(0,30)},[generationCap,runSeed]);const trials=useMemo(()=>Array.from({length:roundCount},(_,index)=>seededShuffle(trialPool,`${runSeed}:${Math.floor(index/trialPool.length)}`)[index%trialPool.length]),[roundCount,runSeed]);const [draft,setDraft]=useState<number[]>([]);const [locked,setLocked]=useState(false);const budget=difficulty==="easy"?520:difficulty==="medium"?460:420;const cost=(id:number)=>Math.round(Object.values(species(id).stats).reduce((a,b)=>a+b,0)/6);const spent=draft.reduce((sum,id)=>sum+cost(id),0);
 const toggle=(id:number)=>setDraft((items)=>items.includes(id)?items.filter((item)=>item!==id):items.length<6&&spent+cost(id)<=budget?[...items,id]:items);
 const report=trials.map((trial)=>{const best=Math.max(...draft.flatMap((id)=>species(id).types.map((type)=>typeMultiplier(type,[trial]))));return{trial,best}});
 const coverage=report.filter((item)=>item.best>1).length;const typeDiversity=new Set(draft.flatMap((id)=>species(id).types)).size;const score=coverage*500+typeDiversity*80+Math.max(0,budget-spent);
 if(locked)return <div className="poke-draft-report"><RunHud score={score} round={roundCount} total={roundCount}/><header><p className="poke-kicker">AUTO-RESOLUTION / COVERAGE CONSOLE</p><h2>{locale==="de"?"Prüfungsbericht":"Trial report"}</h2></header><div className="poke-radar-console"><div className="poke-radar-rings">{report.map((item,index)=><span key={`${item.trial}-${index}`} style={{["--ray" as string]:`${index*(360/report.length)}deg`,["--reach" as string]:`${Math.min(90,item.best*35)}%`}}>{item.trial}<i/></span>)}</div><aside>{report.map((item,index)=><div key={`${item.trial}-${index}`} className={item.best>1?"is-pass":""}><b>{item.trial}</b><span>{item.best}× best available</span></div>)}</aside></div><button className="poke-primary" onClick={()=>onFinish(score,coverage,roundCount,draft)}>{locale==="de"?"Run abschließen":"Complete run"}</button></div>;
 return <div className="poke-draft"><RunHud score={0} round={draft.length} total={6} resource={budget-spent} label="BUDGET"/><header className="poke-draft-header"><div><p className="poke-kicker">BLIND TYPE TRIAL SEQUENCE</p><h2>{locale==="de"?"Drafte sechs unter Budget":"Draft six under budget"}</h2></div><div>{spent}<small> / {budget}</small></div></header><div className="poke-draft-layout"><div className="poke-roster-wall">{pool.map((entry)=><button key={entry.id} onClick={()=>toggle(entry.id)} className={draft.includes(entry.id)?"is-drafted":""} disabled={!draft.includes(entry.id)&&(draft.length>=6||spent+cost(entry.id)>budget)}><PokemonSprite entry={entry} size={82}/><span>#{entry.id} · {cost(entry.id)}</span><b>{entry.name[locale]}</b></button>)}</div><aside className="poke-draft-tray"><span>FIELD SIX</span>{[0,1,2,3,4,5].map((slot)=>draft[slot]?<button key={slot} onClick={()=>toggle(draft[slot])}><PokemonSprite entry={species(draft[slot])} size={65}/><small>{species(draft[slot]).name[locale]}</small></button>:<div key={slot}>EMPTY</div>)}<p>{locale==="de"?"Coverage-Analyse bleibt bis zum Lock verborgen.":"Coverage analysis remains sealed until lock-in."}</p><button className="poke-primary" disabled={draft.length!==6} onClick={()=>setLocked(true)}>LOCK DRAFT <LockKeyhole/></button></aside></div></div>;
}
