"use client";
import {useMemo,useRef,useState} from "react";
import {AudioLines,Check,CircleHelp,FlaskConical,Heart,Mic2,ScanLine,Search,X} from "lucide-react";
import {SPECIES,species} from "@/poke/data";
import {EVOLUTION_FAMILIES,GRID_COLS,GRID_ROWS,buildDynamicCase,isGridPlacementValid} from "@/poke/fixtures";
import {PokemonSprite} from "../pokemon-sprite";
import {Feedback,RunHud,type GameProps} from "../gameplay";

export function EvolutionLab({locale,difficulty,generationCap,onFinish}:GameProps){
 const eligible=EVOLUTION_FAMILIES.filter((family)=>species(family.nodes[0]).generation<=generationCap);const family=eligible[Math.min(eligible.length-1,difficulty==="hard"?eligible.length-1:0)]??EVOLUTION_FAMILIES[0];
 const ordered=[...family.nodes];const initial=difficulty==="easy"?[...ordered]:[...ordered].reverse();const [pool,setPool]=useState<number[]>(initial);const [placed,setPlaced]=useState<number[]>([]);const [condition,setCondition]=useState<string[]>([]);const [rejected,setRejected]=useState<number>();const expected=ordered[placed.length];
 const place=(id:number)=>{if(id!==expected){setRejected(id);setTimeout(()=>setRejected(undefined),350);return}setPlaced((items)=>[...items,id]);setPool((items)=>items.filter((item)=>item!==id))};
 const conditionsCorrect=family.edges.every((edge,index)=>condition[index]===edge.condition.en);
 const complete=placed.length===ordered.length&&conditionsCorrect;
 return <div className="poke-lab"><RunHud score={(placed.length+condition.length)*180} round={placed.length+condition.length} total={ordered.length+family.edges.length}/><header className="poke-lab-header"><FlaskConical/><div><p className="poke-kicker">CHAIN RIG // VERIFIED CONDITIONS</p><h2>{locale==="de"?"Rekonstruiere die Entwicklungsfamilie":"Reconstruct the evolution family"}</h2></div></header><section className={`poke-evolution-rig ${complete?"is-active":""}`}>
  {ordered.map((id,index)=><div className="poke-evolution-slot" key={id}>{placed[index]===id?<PokemonSprite entry={species(id)} size={125}/>:<span>SPECIMEN {index+1}</span>}{index<ordered.length-1&&<div className="poke-condition-port"><select aria-label={`Evolution condition ${index+1}`} value={condition[index]??""} onChange={(event)=>setCondition((items)=>{const next=[...items];next[index]=event.target.value;return next})}><option value="">CONDITION?</option>{[family.edges[index].condition.en,"Level 20","High friendship","Evolution stone"].sort().map((item)=><option key={item} value={item}>{locale==="de"&&item===family.edges[index].condition.en?family.edges[index].condition.de:item}</option>)}</select><span>→</span></div>}</div>)}
 </section><div className="poke-specimen-drawer">{pool.map((id)=><button key={id} className={rejected===id?"is-rejected":""} onClick={()=>place(id)}><PokemonSprite entry={species(id)} size={100}/><b>{species(id).name[locale]}</b></button>)}</div>{placed.length===ordered.length&&!complete&&<Feedback good={false}><X/><span><b>{locale==="de"?"Reihenfolge stabil, Bedingungen prüfen":"Sequence stable; verify the conditions"}</b></span></Feedback>}{complete&&<Feedback good><Check/><span><b>{locale==="de"?"Evolutionsrig aktiviert":"Evolution rig activated"}</b><small>{locale==="de"?"Bedingungen: kuratierter National-Dex-Lernstand":"Conditions: curated National Dex learning rules"}</small></span><button onClick={()=>onFinish(1500,1,1,ordered)}>Archive →</button></Feedback>}</div>;
}

const scannerIndices=[24,92,128,201,248,385,509,701,887];
export function FieldScanner({locale,difficulty,generationCap,onFinish}:GameProps){
 const max=SPECIES.filter((entry)=>entry.generation<=generationCap);const target=max[scannerIndices[generationCap-1]%max.length]??max[24];const candidates=useMemo(()=>{const nearby=max.filter((entry)=>entry.id!==target.id&&entry.types.some((type)=>target.types.includes(type))).slice(0,difficulty==="easy"?5:7);return [...nearby,target].sort((a,b)=>(a.id*13)%17-(b.id*13)%17)},[difficulty,max,target]);
 const [hints,setHints]=useState<string[]>([]);const [guess,setGuess]=useState<number|null>(null);const [signal,setSignal]=useState(100);const hintOptions=[
  {id:"type",cost:18,text:`${locale==="de"?"Typ":"Type"}: ${target.types.join(" / ")}`},
  {id:"generation",cost:12,text:`${locale==="de"?"Einführungs-Generation":"Introduction generation"}: ${target.generation}`},
  {id:"habitat",cost:16,text:`${locale==="de"?"Habitat":"Habitat"}: ${target.habitat}`},
  {id:"measure",cost:20,text:`${target.heightM} m · ${target.weightKg} kg`},
 ];
 const correct=guess===target.id;const buy=(id:string,cost:number)=>{if(hints.includes(id)||guess)return;setHints((items)=>[...items,id]);setSignal((value)=>value-cost)};
 return <div className="poke-scanner-game"><RunHud score={signal*12} round={guess?1:0} total={1} resource={signal} label="SIGNAL"/><div className="poke-scanner-layout"><section className={`poke-scanner-window hints-${hints.length} ${guess?"is-resolved":""}`}><div className="poke-reticle"/><ScanLine/><PokemonSprite entry={target} size={250} concealed={!guess} pixelated={!guess&&hints.length<2} label={!!guess}/><span>{guess?`#${String(target.id).padStart(4,"0")} · ${target.name[locale]}`:"SPECIMEN ID REDACTED"}</span></section><aside className="poke-hint-console"><p className="poke-kicker">BUY RESOLUTION</p>{hintOptions.map((hint)=><button key={hint.id} onClick={()=>buy(hint.id,hint.cost)} disabled={hints.includes(hint.id)||!!guess}><CircleHelp/><span>{hints.includes(hint.id)?hint.text:`${hint.id.toUpperCase()} · −${hint.cost}`}</span></button>)}</aside></div><div className="poke-candidate-film">{candidates.map((entry)=><button key={entry.id} disabled={guess!==null} onClick={()=>setGuess(entry.id)} className={guess===entry.id?(correct?"is-correct":"is-wrong"):""}><PokemonSprite entry={entry} size={90}/><span>{entry.name[locale]}</span></button>)}</div>{guess&&<Feedback good={correct}>{correct?<Check/>:<X/>}<span><b>{correct?(locale==="de"?"Scanner-Lock bestätigt":"Scanner lock confirmed"):`${locale==="de"?"Gesucht":"Target"}: ${target.name[locale]}`}</b><small>#{target.id} · {target.types.join(" / ")} · Gen {target.generation}</small></span><button onClick={()=>onFinish(correct?signal*12:Math.round(signal*4),correct?1:0,1,[target.id])}>File specimen →</button></Feedback>}</div>;
}

const cryIndices=[6,24,93,151,250,384,717,791,887];
export function CryRadar({locale,difficulty,generationCap,onFinish}:GameProps){
 const pool=SPECIES.filter((entry)=>entry.generation<=generationCap&&entry.cry);const target=pool[cryIndices[generationCap-1]%pool.length]??pool[0];const candidates=useMemo(()=>[target,...pool.filter((entry)=>entry.id!==target.id&&entry.shape===target.shape).slice(0,3)].sort((a,b)=>(a.id*7)%11-(b.id*7)%11),[pool,target]);const audio=useRef<HTMLAudioElement>(null);const [playing,setPlaying]=useState(false);const [failed,setFailed]=useState(false);const [guess,setGuess]=useState<number|null>(null);const correct=guess===target.id;
 const play=async()=>{if(!audio.current)return;try{await audio.current.play();setPlaying(true)}catch{setFailed(true)}};
 return <div className="poke-cry"><RunHud score={guess?(correct?1000:200):0} round={guess?1:0} total={1}/><section className={`poke-spectrum ${playing?"is-playing":""}`}><audio ref={audio} src={target.cry??undefined} onEnded={()=>setPlaying(false)} onError={()=>setFailed(true)}/><div className="poke-spectrum-bars">{Array.from({length:48},(_,index)=><i key={index} style={{["--bar" as string]:`${18+(index*37%74)}%`,["--delay" as string]:`${index*-27}ms`}}/>)}</div><div className="poke-radar-dial"><AudioLines/><span>{failed?"MEDIA SIGNAL FAILED":playing?"LIVE SIGNAL":"READY / NO AUTOPLAY"}</span></div><button className="poke-audio-button" onClick={play} disabled={failed}><Mic2/>{playing?(locale==="de"?"Wird abgespielt":"Playing"):(locale==="de"?"Ruf abspielen / wiederholen":"Play / replay cry")}</button></section><div className="poke-cry-candidates">{candidates.map((entry)=><button key={entry.id} disabled={guess!==null||failed} onClick={()=>setGuess(entry.id)}><PokemonSprite entry={entry} size={125}/><b>{entry.name[locale]}</b><small>#{entry.id}</small></button>)}</div>{failed?<Feedback good={false}><span><b>{locale==="de"?"Audiodatei nicht verfügbar":"Audio file unavailable"}</b><small>{locale==="de"?"Diese Runde kann ohne Lebensverlust übersprungen werden.":"Skip this round without losing a life."}</small></span><button onClick={()=>onFinish(0,0,0,[])}>Skip safely →</button></Feedback>:guess&&<Feedback good={correct}><span><b>{correct?(locale==="de"?"Akustischer Treffer":"Acoustic match"):`${locale==="de"?"Signal war":"Signal was"} ${target.name[locale]}`}</b></span><button onClick={()=>onFinish(correct?1000:200,correct?1:0,1,[target.id])}>Archive →</button></Feedback>}</div>;
}

export function PokeGrid({locale,difficulty,generationCap,onFinish}:GameProps){
 const allowed=SPECIES.filter((entry)=>entry.generation<=generationCap);const [cells,setCells]=useState<Record<number,number>>({});const [active,setActive]=useState<number|null>(null);const [query,setQuery]=useState("");const [strikes,setStrikes]=useState(0);const [rejected,setRejected]=useState<number|null>(null);const used=Object.values(cells);
 const options=active===null?[]:allowed.filter((entry)=>!used.includes(entry.id)&&entry.name[locale].toLowerCase().includes(query.toLowerCase())).slice(0,36);
 const complete=Object.keys(cells).length===9;const score=Math.max(180,used.length*180-strikes*70);const choose=(id:number)=>{if(active===null)return;const row=Math.floor(active/3),col=active%3;if(!isGridPlacementValid(id,row,col,used)){setStrikes((value)=>value+1);setRejected(id);return}setCells((state)=>({...state,[active]:id}));setActive(null);setRejected(null);setQuery("")};
 return <div className="poke-grid-game"><RunHud score={score} round={used.length} total={9} resource={strikes} label="STRIKES"/><header><p className="poke-kicker">DAILY MATRIX // GEN 1–{generationCap}</p><h2>{locale==="de"?"Neun gültige, verschiedene Spezies":"Nine valid, distinct species"}</h2></header><div className="poke-grid-board"><div className="poke-grid-corner">ROW × COL</div>{GRID_COLS.map((item,index)=><div className="poke-grid-label" key={index}>{item.label[locale]}</div>)}{GRID_ROWS.flatMap((row,rowIndex)=>[<div className="poke-grid-label" key={`r-${rowIndex}`}>{row.label[locale]}</div>,...[0,1,2].map((colIndex)=>{const cell=rowIndex*3+colIndex;const id=cells[cell];return <button key={cell} onClick={()=>setActive(cell)} className={id?"is-filled":""}>{id?<><PokemonSprite entry={species(id)} size={80}/><small>{species(id).name[locale]}</small></>:<span>+</span>}</button>})])}</div>{active!==null&&<div className="poke-grid-search"><header><Search/><input autoFocus value={query} onChange={(event)=>{setQuery(event.target.value);setRejected(null)}} placeholder={locale==="de"?"Pokémon im aktiven Gen-Pool suchen":"Search the active generation pool"} /><button onClick={()=>setActive(null)}>×</button></header><p>{GRID_ROWS[Math.floor(active/3)].label[locale]} × {GRID_COLS[active%3].label[locale]}</p>{rejected!==null&&<div className="poke-grid-reject" role="status">{locale==="de"?`${species(rejected).name.de} erfüllt diese Schnittmenge nicht. Versuche es erneut.`:`${species(rejected).name.en} does not satisfy this intersection. Try again.`}</div>}<div>{options.map((entry)=><button key={entry.id} className={rejected===entry.id?"is-rejected":""} onClick={()=>choose(entry.id)}><PokemonSprite entry={entry} size={65}/><span>{entry.name[locale]}<small>#{entry.id}</small></span></button>)}</div></div>}{complete&&<Feedback good><Check/><span><b>{locale==="de"?"Matrix vollständig":"Matrix complete"}</b><small>{locale==="de"?"Lösungsanzahlen werden erst nach der Platzierung angezeigt.":"Solution counts are revealed only after placement."}</small></span><button onClick={()=>onFinish(score,9,9,used)}>Submit grid →</button></Feedback>}</div>;
}
export function ProfessorCaseFiles({locale,difficulty,generationCap,onFinish}:GameProps){
 const dossier=useMemo(()=>buildDynamicCase(generationCap),[generationCap]);const [revealed,setRevealed]=useState(1);const [crossed,setCrossed]=useState<number[]>([]);const [guess,setGuess]=useState<number|null>(null);const [confidence,setConfidence]=useState(difficulty==="hard"?80:60);const candidates=dossier.suspects.filter((entry)=>dossier.clues.slice(0,revealed).every((clue)=>clue.test(entry.id)));const correct=guess===dossier.target.id;const score=Math.max(100,1800-revealed*140)*(correct?1:0)*confidence/100;
 return <div className="poke-case"><RunHud score={Math.round(score)} round={revealed} total={dossier.clues.length}/><div className="poke-case-layout"><section className="poke-suspect-board"><header><p className="poke-kicker">CASE #{String(dossier.target.id*37).padStart(5,"0")}</p><h2>{locale==="de"?"Verdächtigenwand":"Suspect board"}</h2></header><div>{dossier.suspects.map((entry)=><button key={entry.id} className={crossed.includes(entry.id)?"is-crossed":""} onClick={()=>setCrossed((items)=>items.includes(entry.id)?items.filter((id)=>id!==entry.id):[...items,entry.id])} disabled={!!guess}><PokemonSprite entry={entry} size={95}/><span>{entry.name[locale]}</span>{crossed.includes(entry.id)&&<X/>}</button>)}</div></section><aside className="poke-evidence-ledger"><p className="poke-kicker">EVIDENCE LEDGER</p>{dossier.clues.slice(0,revealed).map((clue,index)=><div key={index}><span>E-{String(index+1).padStart(2,"0")}</span><p>{clue.label[locale]}</p></div>)}<p className="poke-candidate-count">{candidates.length} {locale==="de"?"logische Kandidaten":"logical candidates"}</p>{revealed<dossier.clues.length&&<button className="poke-secondary" onClick={()=>setRevealed((value)=>value+1)}>REVEAL EVIDENCE −140</button>}<label>CONFIDENCE <b>{confidence}%</b><input type="range" min="40" max="100" step="10" value={confidence} onChange={(event)=>setConfidence(Number(event.target.value))}/></label><div className="poke-case-lock">{dossier.suspects.filter((entry)=>!crossed.includes(entry.id)).map((entry)=><button key={entry.id} onClick={()=>setGuess(entry.id)} disabled={!!guess}>{entry.name[locale]}</button>)}</div></aside></div>{guess&&<Feedback good={correct}>{correct?<Check/>:<X/>}<span><b>{correct?(locale==="de"?"Fall logisch gelöst":"Case solved logically"):`${locale==="de"?"Zielakte":"Target dossier"}: ${dossier.target.name[locale]}`}</b><small>#{dossier.target.id} · {dossier.target.types.join(" / ")} · Gen {dossier.target.generation}</small></span><button onClick={()=>onFinish(Math.round(score),correct?1:0,1,[dossier.target.id])}>Seal dossier →</button></Feedback>}</div>;
}
